oaknational/Oak-Web-Application

src/components/QuizContainer/QuestionListItem/QuestionListItem.test.tsx, src/components/QuizContainer/QuestionListItem/QuestionListItem.tsx
- Fixes ordering of match answers in the  QuestionListItem component and amends test file
Fixes #1283 
1. Go to {cloud link}
=> chore(QuestionListItem): fixes match question type styling and test file

.github/dependabot.yml
Add config to allow Dependabot to open pull requests to update dependencies.
=> build(deps): configure dependabot

src/common-lib/forms/evaluateCondition.ts
Adding some docs
The docs exist
=> docs: demoing CI/CD

public/.well-known/security.txt
- Updated annual review date
- Updated GPG signature in line with changes
1. Go to https://www.thenational.academy/.well-known/security.txt
2. You should see `Expires: 2024-07-31T20:59:00.000Z`
=> chore(security.txt): review file and resign

oak-config/oak.config.test.json, scripts/build/write_env_file/index.js, src/config/server.ts
- add curriculumApi2023 config to config/server.ts
Progresses #1713
- App should still run
- There are no visible changes here, just plumbing
=> feat: add curriculum-api 2023 config

src/node-lib/curriculum-api-2023/fixtures/searchPage.fixtures.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.test.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/searchPage.gql, src/pages/beta/[viewType]/search.tsx
connect teachers-2023/search to hasura endpoint
Fixes #
1. Go to beta/teachers-2023/search
3. You should see filters and page working as before but with 2023 data
{screenshots}
{screenshots}
=> [LESQ-46] Feat/connect search to hasura

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/downloads/downloads.gql, src/node-lib/curriculum-api-2023/queries/downloads/downloads.query.test.ts, src/node-lib/curriculum-api-2023/queries/downloads/downloads.query.ts, src/node-lib/curriculum-api-2023/queries/downloads/downloads.schema.ts, src/node-lib/curriculum-api/fixtures/lessonDownloads.fixture.ts, src/node-lib/curriculum-api/index.ts, src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx
- add downlosds data to teachers-2023 downloads path
Fixes #
1. Go to /beta/teachers-2023/programmes/biology-secondary-ks4-10/units/cell-division-mitosis-and-meiosis/lessons/errors-in-cell-division-and-cancer-ft/downloads
2. 
3. You should see a downloads page with no downloadable resources
{screenshots}
{screenshots}
=> LESQ-53 Feat/connect downloads

src/components/UnitAndLessonLists/UnitList/UnitListItem/UnitListItem.test.tsx, src/context/Search/helpers.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.schema.ts, src/node-lib/curriculum-api/fixtures/unitListing.fixture.ts, src/node-lib/curriculum-api/fixtures/units.fixture.ts, src/node-lib/curriculum-api/index.ts, src/pages/beta/[viewType]/programmes/[programmeSlug]/units.tsx, src/utils/filterLearningTheme/filterLearningTheme.test.ts, src/utils/filterLearningTheme/filterLearningTheme.ts
- Fixes the learning theme filters on the beta to work with new content
Fixes # LESQ-82
1. Go to https://deploy-preview-1748--oak-web-application.netlify.thenational.academy
=> Feat/unit listing page filters LESQ-82

CHANGE_LOG.md, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/downloads/downloads.gql, src/node-lib/curriculum-api-2023/queries/downloads/downloads.schema.ts
-Connects downloads mv 2 
-Fixes no unitvariant programe factor programes 
1. Go to https://deploy-preview-1747--oak-web-application.netlify.thenational.academy
`/beta/teachers-2023/programmes/history-secondary-ks4-aqa/units/historic-environment-normans/lessons/lesson-35-in-historic-environment-normans/downloads`
`/beta/teachers-2023/programmes/english-secondary-ks4-aqa/units/power-and-conflict-poetry/lessons/lesson-26-in-romeo-and-juliet-part-1/downloads`
=> chore: connect mv downloads 2 - LESQ-84

src/components/LessonHelper/LessonHelper.stories.tsx, src/components/LessonHelper/LessonHelper.test.tsx, src/components/LessonHelper/LessonHelper.tsx, src/components/LessonOverview/LessonOverview.test.tsx, src/components/LessonOverview/LessonOverview.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.schema.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql, src/node-lib/curriculum-api/fixtures/lessonOverview.fixture.ts, src/node-lib/curriculum-api/index.test.ts, src/node-lib/curriculum-api/index.ts, src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx
- Wires up the Lesson Overview Page 
Fixes # LESQ-102
1. Go to https://deploy-preview-1755--oak-web-application.netlify.thenational.academy
look (delete if n/a):
=> chore(transform-lesson-overview): wires up the lesson overview page LESQ-102

package-lock.json, package.json
- Updates semver 
Fixes #
1. Go to https://deploy-preview-1771--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore: update semver

src/components/UnitAndLessonLists/ListItemHeader.tsx, src/components/UnitAndLessonLists/UnitList/UnitList.tsx, src/components/UnitAndLessonLists/UnitList/UnitListItem/UnitListItem.test.tsx, src/context/Search/helpers.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.gql, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.schema.ts, src/node-lib/curriculum-api/fixtures/unitListing.fixture.ts, src/node-lib/curriculum-api/fixtures/units.fixture.ts, src/node-lib/curriculum-api/index.ts, src/utils/filterLearningTheme/filterLearningTheme.test.ts
add null variant title to units with optionality
Fixes #
1. Go to https://deploy-preview-1785--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> LESQ-115 Feat/optionality title

sonar-project.properties
Move the SonarCloud JSON file exclusion from the test coverage list to the ignore list
=> chore(sonar cloud): move exclusion to the ignore list

src/__tests__/pages/beta/[viewType]/key-stages/[keyStageSlug]/subjects/index.test.tsx, src/pages/beta/[viewType]/key-stages/[keyStageSlug]/subjects/index.tsx
-  in subjectListing::getStaticProps only fetch from 2023 api if viewType is teachers-2023
=> fix(subject listing): only fetch 2023 api data if viewType 2023

src/components/pages/CurriculumInfo/tabs/OverviewTab/OverviewTab.tsx
- Comments out the video section on Curriculum Info Tab
Fixes #CUR-247
1. Go to (e.g.) https://deploy-preview-1878--oak-web-application.netlify.thenational.academy/beta/teachers/curriculum/english-primary/overview
(alternatively, select any subject and phase from the subject phase picker on https://deploy-preview-1878--oak-web-application.netlify.thenational.academy/beta/teachers/curriculum)
=> chore: comment out section CUR-247

infrastructure/web/.terraform.lock.hcl, infrastructure/web/lesson_video_buckets.tf, infrastructure/web/main.tf, infrastructure/web/monitoring.tf, infrastructure/web/variables.tf
- Cleanup the current Terraform to match current standards
- Add config changes to existing bucket def to match the current deployment
- Add a monitor reporting on errors in the log
[ENG-231](https://www.notion.so/oaknationalacademy/Alert-on-OWA-log-errors-25d6c681cf5440b2805eb8fcda54adae?pvs=4)
=> [ENG-231] Datadog owa alert

README.md
A superficial change in order to trigger a rebuild because we are switching the database from staging to prod
Fixes #
1. Go to https://deploy-preview-1954--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> feat: switch db to prod

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumUnits/curriculumUnits.gql, src/node-lib/curriculum-api-2023/queries/curriculumUnits/curriculumUnits.schema.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql
curriculumUnits.gql v3
lessonDownloads.gql  v6
lessonDownloadsCanonical.gql v6
lessonListing.gql v15
lessonOverview.gql v10
lessonOverviewCanoncical.gql v10
Fixes #
1. Go to https://deploy-preview-1961--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore: repoint gql queries

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumOverview/curriculumOverview.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql, src/node-lib/curriculum-api-2023/queries/programmeListing/progammeListing.gql, src/node-lib/curriculum-api-2023/queries/searchPage.gql, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.gql
Fixes #
1. Go to https://deploy-preview-2028--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> fix: temporary revert

src/common-lib/cms-types/base.ts
- Fixes incorrect asser schema zod error
Fixes #
1. Go to https://deploy-preview-2033--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> fix: incorrect asset schema plan a lesson

infrastructure/web/monitoring.tf
- A refactor to allow for multiple alerts
- A new alert on timeout logs
[ENG-488](https://www.notion.so/oaknationalacademy/Alert-on-slow-running-requests-on-OWA-fd8dce9ca6984fb598efd7573ad02452?pvs=4)
https://app.datadoghq.eu/monitors/13424181
=> [ENG-488] Alert on pages timing out

package-lock.json, package.json
Bumps [@actions/github](https://www.npmjs.com/package/@actions/github) to 6.0.0
=> chore(deps): github actions 6

src/pages/about-us/who-we-are.tsx
Music year: 1993
Fixes #LESQ-152
1. Go to https://deploy-preview-2141--oak-web-application.netlify.thenational.academy
=> chore: update headings LESQ-152

package-lock.json, package.json, src/components/PupilJourneyComponents/QuizEngineProvider/QuizEngineProvider.tsx, src/components/PupilJourneyComponents/QuizMCQSingleAnswer/QuizMCQSingleAnswer.tsx, src/components/PupilJourneyComponents/QuizRenderer/QuizRenderer.tsx
Music year: 1983
Fixes #
{screenshots}
{screenshots}
=> fix: refactor quiz render into seperate component

next.config.js, package-lock.json, package.json, sonar-project.properties, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.tsx, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.test.tsx, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx, src/components/PupilViews/PupilReview/PupilReview.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.gql, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.schema.ts, src/node-lib/curriculum-api/fixtures/pupilLessonOverview.fixture.ts, src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/index.tsx
add oak-components to pupilLessonReview page
Fixes #
1. Go to [https://deploy-preview-2219--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondar[…]-as-a-father-figure?section=review](https://deploy-preview-2219--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-ks4-aqa/units/macbeth-and-masculinity-the-struggle-for-power/lessons/duncan-as-a-father-figure?section=review)
2. this will take you to review with incomplete tasks
3. Go to [https://deploy-preview-2219--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondar[…]-as-a-father-figure](https://deploy-preview-2219--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-ks4-aqa/units/macbeth-and-masculi …
=> PUPIL-295 - Feat/pupil 295 pupil lesson review page

package-lock.json, package.json, src/__tests__/pages/pupils/index.test.tsx, src/components/PupilViews/PupilVideo/PupilVideo.test.tsx, src/components/PupilViews/PupilVideo/PupilVideo.view.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.gql, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.query.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.schema.ts, src/node-lib/curriculum-api/fixtures/pupilLessonOverview.fixture.ts, src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/index.tsx
Music year: [1986](https://www.youtube.com/watch?v=OJWJE0x7T4Q)
Adds the video player and transcript to the video page under the new pupil lesson journey. Also applies the initial phase of styling to the page.
1. Go to https://deploy-preview-2224--oak-web-application.netlify.thenational.academy/pupils/programmes/science-secondary-ks3/units/forces/lessons/what-forces-do
2. Click on "Watch video"
3. You should be able to play the video and view the transcript
1. The video length is not displayed on the lesson intro page — this currently reads `0 min` but will be removed in a subsequent ticket.
2. This does not include a responsive landscape view for mobile like we are aiming for in the designs. When looking into implementing this I realised that it would be a considerable amount of work to …
=> PUPIL-291: Video page final styling

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumUnits/curriculumUnits.gql
Music year: 2018
1. Update API request for curriculum visualiser to curriculum_units_0_1
=> feat: switch to curriculum_units_0_1

package-lock.json, package.json, src/components/PupilComponents/CopyrightNotice/CopyrightNotice.test.tsx, src/components/PupilComponents/CopyrightNotice/CopyrightNotice.tsx, src/components/PupilComponents/CopyrightNotice/index.tsx, src/components/PupilViews/PupilIntro/PupilIntro.view.tsx
Music year: [1975](https://www.youtube.com/watch?v=dAoaVU3-ve0)
Displays the legacy copyright notice for legacy lessons and the current license for new lessons
1. Go to https://deploy-preview-2243--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-ks3/units/graphical-representations-of-data/lessons/constructing-bar-charts-by-utilising-technology
2. Click on "Intro"
3. You should see the correct licence and links
=> feat(PUPIL-285): add copyright notice to lesson `PupilIntro`

README.md
trying to convince netlify to rebuild after a skipped build
=> docs: superficial change

src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/index.tsx
fooling netlify into releasing a new version
=> fix: superficial change

src/components/PupilComponents/QuizAttribution/QuizAttribution.test.tsx, src/components/PupilComponents/QuizAttribution/QuizAttribution.tsx, src/components/PupilComponents/QuizRenderer/QuizRenderer.tsx, src/node-lib/curriculum-api-2023/fixtures/quizElements.fixture.ts
Music year: [1951](https://www.youtube.com/watch?v=bjCoKslQOEs)
Displays image attribution when present below the questions of a starter or exit quiz.
1. Go to https://deploy-preview-2245--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-ks2/units/developing-reading-preferences-in-year-5/lessons/developing-reading-preferences-in-year-5-through-appreciation-of-characters
2. Click on "Starter Quiz"
3. You should see attribution text beneath the first question 
https://deploy-preview-2245--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-ks2/units/developing-reading-preferences-in-year-6/lessons/developing-reading-preferences-by-appreciating-characters-in-adaptations
https://deploy-preview-2245--oak-web-application.netlify.then …
=> feat(PUPIL-166): display attribution for quiz images

src/pages/legal/[policyPageSlug].tsx
Support internal links of policy pages
=> fix(policy): allow general internal links

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.gql
- revert mv versions for lesson overview and lesson downloads
=> fix: rollback mv versions for lesson downloads and overview

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.gql
- mv lesson overview and downloads versions were rolled back to allow fixing migrations on production, this PR reinstates the latest versions
=> feat: reinstate latest mv versions for downloads and lesson overview

src/components/PupilComponents/pupilUtils/requestLessonResources.test.ts, src/components/PupilComponents/pupilUtils/requestLessonResources.ts
until now we were using the `getDownloadResourcesExistence` function which hits the legacy or the new download API depending on whether the lesson is a legacy or new lesson. The legacy endpoint will 404 when the worksheet does not exist instead of returning a successful response with the `exists` field set to `false` for the worksheet as expected. This causes errors to be thrown and caught by Bugsnag which is not desirable.
We have a query `lessonDownloadsCanonical` which appears to be able to fulfil the same function as `getDownloadResourcesExistence` without the the munging of the responses and appears to work for both legacy and new lessons since the great migration.
1. Go to https://deploy-preview-2305--oak-web-application.netlify.thenational.academy/pupils/lessons/prologue-grime-mix-c …
=> PUPIL-507: use download canonical query for the worksheet download check

src/__tests__/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.test.tsx, src/components/TeacherViews/SpecialistLessonDownloads/SpecialistLessonDownloads.fixture.ts, src/components/TeacherViews/SpecialistLessonDownloads/SpecialistLessonDownloads.view.tsx, src/node-lib/curriculum-api-2023/fixtures/specialistLessonDownloads.fixture.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.gql, src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.query.test.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.query.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.schema.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.schema.ts, src/node-lib/curriculum-api-2023/shared.schema.ts, src/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx
Music year: 1974
- adds queries, schema and page for specialist lesson downloads
- next lesson links on downloads success page still TODO
Yet another 'no changes in preview' PR. 
1. Go to https://deploy-preview-2306--oak-web-application.netlify.thenational.academy/teachers/specialist/programmes/independent-living-applying-learning/units/staying-safe-al-5556/lessons/online-safety-c5gk8r/downloads
2. Should be 'internal error' (404)
3. You should see the rest of the site remains the same
=> Feat/lesq 561/specialist download page [LESQ-561]

package-lock.json, package.json, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.test.tsx, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.tsx, src/components/PupilComponents/QuizMatchAnswer/QuizMatchAnswer.test.tsx, src/components/PupilComponents/QuizMatchAnswer/QuizMatchAnswer.tsx, src/components/PupilComponents/QuizMatchAnswer/index.ts, src/components/PupilComponents/QuizOrderAnswer/QuizOrderAnswer.test.tsx, src/components/PupilComponents/QuizOrderAnswer/QuizOrderAnswer.tsx, src/components/PupilComponents/QuizRenderer/QuizRenderer.tsx, src/components/PupilComponents/QuizUtils/answerTypeDiscriminators.ts, src/components/PupilComponents/QuizUtils/pickAnswerComponent.ts, src/components/PupilComponents/pupilTestHelpers/createQuizEngineContext.ts, src/components/PupilComponents/pupilUtils/invariant.ts, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx
Music year: [2005](https://youtu.be/Cj8JrQ9w5jY?si=M7zoobyyuhFJe6uo)
Adds support for match questions to pupil quizzes
1. Go to https://deploy-preview-2309--oak-web-application.netlify.thenational.academy/pupils/lessons/joining-using-and
2. Click on "Starter quiz"
3. Take the quiz including the match question
=> PUPIL-205: Match question UI

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.gql, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.gql, src/node-lib/curriculum-api-2023/queries/specialistLessonShare/specialistLessonShare.gql, src/node-lib/curriculum-api-2023/queries/specialistProgrammeListing/specialistProgrammeListing.gql, src/node-lib/curriculum-api-2023/queries/specialistProgrammeListing/specialistProgrammeListingCounts.gql, src/node-lib/curriculum-api-2023/queries/specialistSubjectListing/specialistSubjectListing.gql, src/node-lib/curriculum-api-2023/queries/specialistSubjectListing/specialistUnitsAndLessonCount.gql, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/developmentStageUnitCount.gql, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/developmentStages.gql, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistLessonCount.query.gql, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistUnitListing.gql
Music year: 1963
- Updates specialist queries to use mv_specialist_1_0_2
=> chore: updates mv queries to use new version

src/components/TeacherViews/SpecialistLesson/SpecialistLesson.view.tsx
- Makes Specialist Worksheets Landscape not Portrait
Fixes #LESQ-711
=> LESQ-711: Change worksheets from being displayed in Portrait to Landscape

next.config.js, src/__tests__/pages/pupils/l/[redirectFrom]/lessons/[lessonSlug]/[section].test.tsx, src/__tests__/pages/pupils/lessons/[lessonSlug]/[section].test.tsx, src/__tests__/pages/pupils/programmes/[programmesSlug]/units/[unitSlug]/lessons/[lessonSlug]/[section].test.tsx, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.test.tsx, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.tsx, src/components/PupilComponents/QuizMCQMultiAnswer/QuizMCQMultiAnswer.stories.tsx, src/components/PupilComponents/pupilUtils/lessonNavigation.test.tsx, src/components/PupilComponents/pupilUtils/lessonNavigation.tsx, src/components/PupilViews/PupilExperience/PupilExperience.view.test.tsx, src/components/PupilViews/PupilExperience/PupilExperience.view.tsx, src/components/PupilViews/PupilIntro/PupilIntro.view.test.tsx, src/components/PupilViews/PupilIntro/PupilIntro.view.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.test.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx, src/components/PupilViews/PupilReview/PupilReview.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx, src/components/PupilViews/PupilVideo/PupilVideo.view.tsx, src/pages/pupils/l/[redirectFrom]/lessons/[lessonSlug]/[section].tsx, src/pages/pupils/lessons/[lessonSlug]/[section].tsx, src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/[section].tsx
Music year: [1984](https://www.youtube.com/watch?v=2WN0T-Ee3q4)
Makes it possible to deep link to the sections in a lesson from all 3 URL schemes.
Also fixes https://www.notion.so/oaknationalacademy/Bug-OWA-back-button-keyboard-navigation-e80d7ffa99ea40b3bfc55dcb01672eb9?pvs=4
1. Go to https://deploy-preview-2327--oak-web-application.netlify.thenational.academy/pupils/l/acting-shakespeare-monologues-from-a-midsummer-nights-dream-723c/lessons/imagery-and-rhythm-in-shakespeares-language-c4tkat
2. Take the lesson
3. You should see the section change in the address bar as you navigate
1. Go to https://deploy-preview-2327--oak-web-application.netlify.thenational.academy/pupils/lessons/prologue-grime-mix-ccuk0d
2. Take the lesson
3. You should see the section change in the address bar as you …
=> PUPIL-517: Multi page pupil experience

src/pages/teachers/curriculum/index.tsx
Music year: 1988
Fixes #
1. Go to https://deploy-preview-2383--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> fix: updated blog slug to our-approach-to-curriculum

src/__tests__/pages/teachers/curriculum/index.test.tsx, src/common-lib/urls/getDeploymentTestUrls.js, src/components/TeacherComponents/LessonOverviewTranscriptViewer/LessonOverviewTranscriptViewer.tsx, src/components/TeacherComponents/LessonOverviewVideo/LessonOverviewVideo.tsx, src/pages/teachers/curriculum/index.tsx
Music year: 1988
- Add `aria-controls` on show/hide transcript button
- add `aria-expanded` on show/hide transcript button
- refator the expandable buttons so there is less duplication
Fixes #
https://www.notion.so/oaknationalacademy/I-want-expanded-true-false-on-the-transcript-component-2b6734dcfec74b958c1a8036c736008f?pvs=4
1. Go to https://deploy-preview-2405--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-higher-ocr/units/eukaryotic-and-prokaryotic-cells/lessons/cells#video
2. Click on show transcript
3. You should see the aria-expanded tag changes from hidden = true to false on toggle
=> Chore/lesq 752/transcript a11y expansion [LESQ-752]

src/__tests__/pages/lesson-planning-new.test.tsx, src/__tests__/pages/lesson-planning.fixture.ts, src/common-lib/cms-types/index.ts, src/common-lib/cms-types/planALessonPage.ts, src/common-lib/cms-types/planningPage.ts, src/node-lib/cms/sanity-client/index.ts, src/node-lib/sanity-graphql/__mocks__/index.ts, src/node-lib/sanity-graphql/fixtures/planALessonPage.json, src/node-lib/sanity-graphql/generated/sdk.ts, src/node-lib/sanity-graphql/queries/planALessonCorePage.gql, src/pages/lesson-planning-new.tsx
1. Go to https://deploy-preview-2408--oak-web-application.netlify.thenational.academy/lesson-planning-new
Open console - you should see test page data coming through from sanity
=> Feat/connect new plan a lesson cms - LESQ-814

src/pages/teachers/sitemap.xml/index.tsx
Music year: 2005
- Removes slice to render full sitemap
=> chore: remove slice to render sitemap fields

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
- Fixed duplicate removal of units from curriculum visualiser
`CUR-584`
1. Go to https://deploy-preview-2436--oak-web-application.netlify.thenational.academy
=> [CUR-584] fixed duplicate removal of units from curriculum visualiser

src/components/PupilComponents/BrowseTierSelector/BrowseTierSelector.tsx
Music year: 1978
Fixes #
1. Go to https://deploy-preview-2458--oak-web-application.netlify.thenational.academy/pupils/programmes/combined-science-secondary-year-10/options-l
2. Click on tier links
3. You should direct to correct tier page
{screenshots}
{screenshots}
=> PUPIL-751 feat(options): ensure tier link link to correct tier

src/components/TeacherViews/LessonOverview/LessonOverview.test.tsx
Music year: 1998
Fixes #
1. Go to https://deploy-preview-2470--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> feat: force re deploy

.github/workflows/create_semantic_release.yml, src/common-lib/urls/urls.test.ts
Music year: 2007
Fixes #
1. Go to https://deploy-preview-2498--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore(Netlify): trigger CI

scripts/build/image_data/generate_inline_sprite.js, scripts/build/image_data/generate_sprite.js, scripts/build/image_data/helpers.js
Music year: 1973
https://oaknationalacademy.slack.com/archives/C05QD9NE0P8/p1718186425945029
1. Go to https://deploy-preview-2501--oak-web-application.netlify.thenational.academy
2. You should see SVGs rendering us per usual 
{screenshots}
{screenshots}
=> fix: spritesheet chrome bug

package-lock.json, package.json, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructCanonicalLessonDownloads.test.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructCanonicalLessonDownloads.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructLessonDownloads.test.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructLessonDownloads.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.query.ts
Music year: 1975
- update curr schema version to stop zod errors crashing the site
- updates downloads to use a pre-parsed copyright object
=> fix: update curriculum schema to working version

package-lock.json, package.json
[v7.23.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.23.0)
Changed from previous version. Nothing which effects our code.
=> chore: bump bugsnag/js

package-lock.json, package.json
Updated `uuid` dependency
This is only used to generate a key in [`./src/components/TeacherComponents/TranscriptViewer/TranscriptViewer.tsx`](https://github.com/oaknational/Oak-Web-Application/blob/8281ded025612d3ee1b0ac8a9fe58ce3a39063ec/src/components/TeacherComponents/TranscriptViewer/TranscriptViewer.tsx#L40)
Breaking changes from [CHANGELOG.md](https://github.com/uuidjs/uuid/blob/6dcb15b86357afdf29ae2dabf5b2a8afab83c2c0/CHANGELOG.md)
> update node support (drop node@12, node@14, add node@20)
=> Update `uuid` dependency

package-lock.json, package.json
Removed `semver` dependency as it was no longer used in the codebase.
=> Remove `semver` dependency

package-lock.json, package.json
Updated `webpack` dependency. I've looked over the release changes (https://github.com/webpack/webpack/releases) nothing stands out and I've smoke tested the app locally.
=> Updated `webpack` dependency 

package-lock.json, package.json
=> chore(deps): percy cli v1.28.8 -> v1.28.9

package-lock.json, package.json
Music year: [1965](https://www.youtube.com/watch?v=MgJ9K7cPRKk)
- Bumps oak-consent-client@2.1.0
- Logs the first page a user landed on with the consent client as well as any UTM params
=> [ENG-818] Additional logging through consent client

src/components/CurriculumComponents/CurriculumDownloadTab/index.tsx
Reset state of the downloads tab when switching lots in curriculum downloads
Fixes `CUR-854`
=> Reset downloads tab when switching lots in curriculum downloads

src/components/CurriculumComponents/CurriculumDownloadTab/index.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.test.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx
Remove prerelease feature flags from curriculum-downloads (docx) and make it live 🎉
`CUR-757`
=> Remove prerelease from curriculum-downloads

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.gql
Update `published_mv_subject_phase_options_0_3` -> `published_mv_su…bject_phase_options_0_5` to fix curriculum subject phase picker.
`CUR-881`
=> Update `subject_phase_options` MV to fix subject phase picker

package.json
Music year: 1997
Fixes #
1. Go to https://deploy-preview-2758--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> feat: convience script added

src/components/CurriculumComponents/OakComponentsKitchen/FocusIndicator/FocusIndicator.stories.tsx, src/components/CurriculumComponents/OakComponentsKitchen/FocusIndicator/index.tsx, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.test.tsx, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Implementation of new phase picker designs.
Fixes `CUR-783`
=> New subject phase picker

next-env.d.ts, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx
Tidy some left over code from code review that was missed in https://github.com/oaknational/Oak-Web-Application/pull/2692#discussion_r1766939037
Fixes `CUR-923`
Test `<CurriculumHeader/>` still works as expected.
=> Tidy some left over code from code review

package-lock.json, package.json, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/pupilLesson/pupilLesson.gql, src/node-lib/curriculum-api-2023/queries/pupilLesson/pupilLesson.query.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonListing/pupilLessonListing.gql, src/node-lib/curriculum-api-2023/queries/pupilLessonListing/pupilLessonListing.query.ts, src/node-lib/curriculum-api-2023/queries/pupilUnitListing/pupilUnitListing.gql, src/node-lib/curriculum-api-2023/queries/pupilUnitListing/pupilUnitListing.query.ts, src/node-lib/curriculum-api-2023/queries/pupilsSitemap/pupilsSitemap.gql, src/node-lib/curriculum-api-2023/queries/pupilsSitemap/pupilsSitemap.query.ts
Music year: 2019
Fixes #
1. Go to https://deploy-preview-2874--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> Feat/pupil 1025/exclude swimming

package-lock.json, package.json, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/pupilLesson/pupilLesson.gql, src/node-lib/curriculum-api-2023/queries/pupilLesson/pupilLesson.query.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonListing/pupilLessonListing.gql, src/node-lib/curriculum-api-2023/queries/pupilLessonListing/pupilLessonListing.query.ts, src/node-lib/curriculum-api-2023/queries/pupilUnitListing/pupilUnitListing.gql, src/node-lib/curriculum-api-2023/queries/pupilUnitListing/pupilUnitListing.query.ts, src/node-lib/curriculum-api-2023/queries/pupilsSitemap/pupilsSitemap.gql, src/node-lib/curriculum-api-2023/queries/pupilsSitemap/pupilsSitemap.query.ts
Music year: 1999
Fixes #
{screenshots}
{screenshots}
=> Feat/pupil 1024/computing overrides

package-lock.json
`npm update express body-parser`
=> chore: npm update express body-parser

package-lock.json, package.json
Remove old `react-cookie` dependency
=> Remove old `react-cookie` dependency

src/common-lib/urls/urls.ts, src/components/CurriculumComponents/Banner/Banner.test.tsx, src/components/CurriculumComponents/Banner/Banner.tsx, src/components/SharedComponents/Button/ButtonAsLink/ButtonAsLink.tsx, src/components/SharedComponents/Button/button.styles.ts
Suggested alterations for https://github.com/oaknational/Oak-Web-Application/pull/2909 comments in line
=> Suggestions to keep `<ButtonAsLink/>` generic

scripts/dev/curriculum/_commands/screenshot.ts
Added page concatenation back into `./scripts/dev/curriculum/automate screenshot` which prevents the bottom footer appearing multiple times down the page.
No QA required dev tool only.
=> Added page concatination back into curric automate script

scripts/dev/curriculum/_commands/screenshot.ts, scripts/dev/curriculum/automate
Features
- Added cycle 2 subjects to curriculum automation script
- Also added `--remove-options` arg to remove options element from DOM (for new MV testing
Only dev script, no QA required.
=> Added cycle 2 subjects to curriculum automation script

scripts/dev/curriculum/_commands/compare.ts, scripts/dev/curriculum/_commands/screenshot.ts
The curriculum automation script now has the ability to screenshot all the tiers (as well as subject categories) of the units.
I've also made the sidebar scrollable when it overflows
No QA required
=> Added tiers to curriculum automation script screenshot command

scripts/dev/curriculum/_commands/screenshot.ts
Fixes for curric screenshot regression which was missing tiers/subjects.
Dev script no QA required.
=> Curric screenshot regression

.github/workflows/post_deployment_actions.yml
Fallback to `ubuntu-20.04` to fix pa11y issues.
Check if pa11y passes in CI
=> Fallback to `ubuntu-20.04` to fix pa11y issues

src/components/GenericPagesComponents/BioCardList/BioCardList.tsx, src/components/GenericPagesComponents/BioCardListModalDialog/BioCardListModalDialog.stories.tsx, src/components/GenericPagesComponents/GenericSummaryCardNavButton/GenericSummaryCardNavButton.tsx, src/components/GenericPagesComponents/HomepageCurriculumLandingHero/HomepageCurriculumLandingHero.tsx, src/components/GenericPagesComponents/HomepageTabImageButton/HomePageTabImageButton.tsx, src/components/GenericPagesComponents/LandingPageSignUpForm/LandingPageSignUpForm.tsx, src/components/GenericPagesComponents/PostQuote/PostQuote.tsx, src/components/GenericPagesComponents/PostTextAndMedia/PostTextAndMedia.tsx, src/components/GenericPagesComponents/PostVideo/PostVideo.tsx, src/components/GenericPagesComponents/TeachersTab/TeachersTab.tsx, src/components/GenericPagesComponents/UpcomingWebinarWall/UpcomingWebinarWall.stories.tsx, src/components/GenericPagesComponents/UpcomingWebinarWall/UpcomingWebinarWall.tsx, src/components/GenericPagesComponents/WebinarRegistration/WebinarRegistration.stories.tsx, src/components/GenericPagesComponents/WebinarVideo/WebinarVideo.stories.tsx
- /teachers/curriculum (header section)
- /about-us/board (nav links, bio card layout)
- /teachers (image tab buttons, search box width slightly reduced on desktop view)
- /lesson-planning (newsletter sign up, quote section, video player)
- Upcoming webinar - storybook
=> Chore/fec/generic pages - box

src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
Add a comment to force a redeploy
Just review the code
=> chore: added comment to force deploy

src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts
Improve some function names, raised in this code review comment https://github.com/oaknational/Oak-Web-Application/pull/3193#discussion_r1950955560
Fixes `CUR-1169`
Just code review (merging into feature branch _not_ `main`)
=> fix: improve some function naming

package-lock.json, package.json, src/components/CurriculumComponents/OakComponentsKitchen/Terms/__snapshots__/Terms.test.tsx.snap, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap, src/components/TeacherComponents/CopyrightNotice/CopyrightNotice.tsx, src/components/TeacherComponents/DownloadConfirmation/DownloadConfirmation.test.tsx, src/components/TeacherComponents/DownloadConfirmation/DownloadConfirmation.tsx, src/components/TeacherComponents/TermsAgreementForm/TermsAgreementForm.tsx, src/node-lib/curriculum-api-2023/fixtures/lessonDownloads.fixture.ts
Update post download message
Fixes [CTC-155](https://www.notion.so/oaknationalacademy/Update-post-download-message-19826cc4e1b18026a54bcb8aae8c057c)
1. Go to https://deploy-preview-3232--oak-web-application.netlify.thenational.academy/teachers/programmes/physical-education-secondary-ks4-gcse-aqa/units/anatomy-and-physiology-the-musculoskeletal-system/lessons/bones-and-structure-of-the-skeleton/downloads?preselected=all
2. Download files on any lesson, for example listed above
3. Validate that post download message is updated as per ACs
=> CTC-155 Update post download message

public/humans.txt
=> adding Ben T

package-lock.json, package.json, src/__tests__/__helpers__/mockClerkServer.ts, src/app/api/auth/onboarding/route.test.ts, src/app/api/auth/onboarding/route.ts, src/pages/api/hubspot/contacts/index.test.ts, src/pages/api/hubspot/contacts/index.ts, src/pages/api/hubspot/subscription/index.test.ts, src/pages/api/hubspot/subscription/index.ts
Music year: 1992
- Upgraded to latest version of Clerk which included a major version bump
1. Go to https://deploy-preview-3246--oak-web-application.netlify.thenational.academy
2. Go through the sign up, sign in and sign out processes
3. Check hubspot submissions for onboarding
4. You should see everything working as it should
=> Chore/upgrade clerk [LESQ-1299]

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersThreads.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersThreads.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersThreads.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersYears.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersYears.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersYears.test.tsx, src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx, src/fixtures/curriculum/childSubject/index.test.ts, src/fixtures/curriculum/childSubject/index.ts, src/fixtures/curriculum/tier/index.test.ts, src/fixtures/curriculum/tier/index.ts, src/fixtures/curriculum/unit/index.ts
Some initial tests/storybook using the new fixtures + repo setup.
Only dev QA required
=> Added tests/storybook for child subjects to new curric filtering branch

src/utils/curriculum/filtering.test.ts
Added missing tests for `.../curriculum/filtering.ts` in the new curriculum visualiser branch.
Just dev review needed as only test effected.
=> Added missing tests for `.../curriculum/filtering.ts`

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersYears.test.tsx, src/utils/getValidSubjectCategoryIconById.test.ts
100%  test coverage on `CurricFiltersYears.tsx` & `getValidSubjectCategoryIconById.ts`
Just requires dev code review, only test files effected.
=> Improve test coverage in curric filtering branch 

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersThreads.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersTiers.test.tsx
Added missing test cases for keystage specific titles in `.../CurricVisualiserFilters/*` tests
Additional tests only no QA required only dev review.
**Note**: We merging into the feature branch of PR #3100
=> Added missing keystage specific title tests into `.../CurricVisualiserFilters/*`

package-lock.json
`npm update @chromatic-com/storybook`
=> Update `@chromatic-com/storybook` dependency

package-lock.json
Update graphql deps `npm run update @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations`
=> Update `@graphql-codegen/*` deps

src/components/TeacherComponents/TeacherNotesModal/TeacherNotesModal.test.tsx
See <https://jestjs.io/docs/timer-mocks>
Requires dev review
=> Added `jest.useFakeTimers` to `<TeacherNotesModal/>`

src/utils/handleTranscript.test.ts
Mock out logging in "getCaptionsFromFile returns undefined" test
Only dev review required.
=> Mock out `console.error` in "getCaptionsFromFile returns undefined" test

src/components/GenericPagesComponents/CurriculumTab/CurriculumTab.tsx, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap
Reverts oaknational/Oak-Web-Application#3248
=> Revert "feat: add squiggle to curriculum landing page"

src/components/TeacherComponents/LessonOverviewFilesNeeded/LessonOverviewFilesNeeded.test.tsx, src/components/TeacherComponents/LessonOverviewFilesNeeded/LessonOverviewFilesNeeded.tsx
Copy update for additional files
Fixes [PUPIL-1273](https://www.notion.so/oaknationalacademy/Remove-Download-these-files-to-use-in-this-lesson-1c826cc4e1b1809985e2eae8d6ae7b75)
1. Go to https://deploy-preview-3339--oak-web-application.netlify.thenational.academy
2. Go to lesson with additional files
3. Validate the copy
=> PUPIL-1273 Copy update for additional files

sonar-project.properties, src/__tests__/pages/teachers/beta/programmes/[programmeSlug]/units/unitListing.test.tsx, src/node-lib/curriculum-api-2023/__mocks__/index.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.ts, src/node-lib/curriculum-api-2023/queries/teacherPreviewUnitListing/teacherPreviewUnitListing.gql, src/node-lib/curriculum-api-2023/queries/teacherPreviewUnitListing/teacherPreviewUnitListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/teacherPreviewUnitListing/teacherPreviewUnitListing.query.ts, src/pages/teachers/beta/programmes/[programmeSlug]/units.tsx
Created beta unit page
Fixes [PUPIL-1290](https://www.notion.so/oaknationalacademy/Create-beta-unit-page-1ce26cc4e1b18060be4bd4f3d1fde6d4)
1. Go to https://deploy-preview-3344--oak-web-application.netlify.thenational.academy/teachers/beta/programmes/physical-education-primary-ks2/units
2. You should see swimming units that aren't published
=> feat: beta unit page

package-lock.json, package.json, src/components/TeacherComponents/LessonOverviewMediaClips/LessonOverviewMediaClips.tsx, src/components/TeacherComponents/helpers/lessonHelpers/lesson.helpers.test.ts, src/components/TeacherComponents/helpers/lessonMediaHelpers/lessonMedia.helpers.ts, src/node-lib/curriculum-api-2023/fixtures/lessonAdditionalFiles.fixture.ts, src/node-lib/curriculum-api-2023/fixtures/lessonMediaClips.fixture.ts, src/node-lib/curriculum-api-2023/fixtures/lessonOverview.fixture.ts, src/node-lib/curriculum-api-2023/queries/lessonMediaClips/lessonMediaClips.schema.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.schema.ts
Media clips schema and fixture cleanup
Fixes [PUPIL-1276](https://www.notion.so/oaknationalacademy/Media-clips-cleanup-schemas-and-fixtures-1c826cc4e1b18021b40ae9b1f031240e)
https://deploy-preview-3349--oak-web-application.netlify.app/
Smoke test any of the media pages
=> PUPIL-1276 Media clips schema and fixture cleanup

public/humans.txt
Music year: 2016
- Adding Thomas Chan's website
- Adding Reece
Fixes #
- Updating John's title
- Moving Ben T to Thanks section
=> Chore_update_humans_txt

src/pages-helpers/curriculum/docx/builder/8_units/8_units.ts
Music year: 2015
- Fixed KS4 unit page ordering in DOCX downloads to group by pathway (Core then GCSE) instead of just year.
- Modified main year headings to include "(Core)" or "(GCSE)" suffix for KS4 pathways, improving document navigation clarity. This was discussed with @HelenHarlow.
- This was required to differentiate KS4 Year items in the navigation sidebar, as sidebar item text is inferred from heading text in the document.
- Removed redundant pathway information from the secondary heading above the main year title in
FYI @orangemug this branches off my previous branch as there was some work from that I needed to use here: [feat/CUR-1398-group-docx-thread-details](https://github.com/oaknational/Oak-Web-Application/tree/feat/CUR-1398-group-docx-thread-details).
Fixes …
=> fix: fix KS4 pathway ordering and headings in curriculum DOCX downloads

avo.json, src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessonListing.test.tsx, src/browser-lib/avo/Avo.ts, src/components/TeacherComponents/UnitList/UnitList.tsx, src/components/TeacherComponents/UnitList/helpers.test.tsx, src/components/TeacherComponents/UnitList/helpers.tsx, src/node-lib/educator-api/helpers/saveUnits/useSaveUnits.test.ts, src/node-lib/educator-api/helpers/saveUnits/useSaveUnits.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx
Music year: 2014
- Create 2 new events in Avo: Content Saved and Content Unsaved
- update useSaveUnits to call tracking on save and unsave
- pass in props from components 
1. Go to https://deploy-preview-3404--oak-web-application.netlify.thenational.academy
2. Try saving and unsaving units from both the unit listing and lesson listing pages
3. You should see posthog events being called with the correct props, either `contentSaved` or `contentUnsaved`
4. the `componentType` should reflect where the action is coming from, either unit listing or lesson listing page
5. the programme data should be correct
6. from specialist and therapies the 'key stage' will be "specialist"
=> Feat/lesq 1325/save events [LESQ-1325]

src/node-lib/educator-api/helpers/saveUnits/useSaveUnits.tsx, src/pages/api/educator-api/getSavedUnits/[programmeSlug].ts
Music year: 1984
- An attempt to fix [this error](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/682318dbd383ca45787459bb?filters[event.since]=30d&filters[app.release_stage]=production&filters[error.status]=open&pivot_tab=event) we're seeing in bugsnag `e.difference is not a function` in useSaveUnits
- I haven't been able to reproduce the error so can't be sure this will fix it
1. Go to https://deploy-preview-3412--oak-web-application.netlify.thenational.academy
2. Go to a unit listing page
3. There should be no errors
4. try again while signed in / out 
5. saving and unsaving should still work with the feature flag
=> fix: e.difference is not a function

src/components/CurriculumComponents/CurriculumHeaderTabNav/index.tsx, src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.tsx, src/utils/curriculum/filtering.test.ts
Fix some missing react `key`s and `act(...)` in curric causing warning in console in tests
none
Just code review required.
=> Fix some missing react `key`s and `act(...)` in curric

src/components/TeacherComponents/MyLibraryUnitCard/MyLibraryUnitCard.test.tsx, src/components/TeacherViews/LessonMedia/LessonMedia.test.tsx
Fixes:
- [test: offset index when to making react keys correct in fixtures](https://github.com/oaknational/Oak-Web-Application/pull/3439/commits/2f74d01fe14cb88805ebe7e843788e09c8b76147) 
Fixes `FEC-72`
Code review only
=> Remove more logging in tests

netlify/edge-functions/README.md, netlify/edge-functions/subdomain-redirects.ts, netlify/plugins/README.md, netlify/plugins/github-deployments/actions.js, netlify/plugins/github-deployments/index.js, netlify/plugins/github-deployments/manifest.yml, netlify/plugins/lib/index.js, netlify/plugins/slack-reporting/index.js, netlify/plugins/slack-reporting/manifest.yml, netlify/plugins/slack-reporting/slack/create_slack_message/e2e.js, netlify/plugins/slack-reporting/slack/create_slack_message/get_slack_config.js, netlify/plugins/slack-reporting/slack/create_slack_message/send_message.js
Music year: 1991 🎂 
https://www.notion.so/oaknationalacademy/Re-instantiate-all-the-netlify-logic-in-PR-1fa26cc4e1b1808e9aa6f12e5cd394e3?source=copy_link
Added the netlify folder and all contents back in, is this all that's required?
=> feat: reinstate netlify folder and contents

package-lock.json
Updates
- `@storybook/addon-a11y`
- `@storybook/addon-actions`
- `@storybook/addon-docs`
- `@storybook/addon-links`
- `@storybook/addon-onboarding`
- `@storybook/addon-webpack5-compiler-swc`
- `@storybook/cli`
- `@storybook/nextjs`
- `@storybook/react`
- `@types/storybook__addons`
=> Update all of storybook

infrastructure/project/.terraform.lock.hcl, infrastructure/project/locals.tf, infrastructure/project/main.tf, infrastructure/project/terraform.tf, infrastructure/project/variables.tf
- Add Vercel configuration using shared terraform module
[ENG-1237](https://www.notion.so/oaknationalacademy/Set-up-OWA-in-Vercel-with-Terraform-21426cc4e1b180de802efd372702d9c0)
1.
=> [ENG-1237] Set up OWA in Vercel 

infrastructure/project/.terraform.lock.hcl, infrastructure/project/builds.tf, infrastructure/project/locals.tf, infrastructure/project/main.tf, infrastructure/project/variables.tf
- deploys storybook build of OWA
[ENG-1241](https://www.notion.so/oaknationalacademy/Set-up-Storybook-in-Vercel-with-Terraform-21626cc4e1b180e6a6a1e451a5a1438c)
1. check that everything works as expected in vercel
=> [ENG-1241] Set up storybook in vercel

avo.json, src/browser-lib/avo/Avo.ts
Music year: 2011
- Updates avo to main branch
Fixes #
1. Go to https://deploy-preview-3520--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore: update avo to main branch [LESQ-1418]

src/components/TeacherViews/LessonMedia/LessonMedia.test.tsx, src/components/TeacherViews/LessonMedia/LessonMedia.view.tsx
Music year: 1951
- Track `contentBlockNotificationDisplayed` event when a geoblocked user accesses a georestricted media clips page
LESQ-1492
1. Go to media clip page for georestricted lesson https://deploy-preview-3529--oak-web-application.netlify.thenational.academy
2. Add your posthog id to `teachers-copyright-restrictions` feature flag
3. When signed out, should not see posthog Content Block event
4. When signed in but not geoblocked, should not see Content Block event
5. Go to Clerk and edit your user public metadata to `isRegionAuthorised: false`
6. Go to media clips page and should see Content Block event in console
=> feat: add tracking for accessing geoblocked media clips page [LESQ-1492]

CHANGE_LOG.md, package-lock.json, package.json, sonar-project.properties
Music year: 2008
- Clerk/nextjs dependabot
- bugsnag/js `8.2.0 -> 8.4.0`
- next: `15.3.0 -> 15.4.3`
- zod: `3.25.67 -> 3.25.76`
- webpack: `5.99.9 -> 5.100.2`
1. Go to https://oak-web-application-website-dajpkqnzq.vercel-preview.thenational.academy
2. Check general site integrity
3. Test the user lifecycle: login, logout, and new user registration.
4. Ensure Bugsnag is capturing errors properly
=> chore: July Dependagames

infrastructure/project/builds.tf, infrastructure/project/locals.tf, infrastructure/project/variables.tf
- migrate owa-staging to vvercel
- add missing custom env vars
[ENG-1284](https://www.notion.so/oaknationalacademy/Fix-Owa-staging-in-vercel-23f26cc4e1b180bbad7dd4f460ec62e0)
- Check that owa-staging.thenational.academy serves content from vercel
=> [ENG-1284] Migrate owa-staging to vercel
