src/browser-lib/fixtures/footerSections.ts, src/components/Pagination/Pagination.test.tsx
Adding status link and use first party domain for careers to direct to jobs page.
- Added Status to bottom of Oak section in footer that links to https://status.thenational.academy
- Edited Careers link to direct to https://jobs.thenational.academy instead of direct link
1. Go to homepage
2. Scroll to footer
3. You should see Status at the bottom of the Oak section (middle column on desktop)
4. Click link and it should take you to https://status.thenational.academy
5. You should see Careers third in the list of the Oak section (middle column on desktop)
6. Click link and it should take you to https://jobs.thenational.academy and redirect to BeApplied
=> chore(footer): add Status link to Oak footer and tidy up links

src/components/QuizContainer/QuestionListItem/QuestionListItem.test.tsx, src/components/QuizContainer/QuestionListItem/QuestionListItem.tsx, src/components/QuizContainer/QuestionListItem/quizUtils/index.test.tsx, src/components/QuizContainer/QuestionListItem/quizUtils/index.tsx
- removes **text** or *text* from title
- adds tests
Fixes #1581 
beta/teachers/programmes/science-secondary-ks3/units/cells-u2b1h4c/lessons/organisation-mbx95u
Starter q 4
1. Go to {cloud link}
{screenshots}
{screenshots}
=> Fix/i don't want to see markdown notation in quizzes#1581

src/node-lib/curriculum-api/generated/sdk.ts, src/node-lib/curriculum-api/queries/lessonOverview.gql
-remove empty strings from answers array
Fixes #1617 
1. Go to [Starter quiz question 3](https://deploy-preview-1609--oak-web-application.netlify.thenational.academy/beta/teachers/programmes/chemistry-secondary-ks4/units/atomic-structure-and-the-periodic-table-u68nqqc/lessons/electronic-structure-and-the-periodic-table-in1zfj)
2. Click on starter quiz
3. You should see question 3 doesnt have a comma after last answer
{screenshots}
=> fix(questions): remove empty answer strings from question answers

src/components/Posts/PostPortableText/PostCta.tsx, src/components/Posts/PostPortableText/PostForm.tsx, src/components/Posts/PostPortableText/PostPortableText.test.tsx, src/components/Posts/PostPortableText/PostPortableText.tsx, src/components/Posts/PostPortableText/PostQuote.tsx, src/components/pages/LandingPages/LandingPageTextAndMedia.tsx, src/node-lib/sanity-graphql/generated/sdk.ts
Some of the smaller sanity tweaks that don't need much consideration bundled together:
- Add the ability to render a newsletter form from within a blog post
- Fix alignment of quotes on blog posts
- Add missing spacing above CTAs on landing pages
- Add missing CTA to landing page Text & Media blocks
- Update the sanity graphql SDK
A newsletter form in a blog post
Before/after the CTA
Centered quote attribution now left aligned like the rest of the content
Text & media CTA now showing
=> fix: cms content snags

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql
connect lesson listing page to all available units with lessons
Fixes #
1. Go to owa 
2. Click on every unit
3. You should see a lesson listing page
{screenshots}
{screenshots}
=> LESQ-61 fix(lesson-listing): connect lesson listing to mv to expose all units

.github/dependabot.yml
- update dependabot config so that we don't get package-lock version updates without updating the package.json version
1. From now on, we should only get PRs from dependabot which update both package.json and package-lock.json
=> chore(dependabot): always increase version requirement to match new version

README.md
Some omissions in the Getting started section of the readme
- missing ‘npm install’
- potentially missing a requirement to run ‘npm run dev’ x 2 (first time is to auto-generate .env.development.local) ???
- potentially requirement to create .env.development.local is unecessary - if so remove
Fixes #
- information on how to run `npm install` to the getting started section.
- If needed - instructions on running 'npm run dev' twice to generate the .env.development.local file.
- If correct - remove redundant instruction to create the local .env.development file
n/a
{screenshots}
{screenshots}
=> fix: omissions and errors in README

src/browser-lib/getBrowserConfig.test.ts, src/browser-lib/getBrowserConfig.ts, src/node-lib/getServerConfig.test.ts, src/node-lib/getServerConfig.ts
We discovered that setting a branch value for an env in Netlify will set _an_ env value for all environments (prod, dev, etc), if you don't specify a value it will set that value to empty string `""`.
This change to the config value management is so that if an env has `required: true` then setting the value to an empty string will cause it to fall back to the default value.
=> [ENG-308] Feat/tighten server config

src/common-lib/cms-types/cta.ts, src/components/PortableText/PortableText.test.tsx, src/components/PortableText/PortableText.tsx, src/components/pages/LandingPages/SignUpForm.tsx, src/utils/portableText/resolveInternalHref.ts
Allow creating links to anchors and their associated targets from within the CMS.
Previously editors could create links to a predefined anchor (`#form-block`, for the landing page forms). This loosens that to any slug-like string, but with the caveat that there's no strong validation that the anchors exist on the page. This does not include the ability to link across pages to anchors, unless the whole URL is entered (instead of an `internal` `linkType`)
Twin PR from CMS repo: https://github.com/oaknational/CMS/pull/95
Fixes ENG-137
1. Go to our [testing blog post](https://deploy-preview-1726--oak-web-application.netlify.thenational.academy/api/preview/blog/some-blog-post?secret=wsJ3DpANkjZQk9z)
2. Click on the link with the text "A link to an anchor within this page"
3. You should be …
=> [ENG-137] feat: allow creating and linking to anchors within a CMS controlled page

src/components/AnchorTarget/AnchorTarget.tsx, src/components/Button/ButtonAsLink.stories.tsx, src/components/Button/ButtonAsLink.tsx, src/components/Button/ButtonInner.tsx, src/components/Button/IconButton.tsx, src/components/Button/IconButtonInner.tsx, src/components/Button/button.styles.ts, src/components/Button/common.ts, src/components/ButtonLinkNav/ButtonLinkNav.tsx, src/components/Icon/Icon.tsx, src/components/Icon/index.tsx, src/components/LessonItemContainer/LessonItemContainer.stories.tsx, src/components/LessonItemContainer/LessonItemContainer.test.tsx, src/components/LessonItemContainer/LessonItemContainer.tsx, src/components/MenuLinks/useIsCurrent.ts, src/components/pages/TeachersLessonOverview/OverviewPresentation.tsx, src/components/pages/TeachersLessonOverview/OverviewVideo.tsx, src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx
Fixes #
1. Go to https://deploy-preview-1783--oak-web-application.netlify.thenational.academy/beta/teachers/programmes/science-secondary-ks3/units/cells-u2b1h4c/lessons/microscopes-lcj273#video
2. Click on left hand nav links
3. You should see the navigation happen
{screenshots}
{screenshots}
=> Feat/lesq 128/lesson navbar

src/components/Button/ButtonInner.tsx
- Updated max height of subject icon in ButtonInner component, which was instead sizing by height / width
The curriculum phase selector had oversized and misaligned subject icons 
1. Go to [https://deploy-preview-1787--oak-web-application.netlify.thenational.academy/beta/teachers/curriculum]
2. Open the subject phase selector
3. You should see all correctly aligned subject icons in the buttons
=> fix(curric): updated max height for button subject svg

package-lock.json, package.json
Override the tough-cookie version temporarily to force a security fix, we should remove once a version of jest-environment-jsdom exists that has a tough-cookie dep that exceeds 4.1.3
=> fix(sec): update tough-cookie dep

src/components/Button/ButtonAsLink.test.tsx, src/components/Button/ButtonAsLink.tsx, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts
**Job Story:**
When *using buttonAsLink*, I want the title to render without risk of “undefined” being added as a suffix
**Detail:**
I think the logic is *supposed* to be as follows (but sounds like the logic might not be reflected properly in the code).
- `defaultTitle` is the string passed to html title attr if `title` prop not passed
- it takes value `ariaLabel` if that prop is passed (if there's a need to pass a different `ariaLabel` than the visible label)
- otherwise it should take the visible `label` prop, and add a suffix of `labelSuffixA11y` if that is passed
Essentially, the advice of a11y experts is that ideally the screen reader label should be same as visible -- but in cases where there are visual cues which would add context to a sighted user, then it's best to add a suffix …
=> Fix/lesq 203/default title logic

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql
remove all content-guidance values from every page page with content guidance
Fixes #
1. Go to beta/teachers-2023/programmes/science-primary-ks1/units/growing-plants/lessons/lesson-3-in-growing-plants
{screenshots}
{screenshots}
=> fix(contentguidance): remove all content guidance values regression

src/common-lib/urls/urls.ts
- use generic type for `OrString`
- use `Record<never, never>` instead of `{}` to appease sonar
- sonar should be happy with it
=> chore: type OrString generic, use Record<never,never> to appease sonar

src/errors/OakError.ts
- one of the main causes of url errors is from params (e.g. slugs coming through as empty strings)
- this PR updates the messaging for the resolveUrl function, so that it's clearer what the underlying cause could be
=> chore: url error logging

src/pages/beta/[viewType]/key-stages/[keyStageSlug]/subjects/index.tsx
- hides subject cards if no content is found
1. Go to https://deploy-preview-1826--oak-web-application.netlify.thenational.academy
=> fix(subject listing): don't show subject card unless there is content

src/common-lib/cms-types/teamMember.ts, src/components/BioModal/BioModal.tsx
- Allow nullish values for the leadership page bios to handle some data problems coming from the CMS
- Wrap the rendering of them in a conditional
Fixes #
-  The deploy should work
- https://deploy-preview-1831--oak-web-application.netlify.thenational.academy/about-us/leadership should only show bios that exist in the CMS
=> fix: handle missing bios in leadership page

src/common-lib/error-reporter/errorReporter.ts
- fix to the error reporter service so that it reports `OakError({ meta: {...fields} })`
1. New instances of [this error](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/64a69d34152a2500081867d0?event_id=64eeef6900beb90d044a0000&i=sk&m=ef) should have extra context
=> fix(error reporter): report meta field from OakError

.github/workflows/create_semantic_release.yml
Otherwise we risk getting into an infinite loop where the release creation process causes a change on `main` that triggers the release creation process.
=> chore(build): don't trigger releases on sonar config changing

src/pages/beta/[viewType]/programmes/[programmeSlug]/units.tsx
- [LESQ-89](https://www.notion.so/oaknationalacademy/Change-learning-themes-to-threads-on-unit-listing-page-834547d634d34270889ee9a9fce3a734?pvs=4) 
- change `Learning themes` to `Threads` in the units component
- there are a few variables using the `learningThemes` naming but I've left these as they are 
1. Go to https://deploy-preview-1892--oak-web-application.netlify.thenational.academy
2. Navigate to a unit page (eg KS3 Music)
3. You should see `Threads` in the sidebar instead of `Learning themes`
=> fix: change learning themes to threads [LESQ-289]

src/common-lib/error-reporter/errorReporter.ts
- ignore [hubspot `null is not an object (evaluating 'e.portalId')` error](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/64ff0304fee41f000706a6b9?filters[error.status]=open&filters[event.since]=30d)
=> chore(husbpot error): ignore hubspot error message

src/common-lib/error-reporter/errorReporter.test.ts, src/common-lib/error-reporter/errorReporter.ts
- ignore errors whose stacktrace contains files matching `//js.hubspot.com` (they aren't impacting users, there's nothing to be done about them, and they are affecting our stability score on bugsnag)
=> chore(error reporter): ignore hubspot errors by stacktrace file

.lintstagedrc.js, src/__tests__/pages/[viewType]/index.test.tsx, src/pages/[viewType]/index.tsx
hide teacher home page for all urls other then teachers
Fixes #
1. Go to https://deploy-preview-1911--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> fix(teachers homepage): hide teachers home page

src/components/Posts/PostHeader/PostHeader.tsx, src/components/Posts/PostListing.tsx, src/components/Posts/PostSingleLayout.tsx, src/pages/blog/[blogSlug].tsx, src/pages/webinars/[webinarSlug].tsx
Ticket: [Move blog breadcrumb out of nav bar](https://www.notion.so/oaknationalacademy/Move-blog-breadcrumb-out-of-nav-bar-c4452ab6611c4093bb77bcabe76cc63b?pvs=4)  
Changes:
- Removed breadcrumbs from nav bar on blog/webinar listing and post pages
- Added breadcrumb into these pages directly above content
- Mobile view should be unchanged 
1. Go to https://deploy-preview-1912--oak-web-application.netlify.thenational.academy/blog
2. See the breadcrumbs below the nav
3. Click on a blog post
4. You should see the breadcrumbs below the nav bar
=> Feat/lesq 305/blog breadcrumbs relocation [LESQ-305]

src/components/pages/CurriculumInfo/tabs/UnitsTab/UnitsTab.tsx
- Update spacing of child subjects, domain and tier filters in sequence visualiser / unit grid
1. Go to [teachers/curriculum/science-secondary/units](https://deploy-preview-1916--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary/units)
2. Scroll down to Year 10 unit section
3. You should see correct spacing for child subject and tier filter buttons
4. You should see correct sizing for tier filter buttons
5. Go to [teachers/curriculum/english-primary/units](https://deploy-preview-1916--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-primary/units)
6. You should correct spacing for domain buttons
=> fix(curric): update filter spacing

src/components/pages/CurriculumInfo/CurriculumHeader/CurriculumHeader.tsx, src/components/pages/CurriculumInfo/tabs/OverviewTab/OverviewTab.tsx
- Updated the title of curriculum intent to curriculum explainer
- Updated font sizes for all headings across overview tab and curriculum header
1. Go to https://deploy-preview-1914--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Go to any subject/phase combination
3. You should see 'Curriculum explainer' instead of 'Curriculum intent'
=> [CUR-261] Updated 'intent' to 'explainer' on overview page

src/components/UnitAndLessonLists/UnitList/UnitListItem/UnitListItem.test.tsx, src/components/UnitAndLessonLists/UnitList/UnitListItem/UnitListLessonCount.tsx
- update `UnitListLessonCount` to display "lesson" when `lessonCount` is 1
1. Go to https://deploy-preview-1927--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation/units
2. You should see "1 lesson" for number 6 and plural "lessons" for the others
=> Fix/lesq 319/lessons plurality [LESQ-319]

src/pages/teachers/key-stages/[keyStageSlug]/subjects/index.tsx
- Adds a sort to subjects in `getStaticProps`, based on slug
Fixes #
- subjects with only new content being shown after old content regardless of alphabet
1. Go to https://deploy-preview-1923--oak-web-application.netlify.thenational.academy/teachers/key-stages/ks4/subjects
2. You should see alphabetically ordered subjects
=> fix: sort subjects by slug on subject page [LESQ-285]

src/components/HeaderListing/HeaderListing.tsx, src/pages/teachers/key-stages/[keyStageSlug]/subjects/[subjectSlug]/programmes.tsx, src/pages/teachers/programmes/[programmeSlug]/units.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx
remove curriculum map link from new content pages
Fixes #
1. Go to https://deploy-preview-1930--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> LESQ-118 fix(headerListing): remove curriculum map link from new content

src/components/pages/LandingPages/CurriculumLandingHero.tsx
- Minor copy update on /teachers/curriculum
1. Go to https://owa.thenational.academy/teachers/curriculum
2. You should see "Oak's curricula cover" in the hero
=> chore(copy): update curricula

src/components/pages/CurriculumInfo/tabs/UnitsTab/UnitsTab.tsx
- Help centre banner was accidentally written over by unit modal work on the curriculum units page
1. Go to https://deploy-preview-1962--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> feat: added help centre banner to new units page

src/pages/api/preview/[[...path]].ts
We're getting hundreds of invalid auth request a day, possibly Detectify, hence extra data to help with analysis.
=> [ENG-471] more data in auth errors for CMS preview API calls

src/node-lib/curriculum-api/fixtures/earlyReleaseExemplarUnits.fixture.ts, src/pages/teachers/early-release-units.tsx
- Updates the lesson count for music unit in the exemplar units fixture
- Removes capitalisation of why in the geography unit "South America: why does the Amazon matter?"
1. Go to https://deploy-preview-1993--oak-web-application.netlify.thenational.academy/teachers/early-release-units
2. Scroll down to secondary and the music unit 'Keyboard fundamentals'
3. You should see the lesson count as 4, and clicking into the unit also shows 4 lessons
=> Feat: update number of lessons for music unit [LESQ-376]

src/common-lib/error-reporter/errorReporter.test.ts, src/common-lib/error-reporter/errorReporter.ts
- ignore errors on scripts from all subdomains of hubspot script domains
1. Run tests
2. When deployed, should no longer get errors such as https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/642d66d7a5d87200087e3138?filters%5Berror.status%5D=open&filters%5Bevent.since%5D=30d&filters%5Bevent.unhandled%5D=true
=> fix(error-reporter): hubspot subdomain wildcards

src/components/UnitAndLessonLists/UnitList/UnitListItem/UnitListItem.tsx
- Changes the background colour of expired unit list items
1. Go to https://deploy-preview-2015--oak-web-application.netlify.thenational.academy/teachers/programmes/art-secondary-ks3-l/units
2. You should see the expired units have a grey background
=> fix: change oakGreen to oakGrey2

src/node-lib/curriculum-api/fixtures/earlyReleaseExemplarUnits.fixture.ts
-Change year 1 to year 2 in primary science unit 'Growing Plants'
1. Go to https://deploy-preview-2016--oak-web-application.netlify.thenational.academy/teachers/early-release-units
=> fix: update year for primary science exemplar unit [LESQ-399]

src/components/Lesson/LessonOverview/LessonOverview.page.tsx, src/components/QuizContainerNew/QuestionsListNew/QuestionsList.tsx
- Moves mathjax provider to lesson level
- Mathjax should still render quizes
- No errors in console
Fixes #
1. Go to https://deploy-preview-2020--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-higher/units/surds/lessons/simplifying-surds#starter-quiz
Quizzes still show mathjax
{screenshots}
{screenshots}
=> refactor: move mathjax context to page level - LESQ-400

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumOverview/curriculumOverview.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql, src/node-lib/curriculum-api-2023/queries/programmeListing/progammeListing.gql, src/node-lib/curriculum-api-2023/queries/searchPage.gql, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.gql
pointing owa to the latest materialized views
this will resolve :
- https://www.notion.so/oaknationalacademy/Tier-on-the-lesson-overview-page-is-lower-case-79ea79f41b5444c2872e71a041c626b0?pvs=4
1. Go to https://deploy-preview-2026--oak-web-application.netlify.thenational.academy
ensure that the user journey is as expected
=> chore: point owa to latest mv versions

src/common-lib/urls/getDeploymentTestUrls.js, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumOverview/curriculumOverview.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOveview.gql, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql, src/node-lib/curriculum-api-2023/queries/programmeListing/progammeListing.gql, src/node-lib/curriculum-api-2023/queries/searchPage.gql, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.gql
Reinstated gql to point to mvs with version 3_0_0
1. Go to https://deploy-preview-2030--oak-web-application.netlify.thenational.academy
check user journey works
=> fix: reinstate pointing to new mv versions

src/components/VideoPlayer/VideoPlayer.tsx
- check the type of error being caught in the video `onError` callback and only report the error if it's not a network error
Fixes #
https://www.notion.so/oaknationalacademy/BugSnag-Report-VideoPlayer-network-error-e87be21fbb884fe6bf8373511a8fc17b?pvs=4 
This is a bit finicky
1. Go to https://deploy-preview-2038--oak-web-application.netlify.thenational.academy and navigate to any lesson with a video
2. Go to the network tab and look for the video requests, they'll start with something like `0.vtt?skid=default...`
3. Right click and select 'Block Request Domain'
4. Now reload the page and try to play the video, if the correct domain was blocked the video should not play, and there should _not_ be a bugnsag report in the console that looks like this: 
5. Don't forget to unblock the domain …
=> fix: only report video error if type is not networkError [LESQ-423]

src/__tests__/pages/lesson-planning.test.tsx, src/components/Sanity/TextBlock/TextBlockCardImageCta.tsx, src/pages/lesson-planning.tsx, src/pages/support-your-team.tsx
- use CTAs from the data that is passed in on the lesson planning page
- update the link for the search cta on support your team page to the new home
Fixes #
Unable to update links via Sanity CMS
1. Go to https://deploy-preview-2036--oak-web-application.netlify.thenational.academy/lesson-planning
2. Click on "Find teaching resources" or any CTA
3. You should see the link goes to the location defined in Sanity
=> Feat/lesq 417/integrate sanity fields [LESQ-417]

.github/workflows/code_checks.yml
Runs the code check tests when a PR merge queue is created or updated. The merge queue functionality needs to be turned on separately via the GH UI under branch rules (done).
=> [ENG-521] build(merges): workflow to enable merge queue checks

src/components/SubjectPhasePicker/SubjectPhasePicker.tsx
- Prevent automatic focus to buttons inside subject-phase picker when opening subject or phase controls
1. Go to https://deploy-preview-2063--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Click on `Subject`
3. You should see that the first subject button is *not* focused
=> [CUR-315] Fix subject-phase picker focus

src/components/DownloadComponents/ResourcePageLayout/ResourcePageLayout.tsx
- give the terms and conditions checkbox a neutral z index
1. Go to https://deploy-preview-2083--oak-web-application.netlify.thenational.academy/teachers/programmes/chemistry-secondary-ks4-l/units/atomic-structure-and-the-periodic-table-u68nqqc/lessons/atoms-elements-and-compounds-h3hasv/downloads?preselected=all
2. Type in the school picker
3. You should see the dropdown appears over the checkbox (and all other elements)
The school picker should be above all other checkboxes
=> Fix: checkbox z index [LESQ-449]

src/components/DownloadAndShareComponents/DetailsCompleted/DetailsCompleted.tsx, src/components/Lesson/LessonDownloads/LessonDownloads.page.tsx, src/styles/utils/typography.ts
Music year: 1960
- Adds overflow-wrap attribute to css
- Removes email from local storage if it is deleted on download click
Fixes #LESQ-431
1. Go to https://deploy-preview-2093--oak-web-application.netlify.thenational.academy/teachers/programmes/chemistry-secondary-ks4-l/units/atomic-structure-and-the-periodic-table-u68nqqc/lessons/atoms-elements-and-compounds-h3hasv/downloads?preselected=all (or any downloads page)
2. Add your email to local storage and download a resource
3. Return to a download page, edit and remove your email, then re-click download, email address will be removed from local storage
4. Return to a download page, should see not provided in the details completed box
5. If you click edit but don't delete your email, email continues to be stored, so when returning old …
=> chore/remove-email-local-storage LESQ-431

src/components/DownloadAndShareComponents/hooks/useResourceFormState.tsx
Music year: 2021
- Ensure downloads are not `forbidden` when adding to the list to be downloaded
Fixes #
https://app.bugsnag.com/oak-national-academy/oak-national-vercel-api/errors/6529a6980fe1a3000757d4d7?event_id=6554a2cf00ccc1377c1c0000&i=sk&m=ef
1. Go to https://deploy-preview-2095--oak-web-application.netlify.thenational.academy//teachers/programmes/spanish-secondary-ks3-l/units/year-7-unit-1-33b9/lessons/saying-what-someone-is-like-in-general-part-12-c5gkcr/downloads?preselected=all
2. Click on Download button
3. You should see the download succeed
=> fix: downloads failure [LESQ-465]

src/components/pages/CurriculumInfo/tabs/UnitsTab/UnitsTab.test.tsx, src/components/pages/CurriculumInfo/tabs/UnitsTab/UnitsTab.tsx
- Hide duplicate units without examboard
- Simplify unit visualiser tests
- Add comments and re-order units tab code for clarity
1. Go to https://deploy-preview-2101--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-secondary-aqa/units
2. Scroll to Year 10
3. You should see only one unit titled "Modern text: first study" with 2 unit options
=> fix: hide duplicate curriculum units

infrastructure/web/main.tf, infrastructure/web/monitoring.tf
Music year: 1951
- Increases the threshold at which OWA errors spotted in the logs will trigger a notification in Slack
1. Authenticate with correct Terraform workspace
2. Run `terraform plan` in the `infrastructure/web` directory
3. You should see a proposal to update the warn threshold for the existing "OWA log errors" Slack notification
=> chore: increase warning threshold for OWA errors

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.test.tsx, src/components/DownloadAndShareComponents/CopyrightNotice/CopyrightNotice.test.tsx, src/components/DownloadAndShareComponents/CopyrightNotice/CopyrightNotice.tsx, src/components/LessonDetails/LessonDetails.test.tsx
Music year: 1985
-adds missing 'Limited' to licence on new lessons
Fixes #
(https://deploy-preview-2106--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-higher-ocr/units/measuring-waves/lessons/transverse-waves/downloads?preselected=slide+deck)
You should see : This content is © Oak National Academy **Limited**......
{screenshots}
{screenshots}
=> chore: copy change for licence LESQ-474

package-lock.json, src/components/SiteFooter/SiteFooter.tsx
Music year: 1971
- Change copy on site footer
Fixes #LESQ-472
1. Go to https://deploy-preview-2122--oak-web-application.netlify.thenational.academy
2. Scroll to bottom to see footer
=> chore: update site footer copy LESQ-472

src/components/Checkbox/Checkbox.tsx
Music year: 2013
- Removes htmlFor attribute from checkboxes to fix accessibility bugs
https://www.geeksforgeeks.org/html-label-tag/
Fixes #LESQ-505
1. Go to https://deploy-preview-2128--oak-web-application.netlify.thenational.academy
=> chore: removes htmlFor as checkbox is a child component

src/context/Search/useSearch.ts
Music year: 1962
- removes dependancy on 2023 search API feature flag for perfoming a search, as this flag requires requesting to posthog which is behind the user consent agreement
- there is now a delay when performing a search using the feature flag, initially only legacy api results show and then it should populate with the new search results
- it is now not possible to use the new search api with the feature flag if you have not consented to tracking cookies
Fixes #LESQ-494
1. Go to https://deploy-preview-2129--oak-web-application.netlify.thenational.academy
2. Don't accept cookies
3. Perform a search and you should get results
=> fix: decouple search and feature flag [LESQ-494]

src/pages/develop-your-curriculum.tsx, src/pages/teachers/curriculum/index.tsx
Music year: 1993
- Adds alt text to hexagon image on curriculum and develop your curriculum pages
Fixes #LESQ-166
1. Go to https://deploy-preview-2133--oak-web-application.netlify.thenational.academy
=> chore: adds alt text to hexagon image LESQ-166

src/components/HomePageTabs/TeachersTab/TeachersTab.tsx
Music year: 1975
- Changes width of search in put bar on mobile
Fixes #LESQ-493
1. Go to https://deploy-preview-2132--oak-web-application.netlify.thenational.academy
2. Look at search bar on mobile phone view
=> chore: expands width on mobiles LESQ-493

src/__tests__/pages/contact-us.test.tsx, src/components/Forms/NewsletterForm/NewsletterForm.test.tsx, src/components/Forms/NewsletterForm/NewsletterForm.tsx, src/components/Posts/PostPortableText/PostPortableText.test.tsx, src/components/Posts/WebinarRegistration/WebinarRegistration.test.tsx
Music year: 1992
[Ticket](https://www.notion.so/oaknationalacademy/Buttons-and-links-should-inform-a-user-what-they-are-7c4d319f0c83439a916a26b311fd451e?pvs=4)
- Update the copy on the newsletter 'sign up' button to 'Sign up for the newsletter
- The other two changes in the ticket are controlled by Sanity and have been updated there:
- "Get started" -> "View curriculum"
- "Sign up" -> "Become a subject expert" 
Fixes #
1. Go to https://deploy-preview-2137--oak-web-application.netlify.thenational.academy
2. Check the newsletter form at the bottom of the page
=> [LESQ-163] Fix/lesq 163/a11y labels

src/components/Forms/NewsletterForm/NewsletterForm.test.tsx, src/components/Forms/NewsletterForm/NewsletterForm.tsx
- Changes error message and test files
Fixes #LESQ-157
1. Go to https://deploy-preview-2140--oak-web-application.netlify.thenational.academy
2. Select newsletter form inputs and then unselect error messages will appear
=> Fix/newsletter error message LESQ-157

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql
Some of the lessons that were released yesterday had no data (intentionally) in their exit quizzes. Unfortunately, the PDFs are generated regardless of whether there is data in the quizzes. This meant the lesson page in OWA knew there wasn’t a quiz because there was no quiz data, but the downloads page, that only checks to see if a PDF exists, does see a PDF so offers it for download. 
Connects up new downloads mv to fix the issue
Fixes #
1. Go to https://deploy-preview-2150--oak-web-application.netlify.thenational.academy/teachers/programmes/english-primary-ks1/units/writing-lower-case-letters-in-print/lessons/introduction-to-skills-and-patterns
There should be no exit quiz in this download
=> fix: non existence exit quizes

src/components/SearchResultsItem/SearchResultsItem.tsx
Music year: 1985
- Fixes bolding on search descriptions 
Fixes #
1. Go to https://deploy-preview-2156--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore: fix highlighting of key words

.github/workflows/post_deployment_actions.yml
The warm caches script seems to be flaky, and it's not clear it's providing benefit for the Percy testing at the moment. Temporarily disabling it while validating.
=> chore(CI): temporarily disable to warm caches script in CI

src/components/TeacherComponents/LessonOverviewCommonMisconceptions/LessonOverviewCommonMisconceptions.test.tsx, src/components/TeacherComponents/LessonOverviewCommonMisconceptions/LessonOverviewCommonMisconceptions.tsx, src/components/TeacherComponents/LessonOverviewDetails/LessonOverviewDetails.test.tsx, src/components/TeacherComponents/LessonOverviewDetails/LessonOverviewDetails.tsx, src/components/TeacherViews/LessonOverview.view.tsx
- Mathsjax in lesson details
- fixes copy error 'misconceptions'
Fixes #
1. Go to https://deploy-preview-2208--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation/units/surds/lessons/accuracy-of-final-answers
Mathjax should render correctly in quizes,
No Mathjax in lesson details yet
Misconceptions changed to misconception
{screenshots}
{screenshots}
=> Feat/mathjax in lesson information LESQ-525 LESQ-507

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql
point src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql and src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql to mv_downloads_3_0_2 which corrects and issue with duplicate lessons
Head to any lesson on the teacher journey and download some items
=> fix: point dowloads gql to correct mv

src/components/AppComponents/LayoutSiteFooter/LayoutSiteFooter.tsx, src/components/SharedComponents/Button/Button.tsx, src/components/SharedComponents/Button/ButtonInner.tsx
Music year: 2014
- Adds labelColor prop to button to change the colour of button labels when passed in 
Fixes #LESQ-495
1. Go to https://deploy-preview-2209--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> Footer button colour LESQ-495

src/components/PupilComponents/QuizQuestionStem/QuizQuestionStem.tsx
Quiz images (especially PNGs and SVGs) may have transparency. The lemon and mint page backgrounds of the quiz pages will show through and could cause contrast issues with the content of the image. To avoid this we can set a white background on all quiz images which will show through the transparency to provide a default backdrop.
https://deploy-preview-2225--oak-web-application.netlify.thenational.academy/pupils/programmes/combined-science-secondary-ks4-foundation-aqa/units/measuring-waves/lessons/representing-longitudinal-waves
exit quiz
question 4/6
- [ x]  Quiz images with transparency are filled with white
=> fix: white bg for quiz stem images to avoid contrast issues

src/components/GenericPagesComponents/TeachersTabResourceSelectorCard/TeachersTabResourceSelectorCard.tsx
Music year: 2004
- Fix icons so they are all white
Fixes #
1. Go to https://deploy-preview-2238--oak-web-application.netlify.thenational.academy
=> fix: icon color to white on home page - LESQ-624

src/__tests__/pages/pupils/index.test.tsx, src/components/CurriculumComponents/CurriculumDownloads/CurriculumDownloads.test.tsx, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.test.tsx, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.tsx, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.test.tsx, src/components/PupilComponents/QuizEngineProvider/QuizEngineProvider.tsx, src/components/PupilComponents/QuizMCQMultiAnswer/QuizMCQMultiAnswer.stories.tsx, src/components/PupilComponents/QuizRenderer/QuizRenderer.test.tsx, src/components/PupilViews/PupilIntro/PupilIntro.view.test.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.test.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx, src/components/PupilViews/PupilVideo/PupilVideo.test.tsx, src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/index.tsx
Music year: [1997](https://www.youtube.com/watch?v=2H5uWRjFsGc)
Supports lessons with one or more missing sections (starter quiz, exit quiz and video).
🤦‍♂️ Includes a fix for a mistake I made when building the overview page — somehow I managed to get the count of exit and starter quiz questions the wrong way round.
1. Go to https://deploy-preview-2234--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-ks1/units/writing-lower-case-letters-in-print/lessons/formation-of-v-w-x-and-z
2. You should see a lesson with an intro, starter quiz and video
3. You should be able to take the lesson and complete the 3 sections
4. After completing the 3 sections you should see the lesson review.
NB: There aren't any lessons available currently with a missing starter-quiz or …
=> PUPIL-317: Support lessons with missing sections

src/context/Search/search.schema.ts
- Typo in the search highlight schema was removing the lesson description highlight field.
Fixes #
1. Go to https://deploy-preview-2240--oak-web-application.netlify.thenational.academy
Search for object - you should the it highlighted in the search results
There are still some issues - `objects` does not match, but `object` matches 'object' and 'objects', we should look into tweaking the analyser for highlighting when we work more on search.
=> fix: schema for search highlight - LESQ-528

src/components/TeacherViews/LessonOverview.view.tsx
Music year: 1950
- prevent lesson overview rendering empty keywords section
- 
Everything should look the same, only EYFS is affected currently on the migration environment
1. Go to https://deploy-preview-2241--oak-web-application.netlify.thenational.academy
{screenshots}
=> fix: convert empty keywords array to undefined [LESQ-626]

src/__tests__/pages/pupils/index.test.tsx, src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/index.tsx
Music year: [2022](https://www.youtube.com/watch?v=pzVYSfzNQ5Y)
Fixes the lesson page blowing up when a the download existence check throws.
If the download existence check fails, we should not block the page from rendering. There appear to be two ways the `getDownloadResourcesExistence` will report a missing resource. Either by returning an object in the form `{ resources: ["worksheet-pdf", { exists: false }] }` or by throwing. Catching and reporting the error matches the behaviour of the teachers downloads page and allows the lesson page to render
1. Go to the migrated legacy lesson https://deploy-preview-2253--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-ks3/units/the-oral-tradition-7424/lessons/the-origins-of-storytelling-cmrk0r — this lesson …
=> fix: lesson page blowing up when a download existence check fails

package-lock.json, src/components/TeacherViews/LessonOverview/LessonOverview.test.tsx, src/components/TeacherViews/LessonOverview/LessonOverview.view.tsx, src/components/TeacherViews/SpecialistLesson/SpecialistLesson.view.tsx, src/node-lib/curriculum-api-2023/shared.schema.ts, src/pages/teachers/lessons/[lessonSlug].tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx
Music year: 1976
- remove the pupil lesson outcome from the lesson header when it is included in key learning points
- only applies to EYFS currently, but will apply to legacy when migrated
1. Go to https://deploy-preview-2247--oak-web-application.netlify.thenational.academy/teachers/programmes/citizenship-secondary-ks4-l/units/how-well-does-the-media-hold-those-in-power-to-account-63c4/lessons/what-is-the-role-of-the-media-in-a-democracy-cmw32c
3. You should see no pupil lesosn outcome in the header (same as prod)
4. Go to https://deploy-preview-2247--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-higher-aqa/units/measuring-waves/lessons/transverse-waves
5. You should see the pupil lesson outcome in the header (same as prod)
How it used …
=> Feat/lesq 637/legacy remove duplicate description [LESQ-637]

src/components/TeacherComponents/LessonShareCardGroup/LessonShareCardGroup.test.tsx, src/components/TeacherComponents/LessonShareCardGroup/LessonShareCardGroup.tsx, src/node-lib/curriculum-api-2023/queries/lessonShare/lessonShare.schema.ts
Music year: 2014
- make shareable resource metadata nullable as it only exists when the resource exists 
Fixes # 
share page not loading for EYFS lessons
can't be tested until it is deployed to the migration instance
=> Fix/lesq 628/lesson share [LESQ-628]

package-lock.json, package.json, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.test.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.test.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx, src/components/PupilViews/PupilReview/PupilReview.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx
Music year: [2006](https://www.youtube.com/watch?v=x1peC9_QOiE)
A bunch of copy changes and tweaks to match the [latest designs](https://www.figma.com/file/G7z5ufo2T0CHk14CkadeuB/Pupils-high-fidelity-designs?type=design&node-id=2980-64457&mode=design)
1. The "Lesson review" button label will appear at the end of the exit quiz even if the lesson is incomplete (I.e. the lesson has been completed out of order). I feel like this ok, but I can spend a little more time covering this case if it would be confusing. In the case that the lesson is completed out of order this label should be applied to any section that happens to be the last one completed.
2. I missed changing the "Watch video"  -> "Lesson video" on the lesson review page. This will trickle through in the next publish of the …
=> PUPIL-351: Pupil lesson copy changes

src/components/AppComponents/App/AppHooks.tsx
It is not needed for pupils, and it is appearing on top of the submit button in quizzes. We'll use other methods to gather feedback from pupils
Music year: [1969](https://www.youtube.com/watch?v=zUQiUFZ5RDw)
1. Go to https://deploy-preview-2259--oak-web-application.netlify.thenational.academy/pupils/programmes/science-secondary-ks3/units/moving-by-force/lessons/reading-distance-time-graphs
3. You **should not** see the Gleap
4. Go to https://deploy-preview-2259--oak-web-application.netlify.thenational.academy/
5. You **should** see the Gleap
How it used to look 
=> PUPIL-338: disable Gleap for pupils

src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx
Music year: [1957](https://www.youtube.com/watch?v=tE46zm4yjhA)
Disables the nav items and "Let's get ready" button (using their existing disabled states) on the lesson overview until the page has hydrated. This is a temporary measure until they are replaced with links. However until then the page will appear broken while the JS is loading. 
1. Visit https://deploy-preview-2260--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-ks4-aqa/units/modern-text-second-deep-dive-194/lessons/men-in-leave-taking#lesson-details on a slow or throttled connection (climb a remote hillside in North Wales, go to a music festival, or use the Network tab of DevTools).
2. Try to interact with the buttons on the overview screen while the page is still loading.
1. Deep linking …
=> PUPIL-412: Disable buttons on the lesson overview until page hydration

package-lock.json, package.json, src/components/PupilViews/PupilIntro/PupilIntro.view.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx, src/components/PupilViews/PupilReview/PupilReview.view.test.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx, src/components/PupilViews/PupilVideo/PupilVideo.view.tsx
Fixes the button in the lesson footer wrapping when the answer is long
1. Go to https://deploy-preview-2262--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-ks2/units/developing-reading-preferences-in-year-5/lessons/developing-reading-preferences-in-year-5-through-appreciation-of-characters
2. Click on "Starter lesson"
3. Take the quiz and answer question 5
4. Resize the window until the answer text wraps
5. The button should not wrap.
How it used to look
=> PUPIL-274: Fix footer button wrapping in lesson

src/components/PupilComponents/ViewAllLessonsButton/ViewAllLessonsButton.test.tsx, src/components/PupilComponents/ViewAllLessonsButton/ViewAllLessonsButton.tsx, src/components/PupilViews/PupilExperience/PupilExperience.view.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/PupilViews/PupilReview/PupilReview.view.tsx
Music year: [2000](https://www.youtube.com/watch?v=9Ht5RZpzPqw)
* Applies the same grid as the lesson overview so that the button and content align correctly at each breakpoint
* Adds the missing link back to "View all lessons" on lesson review
* This should behave the same as the link on the overview page?
1. Go to https://deploy-preview-2263--oak-web-application.netlify.thenational.academy/pupils/programmes/science-secondary-ks3/units/forces/lessons/what-forces-do
2. Take the lesson and stop at the lesson review
3. Observe the position and spacing of the "View all lessons" button
4. Click "Lesson overview" button
5. Observe that the position of the "View all lessons" buttons match on both pages
https://github.com/oaknational/Oak-Web-Application/assets/122096/c78bbec7-e96b-4d93-b17a-81396 …
=> PUPIL-398: correct spacing around "View all lessons" button

package-lock.json, package.json
Music year: [1993](https://www.youtube.com/watch?v=7kmEEkECFQw)
Fixes loading placeholders not being displayed in OWA owing to it running an older version of Next
✋🏼 you might need to disable cache in dev tools if it is already primed 
1. Go to https://deploy-preview-2271--oak-web-application.netlify.thenational.academy/pupils/programmes/science-secondary-ks3/units/moving-by-force/lessons/reading-distance-time-graphs
2. Click on "Starter quiz"
3. You should see loading placeholders for each answer while the image loads
4. Go to https://deploy-preview-2271--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-ks2/units/developing-reading-preferences-in-year-5/lessons/developing-reading-preferences-in-year-5-through-appreciation-of-characters
5. Click on …
=> feat(PUPIL-413): bump oak-components@0.0.37 to apply Next13 image placeholders

.storybook/main.js, src/components/PupilComponents/QuizMCQMultiAnswer/QuizMCQMultiAnswer.stories.tsx, src/components/PupilComponents/QuizMCQSingleAnswer/QuizMCQSingleAnswer.stories.tsx, src/components/PupilComponents/QuizShortAnswer/QuizShortAnswer.stories.tsx
Because they are broken and will stay broken, the resolution is part of the new open source components library.
How to test: the Storybook deployment should no longer contain autodocs.
=> chore(Storybook): disable Storybook autodocs

src/components/TeacherComponents/LessonShareCardGroup/LessonShareCardGroup.test.tsx, src/components/TeacherComponents/LessonShareCardGroup/LessonShareCardGroup.tsx, src/components/TeacherComponents/LessonShareLinks/LessonShareLinks.test.tsx, src/components/TeacherComponents/LessonShareLinks/LessonShareLinks.tsx, src/components/TeacherComponents/LessonShareLinks/getHrefForSocialSharing.test.ts, src/components/TeacherComponents/LessonShareLinks/getSharingMetadata.test.ts, src/components/TeacherComponents/LessonShareLinks/getSharingMetadata.ts, src/components/TeacherComponents/ResourceCard/ResourceCard.test.tsx, src/components/TeacherComponents/ResourceCard/ResourceCard.tsx, src/components/TeacherViews/LessonShare/LessonShare.view.tsx
Music year: 1960
- updated resource card component to show checkbox coniditionally
- remove select all when sharing to new pupil experience is active
- update url for sharing to new pupil experience
currently only one unit is active on the new pupil experience
1. Go to https://deploy-preview-2283--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks3-l/units/shakespearean-comedy-the-tempest-88f0/lessons/context-of-the-tempest-cctp4c/share?preselected=all
3. You should see no 'select all' or checkboxes
4. clicking preview should take you to the new pupil experience
5. share links should all link to new pupil experience
6. every other legacy unit should share to classroom still
=> Feat/lesq 619/share to npe [LESQ-619]

src/components/TeacherViews/LessonShare/LessonShare.view.tsx, src/node-lib/curriculum-api-2023/fixtures/lessonDownloads.fixture.ts, src/node-lib/curriculum-api-2023/fixtures/lessonOverview.fixture.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloadsCanonical/lessonDownloadsCanonical.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.ts, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql, src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonShare/lessonShare.gql, src/node-lib/curriculum-api-2023/queries/lessonShare/lessonShare.schema.ts, src/node-lib/curriculum-api-2023/shared.schema.ts, src/node-lib/curriculum-api/fixtures/lessonDownloads.fixture.ts, src/node-lib/curriculum-api/fixtures/lessonShare.fixture.ts, src/node-lib/curriculum-api/index.ts
-Updates MV unitListing, lessonListing , lessonOverview, downloads and share
-Adds expired field to GQL
-Stops expired lessons from being rendered
Fixes #
1. Go to https://deploy-preview-2288--oak-web-application.netlify.thenational.academy
All should be the same, on migration oak expired eyfs lessons should be greyed out in lists and message on lesson overview / downloads / share stating there is no longer a lesson.
=> Feat/ expired fields in lesson journey new database - LESQ-662

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].test.tsx, src/components/TeacherViews/LessonDownloads.view.tsx, src/components/TeacherViews/LessonOverview/LessonOverview.view.tsx, src/components/TeacherViews/LessonShare/LessonShare.view.tsx, src/components/TeacherViews/SpecialistLessonDownloads/SpecialistLessonDownloads.fixture.ts, src/components/TeacherViews/SpecialistLessonDownloads/SpecialistLessonDownloads.stories.tsx, src/components/TeacherViews/SpecialistLessonDownloads/SpecialistLessonDownloads.view.tsx
Music year: 1990
- Disable buttons and hide content on the share and downloads pages that are expired. This pages are not linked to but could be found.
Fixes #
1. Go to https://deploy-preview-2290--oak-web-application.netlify.thenational.academy
Nothing here to see everything works the same. On migration should see images below for expired lessons
for expired eyfs: /teachers/programmes/understanding-the-world-foundation-early-years-foundation-stage/units/transport-0359/lessons/to-explain-features-of-different-modes-of-transport-chjk0c/downloads
=> Feat hide content on expired share and overview

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.gql
Music year: 1967
- Connects the MV's that use 
```
{
"copyright_info": "Attributions in slides where needed."
}
```
For both legacy and new content to determine if a lesson has downloads
More detail here - https://www.notion.so/oaknationalacademy/Spring-Sprint-1-fe3f5ac1bb0147668eb40dc32334d684?p=aa1063242dc847a2b0cb5eb96788b104&pm=s
Fixes #
1. Go to https://deploy-preview-2293--oak-web-application.netlify.thenational.academy
teachers/programmes/science-primary-ks2/units/simple-forces-including-magnets/lessons/different-magnets-and-their-parts
You should see downloads are available 
{screenshots}
{screenshots}
=> chore: update mv for downloads and overview - LESQ-674

src/pages/legal/[policyPageSlug].tsx
Internal links on policy pages weren't working, now they should.
To test, open the privacy policy page, and check that the first paragraph has a working, underlined link to the child-friendly version of the privacy policy.
=> [ENG-675] fix(policy pages): make internal links work

package-lock.json, src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.tsx, src/components/PupilComponents/pupilTestHelpers/createLessonEngineContext.ts, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.test.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx
Music year: 1951
overview next section label wasnt being driven by lesson state.lessonStarted
now using lesson sate to dictate label
Fixes #
1. Go to https://deploy-preview-2289--oak-web-application.netlify.thenational.academy/pupils/l/shakespearean-comedy-the-tempest-88f0/lessons/context-of-the-tempest-cctp4c
2. Click through lesson
3. You should see once intro is complete the label should say continue lesson untilo the lesson is finished
=> PUPIL-457 Fix/start lesson label bug

src/components/PupilViews/PupilExperience/PupilExperience.view.test.tsx, src/components/PupilViews/PupilExperience/PupilExperience.view.tsx, src/components/PupilViews/PupilExpired/PupilExpired.view.stories.tsx, src/components/PupilViews/PupilExpired/PupilExpired.view.tsx, src/node-lib/curriculum-api-2023/fixtures/pupilLessonOverview.fixture.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.gql, src/node-lib/curriculum-api-2023/queries/pupilLessonOverview/pupilLessonOverview.schema.ts, src/node-lib/curriculum-api-2023/queries/pupilLessonOverviewCanonical/pupilLessonOverviewCanonical.gql, src/node-lib/curriculum-api/fixtures/pupilLessonOverview.fixture.ts
As a rights holder of copyrighted content,
I want expired lessons not to be accessible in the pupil experience,
So that I do not have to take legal action against Oak National Academy
As a pupil who has somehow found their way to an expired lesson in the Pupil experience
I want to be shown a clear message when the lesson is no longer available
So that I receive better information than a generic error page
See here:
https://deploy-preview-2301--owa-storybook.netlify.thenational.academy/?path=/story/components-pupilviews-pupilexpired--default
- NB. we haven't published expired lessons yet so there's no way of checking via OWA in prod.
- Expose expired field in MV lesson overview
- OWA Redirect to a 'this content is no longer available page' when said field is shown
=> Feat/pupil 479/handle expired lessons

src/__tests__/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons.test.tsx, src/components/TeacherComponents/LessonList/LessonList.tsx, src/components/TeacherComponents/LessonListItem/LessonListItem.tsx, src/components/TeacherComponents/ListItemHeader/ListItemHeader.tsx, src/components/TeacherViews/SpecialistLessonListing/SpecialistLessonListing.fixture.ts, src/components/TeacherViews/SpecialistLessonListing/SpecialistLessonListing.view.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.gql, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.query.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.schema.ts, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx, src/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx
- add query for specialist lesson listing
- add specialist lesson listing page
- update schema and types
Once again this should 404 until published, so nothing to see here. 
1. Go to https://deploy-preview-2303--oak-web-application.netlify.thenational.academy/teachers/specialist/programmes/numeracy-building-understanding/units/number-c7b4/lessons
2. Observe the internal server error (404)
The 'curriculum download' buttons seems to _just work_, which is a nice surprise
=> Feat/lesq 559/specialist lesson listing [LESQ-559]

src/__tests__/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/share.test.tsx, src/node-lib/curriculum-api-2023/fixtures/specialistLessonShare.fixture.ts, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/lessonShare/lessonShare.schema.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonShare/specialistLessonShare.gql, src/node-lib/curriculum-api-2023/queries/specialistLessonShare/specialistLessonShare.query.test.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonShare/specialistLessonShare.query.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonShare/specialistLessonShare.schema.ts, src/node-lib/curriculum-api-2023/shared.schema.ts, src/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/share.tsx
Music year: 2007
- Adds specialist share page, query and schema
- Note: we are mising information in the MV required to give video duration, so have added a placeholder text 'mp4' and added an issue in the specialist issues tracker
- We also don't have information on quiz questions but I don't think specialist has any quizzes
1. Go to https://deploy-preview-2307--oak-web-application.netlify.thenational.academy/teachers/specialist/programmes/numeracy-building-understanding/units/number-c7b4/lessons/counting-individual-objects-one-to-one-correspondence-6nh32d/share
3. You should see internal server error (404)
4. the rest of the site should work the same :') 
=> Feat/lesq 668/specialist share page [LESQ-688]

src/components/TeacherViews/LessonShare/LessonShare.view.tsx
Music year: 2001
- Amends how links are generated to be by subject 
Fixes #LESQ-693
1. Go to https://deploy-preview-2304--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> LESQ-693 -  Refactor: share link to pupil experience by subject

src/node-lib/curriculum-api-2023/queries/specialistLessonOverview/specialistLessonOverview.schema.ts
Music year: 2011
- make developmentstage optional in the schema
Fixes #
Therapy lessons not loading
1. Go to https://deploy-preview-2319--oak-web-application.netlify.thenational.academy
2. should be the same
=> fix: specialist lesson schema [LESQ-704]

src/components/PupilViews/PupilExperience/PupilExperience.view.tsx
Music year: 1977
Moves the Confirmic widget above the footer nav in pupil lessons so that it no longer obscures and blocks interaction with the button beneath
1. Open an incognito browser window or clear your cookies + localStorage for `thenational.academy`
2. Go to https://deploy-preview-2311--oak-web-application.netlify.thenational.academy/pupils/lessons/prologue-grime-mix-ccuk0d
3. Observe the appearance of the Confirmic consent widget
4. You should be able to click on "Let's get ready"
5. The confirmic widget should work as before
6. The confirmic widget should not be affected in any other section of OWA
https://github.com/oaknational/Oak-Web-Application/assets/122096/1af63711-856c-4bca-8313-f4fe8f5898c2
=> PUPIL-478: Confirmic blocking the bottom nav in pupil lessons

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistUnitListing.gql, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistUnitListing.query.ts, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistUnitListing.schema.ts
Music year: 1963
- update unit listing query to remove expired
- add expired as lesson count = 0
1. Go to https://deploy-preview-2324--oak-web-application.netlify.thenational.academy
2. SHould be the same
=> fix: update unit listing query to remove expired [LESQ-714]

src/components/PupilComponents/pupilUtils/requestLessonResources.test.ts, src/components/PupilComponents/pupilUtils/requestLessonResources.ts
Music year: 1959
Legacy transcripts are stored as a big string which we have to split into sentences to properly format in the frontend.
1. Go to https://deploy-preview-2330--oak-web-application.netlify.thenational.academy/pupils/lessons/introduction-to-the-canterbury-tales-cmrk4d
2. Click on "Lesson video"
3. Click on "Show transcript"
4. You should see a transcript with line breaks.
Line breaking should now match the same lesson in the teacher's section https://www.thenational.academy/teachers/programmes/english-secondary-ks3-l/units/the-canterbury-tales-general-prologue-7d62/lessons/introduction-to-the-canterbury-tales-cmrk4d
Compared to the same lesson in the teacher section:
=> fix(PUPIL-524): split `transcriptSentences` into an array of transcript sentences

src/components/TeacherComponents/HeaderListing/HeaderListing.tsx, src/components/TeacherComponents/SpecialistProgrammeHeaderListing/SpecialistProgrammeHeaderListing.tsx
Music year: 2014
https://www.youtube.com/watch?v=ZbZSe6N_BXs
- Amends heading Icon sizes on `SpecialistProgrammeHeadingListing` and `HeaderListing` components
Fixes #LESQ-715
=> LESQ-715: Fix specialist heading icon sizes

src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.query.ts, src/node-lib/curriculum-api-2023/shared.schema.ts
Music year: 2017
- there was a schema validation error due to null values on some asset worksheet urls, so updated the schema
- this means we face the bug where the download button is available on individual resources but not on the downloads page, we have a ticket for that for next sprint
1. Go to https://deploy-preview-2333--oak-web-application.netlify.thenational.academy
2. should be the same
=> fix: 404 on some lesson listing pages [LESQ-709]

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/specialistUnitListing/specialistLessonCount.query.gql
- Remove contains_copyright_content: { _eq: false } from gql query
- https://www.notion.so/oaknationalacademy/I-want-correct-lesson-counts-on-unit-cards-for-specialist-content-2eb71e0ef8bc46f68975c8465d7b4752
Fixes #
1. Go to https://deploy-preview-2334--oak-web-application.netlify.thenational.academy
`Our world` has an incorrect count
{screenshots}
{screenshots}
=> fix: do not exclude copyright from counts - LESQ-719

src/components/PupilComponents/PupilLayout/PupilLayout.tsx, src/components/PupilViews/PupilExperience/PupilExperience.view.tsx
Add Seo to pupil pages
I have created a new PupilLayout component . Very similar to AppLayout but without Header and Footer.
Check SEO tags are correct in `<head>` for lesson (and canonical) lessons pages.
```html
<title>LESSON TITLE | Oak National Academy</title> 
```
```html
<meta name="robots" content="index,follow" />
```
```html
<meta name="description" content="LESSON OVERVIEW/SUMMARY HERE" />
```
```html
<meta property="og:title" content="LESSON TITLE HERE" />
<meta property="og:description" content="LESSON OVERVIEW/SUMMARY HERE" />
<meta property="og:url" content="NEW URL HERE" />
<meta property="og:image" content="https://www.thenational.academy/images/sharing/default-social-sharing-2022.png?2024" />
<meta property="og:image:alt" content="Oak National Academy" />
<meta …
```
=> Feat/pupil 560/seo meta data is correct

src/components/GenericPagesComponents/HomepageTabImageButton/HomePageTabImageButton.test.tsx, src/components/GenericPagesComponents/HomepageTabImageButton/HomePageTabImageButton.tsx
Music year: 1995
- adds `(New)` to aria label and title when the 'new' icon is visible
- adds test
1. Go to https://deploy-preview-2351--oak-web-application.netlify.thenational.academy
2. Hover over the 'AI Experiments' button
3. Should see the title tooltip reading 'AI Experiments (New)'
4. Check the `aria-label` of this button
5. Should be 'AI Experiments (New)'
{screenshots}
{screenshots}
=> fix(a11y): add 'new' to aria-label where appropriate

src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
Regression in the curriculum visualiser. We removed the new banner, but it has re-appeared 😕.  
This is the original ticket - https://www.notion.so/oaknationalacademy/Remove-New-tags-and-labels-from-curriculum-journey-584312705f2240498c84dbfd4bb4b928
Banner should be replaced with new copy and the heading structure should remain hierarchical
1. Go to https://deploy-preview-2352--oak-web-application.netlify.thenational.academy/teachers/curriculum/maths-secondary/units
<kbd><img width="1281" alt="image" src="https://github.com/oaknational/Oak-Web-Application/assets/587241/67ecd172-b9bf-4e50-b42d-41728346511e"></kbd>
<kbd><img width="1291" alt="image" src="https://github.com/oaknational/Oak-Web-Application/assets/587241/81c0228f-61b …
=> [CUR-451] Removing new banner and updating header hierarchy

src/__tests__/pages/teachers/curriculum/index.test.tsx, src/browser-lib/fixtures/footerSections.ts, src/common-lib/urls/getDeploymentTestUrls.js, src/pages/teachers/curriculum/index.tsx
Music year: 2011
- publish copyright page in sanity
- add link to footer
- once this is deployed we can ask Jim to remove redirect
There was also a bug with some blog post URLs being out of date so updated those as well
1. Go to https://deploy-preview-2360--oak-web-application.netlify.thenational.academy/legal/copyright-notice
3. You should see the page
4. go to https://deploy-preview-2360--oak-web-application.netlify.thenational.academy/teachers/curriculum
5. the links to blog posts should all work
=> feat: add copyright notice link to footer [LESQ-763]

src/node-lib/curriculum-api-2023/queries/specialistLessonDownload/specialistLessonDownload.query.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonListing/specialistLessonListing.query.ts, src/node-lib/curriculum-api-2023/queries/specialistLessonOverview/specialistLessonOverview.query.ts
Music year: 1984
- check agains the correct field for worksheet download on lesson overview and downloads page
Fixes #
speciallist worksheets can't be downloaded
1. Go to https://deploy-preview-2362--oak-web-application.netlify.thenational.academy/teachers/specialist/programmes/sensory-integration/units/oral-breathing-6e66/lessons/getting-ready-for-bed-chh38d#worksheet
2. Click on download worksheet
3. You should see to download page with worksheet downloadable
=> fix: specialist worksheet download [LESQ-739]

src/components/GenericPagesComponents/LandingPageTextAndMedia/LandingPageTextAndMedia.tsx
- Adds black font color
Fixes #
1. Go to https://deploy-preview-2387--oak-web-application.netlify.thenational.academy
https://deploy-preview-2387--oak-web-application.netlify.thenational.academy/lp/how-to-use-Oak-in-3-easy-steps
=> fix: landing page font color - LESQ-778

src/components/CurriculumComponents/OakComponentsKitchen/Autocomplete/index.tsx, src/components/SharedComponents/Input/Input.tsx
- No functional changes just removed `FC<InputProps>` from `<Input/>`'s type so I can remove `@ts-expect-error:`
Previous error is as follows
```
src/components/CurriculumComponents/OakComponentsKitchen/Autocomplete/index.tsx:67:9 - error TS2578: Unused '@ts-expect-error' directive.
67         // @ts-expect-error: unsure what type it's after here...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in src/components/CurriculumComponents/OakComponentsKitchen/Autocomplete/index.tsx:67
husky - pre-push hook exited with code 2 (error)
error: failed to push some refs to 'github.com:oaknational/Oak-Web-Application.git'
```
=> feat: fixed type issue with `./SharedComponents/Input`

src/components/TeacherComponents/SubjectProgrammeList/SubjectProgrammeList.test.tsx, src/components/TeacherComponents/SubjectProgrammeListItem/SubjectProgrammeListItem.tsx, src/components/TeacherComponents/SubjectProgrammeListing/SubjectProgrammeListing.test.tsx
Music year: 2004
- update subjectProgrammeListItem links to use `p` instead of `heading` for inner text
- update tests
1. Go to https://deploy-preview-2401--oak-web-application.netlify.thenational.academy/teachers/key-stages/ks4/subjects/chemistry/programmes
2. Inspect tags of the programme links
3. You should see they are not headings
[] Programme listing page, the programmes listings shouldn’t be header elements  because no content follows them, and screen reader users might expect there to be, given they are header elements
=> Fix/lesq 760/a11y link header [LESQ-760]

package-lock.json, src/__tests__/pages/teachers/sitemap.test.tsx, src/components/TeacherComponents/QuizQuestionsMCAnswers/QuizQuestionsMCAnswers.tsx, src/components/TeacherComponents/QuizQuestionsQuestionStem/QuizQuestionsQuestionStem.test.tsx, src/components/TeacherComponents/QuizQuestionsQuestionStem/QuizQuestionsQuestionStem.tsx
Music year: 1966
- add alt text to images in quiz stems and answers
Fixes #
https://www.notion.so/oaknationalacademy/Quiz-images-are-marked-up-as-decorative-however-they-require-an-alt-description-1b1038f7edba44378c0e50e70284a6c6?pvs=4
1. Go to https://deploy-preview-2404--oak-web-application.netlify.thenational.academy/teachers/programmes/science-primary-ks2/units/simple-electrical-circuits/lessons/building-simple-circuits#exit-quiz
3. You should see alt text on the images in the answers
4. Go to https://deploy-preview-2404--oak-web-application.netlify.thenational.academy/teachers/programmes/geography-primary-ks2/units/land-use-how-diverse-are-local-and-uk-landscapes/lessons/land-use-in-the-locality#exit-quiz
5. You should see alt text on the images in the questions
=> Chore/lesq 755/quiz alt text [LESQ-755]

next-sitemap.config.js
- Adds sitemap to the next-sitemap config so page does not error
Fixes 
- Currently sitemap is throwing an error, required to add to the config to resolve this
=> chore: add sitemap to next-sitemap config

src/node-lib/curriculum-api-2023/helpers/index.test.ts, src/node-lib/curriculum-api-2023/helpers/index.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.query.ts
Music year: 2007
- only include core tier in legacy maths
Fixes #
Core tier available on the unit listing page for new maths ks4 units
1. Go to https://deploy-preview-2413--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation/units
3. You should see no core tab
4. Go to https://deploy-preview-2413--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation-l/units
5. Yu should see core tab
6. programme listing page and other subjects should be unaffected
=> Fix/lesq 829/maths core new [LESQ-829]

package-lock.json, package.json, src/__tests__/pages/lesson-planning-new.test.tsx, src/components/GenericPagesComponents/PostPortableText/PostPortableText.tsx, src/pages-helpers/homesite/plan-a-lesson/getNavItems.test.tsx, src/pages-helpers/homesite/plan-a-lesson/getNavItems.ts, src/pages/lesson-planning-new.tsx
- Adds plan a lesson page nav to page
- Connects to cms
- Crudely adds some content without styling
Fixes #
1. Go to https://deploy-preview-2416--oak-web-application.netlify.thenational.academy/lesson-planning-new
- Test nav and back to contents buttons
{screenshots}
{screenshots}
=> Feat sticky nav for new plan a lesson - LESQ-782

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.gql, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.query.ts, src/node-lib/curriculum-api-2023/shared.schema.ts
Music year: 2019
- updates the lesson listing page to use the new browse mv
- updates tests
1. Go to https://deploy-preview-2426--oak-web-application.netlify.thenational.academy
Lesson listing pages should look the same (sorry Jack)
=> feat: new lesson listing query - LESQ-793

src/pages-helpers/curriculum/docx/curriculum-download-patcher/index.ts, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/back.test.ts, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/back.ts
Added finalised version of back page to docx file generation 
`CUR-559`
1. Go to https://deploy-preview-2430--oak-web-application.netlify.thenational.academy/teachers/curriculum/docx-poc/select
2. Choose a subject via the autoComplete
3. Download the docx template - linked on the page
4. Download the rendered document
5. Check the back page is present and correct
=> [CUR-559] Added back page to docx generation

next-sitemap.config.js
Music year: 2015
- Removes the sitemap size limit 
Fixes #
1. Go to https://deploy-preview-2437--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> Test: sitemap rendering without size limit

src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/__snapshots__/mainThreads.test.ts.snap, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/mainThreads.test.ts, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/mainThreads.ts, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/util.ts
- Added thread details pages to curriculum generated `.docx` 
`CUR-560`
1. Go to https://deploy-preview-2445--oak-web-application.netlify.thenational.academy/teachers/curriculum/docx-poc/select
2. Choose a subject via the autoComplete
3. Download the docx template - linked on the page
4. Download the rendered document
5. Check the cover page is present and correct
=> [CUR-560] docx thread details

next-sitemap.config.js, src/__tests__/pages/teachers/sitemap-1.test.tsx, src/node-lib/curriculum-api-2023/queries/teachersSitemap/teacherSitemap.query.test.ts, src/node-lib/curriculum-api-2023/queries/teachersSitemap/teacherSitemap.query.ts, src/pages/teachers/sitemap-1.xml/index.tsx, src/pages/teachers/sitemap.xml/index.tsx, src/utils/generateSitemapUrlFields.test.tsx, src/utils/generateSitemapUrlFields.ts
Music year: 1950
- Adds a second sitemap page and breaks into half to prevent the crashing of a single page
- Additional functions and test files or halving URL added
- Adds the second sitemap page to the config
Fixes #LESQ-847
1. Go to https://deploy-preview-2455--oak-web-application.netlify.thenational.academy/teachers/sitemap.xml
1. https://deploy-preview-2455--oak-web-application.netlify.thenational.academy/teachers/sitemap-1.xml
2. Should have the sitemap rendering
=> LESQ-847: Render teacher sitemap

src/components/SharedComponents/CategoryFilterList/CategoryFilterListItem.tsx
Music year: 1985
[Ticket](https://www.notion.so/oaknationalacademy/I-want-colours-with-high-enough-contrast-c9efbbf4e46d454fa6c42515cec66974?pvs=4)
- use a predefined colour (`grey60`) instead of opacity (50%) for selected filter list item on unit listing thread list
Fixes #
Insufficient contrast between text and background colour
1. Go to https://deploy-preview-2461--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks3/units
3. You should see the colour of the selected filter item satisfies a11y guidelines
=> fix: a11y colour contrast [LESQ-759]

src/components/PupilViews/PupilSubjectListing/PupilSubjectListing.view.tsx
Music year: 2010
fix padding on subject list
Fixes #
1. Go to https://deploy-preview-2462--oak-web-application.netlify.thenational.academy
3. You should see correct padding
=> PUPIL-720 feat(subjects): fix padding on subject list

package-lock.json
- Updated `ejs` as per https://github.com/oaknational/Oak-Web-Application/security/dependabot/99
`CUR-638`
Check storybook and tests (which this module is a dep of) works ok.
=> [CUR-638] Update `ejs` as per security warning in github

package-lock.json
- Updated `follow-redirects` as per https://github.com/oaknational/Oak-Web-Application/security/dependabot/92
See https://github.com/follow-redirects/follow-redirects/compare/v1.15.3...v1.15.6 for dependency changes
`CUR-643`
Minor changes to redirects shouldn't effect our users. To test generally check app works as expected
=> [CUR-643] Update `follow-redirects` dependency

package-lock.json
- Updated `express` as per https://github.com/oaknational/Oak-Web-Application/security/dependabot/94
`CUR-644`
Check storybook and tests (which this module is a dep of) works ok.
=> [CUR-644] update `express` dependency

package-lock.json, package.json
Music year: 1963
- update to canary version of mux-video-player-react at the recommendation of mux to try and resolve t[he errors we're seeing on Mac/Ios](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/66422ed418f4d300089ccdb8?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production&sort=events)
1. Go to https://deploy-preview-2480--oak-web-application.netlify.thenational.academy
2. Go to a teacher lesson and make sure video works
3. Same for pupils video and CMS video (eg in blogs)
=> chore: update mux video player [LESQ-900]

src/node-lib/curriculum-api-2023/fixtures/curriculumSiteMap.fixture.ts, src/pages/teachers/curriculum/sitemap.xml/index.tsx
The curriculum sitemap had `https:/` rather than `https://` because it was using `path.join(...)` with strips out duplicate slashes `/`
`CUR-516`
1. Go to https://deploy-preview-2481--oak-web-application.netlify.thenational.academy/teachers/curriculum/sitemap.xml
2. Check the sitemap has the correct protocol
=> [CUR-516] Fix protocol in curriculum sitemap

package-lock.json
- Updated `webpack-dev-middleware` as per https://github.com/oaknational/Oak-Web-Application/security/dependabot/93
`CUR-639`
Check storybook and tests (which this module is a dep of) works ok.
=> [CUR-639] Update `webpack-dev-middleware` as per security warning in github

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx
Fixed child-subject ordering in the curriculum visualiser. Rules are as follows
> Alphabetical but "combined-science" always comes first 
`CUR-594`
1. Go to https://deploy-preview-2482--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary-aqa/units
2. Check child subjects are in the correct order as per `CUR-594`
=> [CUR-594] Fix child-subject button ordering in curriculum visualiser

package-lock.json, package.json
As mentioned in https://github.com/dependabot/dependabot-core/issues/9277#issue-2183840900 hopefully changing the `npm` version in the `engine` field to `>=9.6.5` will get dependabot running again and creating PRs.
The original error we're trying to overcome is
```
Dependabot uses Node.js v20.14.0
and NPM 10.7.0
. Due to the engine-strict setting, the update will not succeed.
```
`FEC-73`
We can't test the actual fix prior to merge, hopefully it'll work once merged and dependabot will start working again.
With regards to the deployed code, nothing should change as our github action workflows run with particular versions of node/npm anyway.
=> [FEC-73] Change npm version in engine field to get dependabot running again

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.test.tsx, src/components/TeacherComponents/ResourceCard/ResourceCard.tsx
Music year: 1955
- updates aria label on resource card checkboxes to include resource type
- change 'pptx' to 'powerpoint' for readability
1. Go to https://deploy-preview-2487--oak-web-application.netlify.thenational.academy/teachers/programmes/chemistry-secondary-ks4-foundation-edexcel/units/atomic-structure-and-the-periodic-table/lessons/atomic-structure-negligible-electron-mass/downloads?preselected=all
2. Use screen reader to select checkboxes
3. You should get the resource file format along with resource type
=> Feat/lesq 762/screen reader resource types [LESQ-762]

src/components/GenericPagesComponents/NewsletterForm/NewsletterForm.tsx, src/components/SharedComponents/FieldError/FieldError.tsx, src/components/TeacherComponents/ResourcePageLayout/ResourcePageLayout.tsx, src/components/TeacherComponents/ResourcePageSchoolDetails/ResourcePageSchoolDetails.tsx, src/components/TeacherComponents/ResourcePageSchoolPicker/ResourcePageSchoolPicker.tsx, src/components/TeacherComponents/ResourcePageSearchComboBox/ResourcePageSearchComboBox.tsx, src/components/TeacherComponents/ResourcePageTermsAndConditionsCheckbox/ResourcePageTermsAndConditionsCheckbox.tsx, src/components/TeacherComponents/TermsAgreementForm/TermsAgreementForm.tsx
- Turns browser validation off for newsletter form (this was blocking custom form messages)
- Adds area live option for field error (on downloads and share where button is disabled this will read out errors to user)
- Adds aria invalid to school group 
- Adds described by to resources page inputs
Users using screen reader should be notified of errors
1. Go to https://deploy-preview-2485--oak-web-application.netlify.thenational.academy
- newsletter form  - https://deploy-preview-2485--oak-web-application.netlify.thenational.academy/#teachers
- downloads form - https://deploy-preview-2485--oak-web-application.netlify.thenational.academy/teachers/programmes/computing-non-gcse-secondary-ks4-l/units/it-and-the-world-of-work-c47e/lessons/the-modern-world-of-work-65jp …
=> feat: improve aria form error messaging - LESQ-758

src/components/TeacherComponents/LessonShareCardGroup/LessonShareCardGroup.tsx, src/components/TeacherComponents/ResourcePageLayout/ResourcePageLayout.tsx, src/components/TeacherComponents/ResourcePageSchoolDetails/ResourcePageSchoolDetails.tsx
Music year: 1960
- Add fieldset and legend to checkbox group for resources (downloads not share)
- Adds fieldset and legend to school picker and 'school not listed' checkbox 
Fixes #
1. Go to https://deploy-preview-2489--oak-web-application.netlify.thenational.academy
download : downloads lesson resources group should be read out 
school picker and checkbox: school details group school be read out.
=> Lesq 751   radio buttons in fieldset with legend - LESQ-751

src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/__snapshots__/threadsTable.test.ts.snap, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/threadsTable.ts, src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/units.ts
Issues fixes
- Because of invalid nesting in our docx files XML, the google drive docx-renderer was failing to render lessons/threads
- Threads overview table was too small when rendered in google drive
- Optionality issue with whitespace
1. Go to https://deploy-preview-2502--oak-web-application.netlify.thenational.academy/teachers/curriculum/docx-poc/select
2. Generate a document
3. Upload the google drive and check issues described above are resolved
=> Fix docx -> google drive rendering issues

src/pages/about-us/partners.tsx
Music year: 1962
Remove meet the teachers section from the about us page.
See the ticket [here ](https://www.notion.so/oaknationalacademy/Update-About-Us-Page-2a2ba7cf94f54dd881fd27e227547d54)
1. Go to https://deploy-preview-2513--oak-web-application.netlify.thenational.academy/about-us/partners
2. You shouldn't see a meet the teacher section below "From humble roots..."
=> [PUPIL-810] Remove meet our teachers section from about us

src/components/GenericPagesComponents/InlineSpriteSheet/InlineSpriteSheet.tsx
Music year: 1953
This wraps the inline svg sprite with a div and hides it. Applying the style to the sprite itself results in all the svgs within the spritesheet getting that style (seems odd I know), so the only option was to add the extra div.
This was introduced with the recent fix for the latest version of Chrome where svgs on the site stopped displaying.
1. Go to https://deploy-preview-2515--oak-web-application.netlify.thenational.academy
2. Click on any page, there should be no svg visible at the bottom of the page.
3. Test other areas of the site to check svgs are working
4. Check if this has resolved drag and drop issue in pupil quizzes
=> [PUPIL-811] Hide inline svg spritesheet

src/__tests__/__helpers__/renderWithProviders.tsx, src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx, src/components/CurriculumComponents/OakComponentsKitchen/SkipLink/SkipLink.stories.tsx, src/components/CurriculumComponents/OakComponentsKitchen/SkipLink/SkipLink.test.tsx, src/components/CurriculumComponents/OakComponentsKitchen/SkipLink/__snapshots__/SkipLink.test.tsx.snap, src/components/CurriculumComponents/OakComponentsKitchen/SkipLink/index.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx, src/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].tsx
Added skip links to curriculum visualiser and a `<SkipLink/>` component to `./CurriculumComponents/OakComponentsKitchen`
`CUR-682`
1. Go to https://deploy-preview-2519--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary-aqa/units
2. Tab through content until you see the "Skip to units" should appear when highlighted.
3. Upon hitting enter, focus should jump to top of units
=> [CUR-682] Added a11y skip link to curriculum visualiser

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx
- Added `role="group"` and `aria-label` to container divs for domain/subject/tier filters in curriculum visualiser
- Add `aria-pressed="true"` to currently active button in each filter group.
`CUR-473`
1. Go to https://deploy-preview-2520--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary-edexcel/units
2. Test using voice over
=> [CUR-473] Added group role, aria-label and aria-pressed to domain/subject/tier buttons

package-lock.json, package.json, src/pages/_app.tsx
How to test: the app still works, sorry @jack-skerrett-oak ! It's a minor version change, so I don't expect issues.
P.s. Storybook built on re-run, but that doesn't update the commit statuses in GitHub.
=> Update React, remove a provider that doesn't do anything in React 18

src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Music year: [1957](https://open.spotify.com/track/4gphxUgq0JSFv2BCLhNDiE?si=686587445de94ae1)
- Adds `aria-required` to each radiogroup in the subject-phase picker modal (subject, phase, exam board)
- Ensures that each group of selectable options is announced as 'required' to screen reader and other AT users.
Fixes [this a11y audit finding re: subject-phase picker](https://www.notion.so/oaknationalacademy/Forms-fields-that-are-required-are-not-marked-visually-and-programatically-675790568a754cb2bd8fd662fa196337?pvs=4)
1. Go to https://deploy-preview-2548--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Launch your screen reader of choice
3. Open one of the modal dialogs within the subject-phase picker
4. Navigate to a button
6. The button should be announced as …
=> chore: add aria-required to subject-phase picker radiogroups

src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.ts, src/pages/teachers/lessons/[lessonSlug].tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx, src/utils/handleTranscript.test.ts, src/utils/handleTranscript.ts
Music year: 2019
[Ticket](https://www.notion.so/oaknationalacademy/Canonical-lessons-do-not-display-transcripts-e65b1527ada8406c939eccc396d6c1de?pvs=4)
- move logic to fetch and transform video transcripts into lesson overview query used by canonical lessons as well
Fixes #
canonical lessons not having video transcripts
1. Go to https://deploy-preview-2545--oak-web-application.netlify.thenational.academy/teachers/lessons/developing-a-model-for-atoms#video
3. You should see trasncript for the video
=> fix: transcripts for canonical lessons [LESQ-835]

package-lock.json, package.json, src/browser-lib/cookie-consent/CookieConsentProvider.tsx, src/components/AppComponents/AppHeader/AppHeader.test.tsx, src/components/AppComponents/AppHeader/AppHeader.tsx, src/components/AppComponents/AppHeaderMenu/AppHeaderMenu.tsx
Music year: [1957](https://www.youtube.com/watch?v=V_FAqr6rP4w)
Fixes the consent banner rendering above modals blocking interaction.
Scenario 1: Modals
1. Open https://deploy-preview-2554--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-primary/units in an incognito session
2. Click “Unit info” on any of the cards
3. You should see the modal above the consent banner
Scenario 2: Burger menu
1. Open https://deploy-preview-2554--oak-web-application.netlify.thenational.academy in an incognito session
2. Click the burger menu icon in the top right
3. You should see the menu above the consent banner
How it used to look
=> [ENG-813] Consent banner stacked in front of modals

package-lock.json, package.json
Updates `date-fns` from `2.30.0` to `3.6.0`
Effected areas of website are the blog
```bash
grep -r date-fns src 
```
The `isFuture` and `isPast` API's have not changed between versions.
=> Update `date-fns` dependency

package-lock.json, package.json
Updated `copy-webpack-plugin` through major version
It's used to copy over mathjax, see `./next.config.ts`
```ts
config.plugins.push(
new CopyPlugin({
patterns: [
{
from: path.join(__dirname, "node_modules/mathjax/es5"),
to: path.join(__dirname, "public/mathjax"),
},
],
}),
);
```
**Note**: I've confirmed mathjax still works by visiting `/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/highest-common-factor-with-algebraic-terms/starter-quiz`
Min-version of nodejs changed, however we're `>20` anyway 
```
"engines": {
"node": ">=20 <21",
"npm": ">=9.6.5"
},
```
See following from <https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md>
=> Update `copy-webpack-plugin` dependency

package-lock.json, package.json
The `change-case` dependency has changed to fill in some edge cases. However we only use it to `camelCase` simple keys, see [`./netlify/plugins/slack-reporting/slack/get_slack_config.js`](https://github.com/oaknational/Oak-Web-Application/blob/8281ded025612d3ee1b0ac8a9fe58ce3a39063ec/netlify/plugins/slack-reporting/slack/get_slack_config.js#L3-L6)
=> Update `change-case` dependency

package-lock.json, package.json
bumped from 7.19.0 to 7.24.0
only change affecting plugin-react is 
(plugin-react) Modified the polynomial regular expression to remove the ambiguity https://github.com/bugsnag/bugsnag-js/pull/2135
=> chore: bump bugsnag react plugin

package-lock.json, package.json
Used to download video transcripts from google cloud buckets
Bump from 7.10 to 7.11.2
changelog shows no breaking changes
https://github.com/googleapis/nodejs-storage/blob/main/CHANGELOG.md
Tested by loading legacy and cycle 1 pages with video transcripts without error
=> chore: bump google cloud storage

package-lock.json, package.json
This is used in the `search-api` see [`src/context/Search/search-api/2023/fetchResults.ts`](https://github.com/oaknational/Oak-Web-Application/blob/8281ded025612d3ee1b0ac8a9fe58ce3a39063ec/src/context/Search/search-api/2023/fetchResults.ts)
I've manually tested `/teachers/search` route and all seems fine.
=> Update `snakecase-keys` dependency

src/__tests__/pages/teachers/key-stages/[keyStageSlug]/subjects/index.test.tsx, src/components/TeacherComponents/SubjectListingCardDouble/SubjectListingCardDouble.test.tsx, src/components/TeacherComponents/helpers/lessonHelpers/lesson.helpers.ts, src/node-lib/curriculum-api-2023/fixtures/subjectListing.fixture.ts, src/pages/teachers/key-stages/[keyStageSlug]/subjects/index.tsx, src/pages/teachers/programmes/[programmeSlug]/units.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx
Music year: 2003
- EYFS was being excluded in the logic for combining new and legacy maths, as there is only legacy content
- this includes EYFS for maths subject only and doesn't combine counts
Fixes #
Maths EYFS gone missing from the site
1. Go to https://deploy-preview-2559--oak-web-application.netlify.thenational.academy/teachers/key-stages/early-years-foundation-stage/subjects
3. You should see a card for maths
4. Click through and the counts should be correct
5. There should be no 'new' tag on any of the content
=> fix: only combine unit listing pages for ks1-4 maths [LESQ-949]

src/components/SharedComponents/helpers/downloadAndShareHelpers/createAndClickHiddenDownloadLink.tsx
Fixing DOM text reinterpreted as HTML alert
```
export const hideAndClickDownloadLink = (url: string, a: HTMLAnchorElement) => {
a.style.display = "none";
a.href = URL;
```
is reinterpreted as HTML without escaping meta-characters.
[DOM text reinterpreted as HTML](https://github.com/oaknational/Oak-Web-Application/security/code-scanning/51)
1. Go to https://deploy-preview-2593--oak-web-application.netlify.thenational.academy
2. Click on /teachers/curriculum/
3. You should be able to download curriculum plans
4. CodeQL should remove errors when scanning
=> fix(sec): encode URI when DOM text is reinterpreted as HTML

netlify/plugins/slack-reporting/index.js, netlify/plugins/slack-reporting/slack/create_slack_message/build_complete.js, netlify/plugins/slack-reporting/slack/create_slack_message/build_started.js, netlify/plugins/slack-reporting/slack/create_slack_message/index.js, netlify/plugins/slack-reporting/slack/create_slack_message/validate_config.js, netlify/plugins/slack-reporting/slack/get_slack_config.js, netlify/plugins/slack-reporting/slack/send_message.js
Music year: 1998
- update slack-reporting netlify plugin to esm
- this looks to be faling since updating the  `Netlify/plugin-nextjs` dependancy
Fixes #
[Builds failing due to plugin error](https://app.netlify.com/sites/oak-web-application/deploys?filter=main)
As far as I can tell the slack plugin only runs on production builds, so I'm not sure how to test it properly
=> fix: update netlify slack plugin code to esm syntax

src/pages-helpers/curriculum/docx/curriculum-download-patcher/patches/units.ts
Added unit title/descriptions for cycle 1 documents.
Fixes `CUR-770`
1. Go to https://deploy-preview-2625--oak-web-application.netlify.thenational.academy/teachers/curriculum/docx-poc/select
2. Generate documents for cycle1/cycle2 document and check that unit title/description and why-this-why-now is present for the relevant cycles. Also check unit options.
=> fix: added unit descriptions for cycle 1 documents

src/pages/teachers/programmes/[programmeSlug]/units.tsx
Music year: 2002
- Fixes threads dropdown bug so it renders at full screen
Fixes #LESQ-932
1. Go to https://deploy-preview-2629--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-aqa/units or any subject with threads 
2. You should see dropdown renders at full width on mobile
=> LESQ-932: Threads dropdown bug

src/pages/api/curriculum-downloads/index.ts
Music year: 2005
- Updated filtering for units 
- Missing units in Secondary science & maths
Maths Higher
=> [CUR-796] Missing filtered units in downloads

src/pages-helpers/curriculum/docx/builder/1_frontCover.test.ts, src/pages-helpers/curriculum/docx/builder/1_frontCover.ts, src/pages-helpers/curriculum/docx/index.ts, src/pages/api/curriculum-downloads/index.ts
- Updated title page to have correct subtitle according to filters 
- Updated filename to have proper formatting (e.g. "Combined-science" becomes "Combined science") for subject titles longer than a word
English
=> [CUR-791] Child subject & tier subtitle on title page for docx

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumUnits/curriculumUnits.gql
Update to `published_mv_curriculum_units_0_6` which filters out `year = "All"` in MV (see [here](https://github.com/oaknational/Database-Tools/blob/6c7492cd39b2fe143f3ec0d2f96fdd2ead311e59/sql-and-graphql-library/SQL/owa-materialized-views/mv_curriculum_units.sql#L245))
Fixes `CUR-799`
Check that the curriculum visualiser is still in working order (no regressions)
=> Update to `published_mv_curriculum_units_0_6`

src/node-lib/curriculum-api-2023/sdk.ts
so we can identify requests from OWA more easily in logs
=> chore: add a user-agent header to requests from the curriculum API GQL client

avo.json, src/browser-lib/avo/Avo.ts, src/common-lib/urls/urls.ts
Music year: 1953
- Onboarding page name was updated in AVO branch after review but not pulled into dev branch after changes.
when the PR and then AVO branch was merged this broke the types in URL.
- This pulls from avo main and fixes the page name type
Fixes #
1. Go to https://deploy-preview-2710--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> fix: incorrect onboarding page name

src/pages-helpers/pupil/lessons-pages/getProps.ts
When previewing pages the video transcripts aren't yet created by the ingest process . This means that attempts to find them result in an error creating a 404.
Fixes #
Wrap the call to requestLessonResources in a try/catch and then conditionally throw the error depending whether it's a preview page or not.
1. Go to https://deploy-preview-2708--oak-web-application.netlify.thenational.academy/pupils/beta/previews/lessons/natural-selection-at-the-genetic-level/overview
2. should be visible where as on production it is a 404
=> fix: wrap requestLessonResources in try catch

clerk.d.ts, src/__tests__/__helpers__/mockUser.ts, src/app/api/auth/onboarding/route.test.ts, src/app/api/auth/onboarding/route.ts, src/common-lib/schemas/onboarding.ts, src/components/TeacherComponents/OnboardingForm/OnboardingForm.test.tsx, src/components/TeacherComponents/OnboardingForm/OnboardingForm.tsx, src/components/TeacherComponents/OnboardingForm/onboardingActions.test.ts, src/components/TeacherComponents/OnboardingForm/onboardingActions.ts, src/hocs/withOnboardingRequired.test.tsx, src/hocs/withOnboardingRequired.tsx, src/hooks/useRequireOnboarding.test.ts, src/hooks/useRequireOnboarding.ts, src/pages/onboarding/index.tsx, src/pages/onboarding/role-selection.tsx, src/pages/onboarding/school-selection.tsx
Music year: 1994
- sets `{ owa: { isTeacher } }` in the user's Clerk public metadata depending on their onboarding choices, we can use this to authorise access to resources later.
- sets `sourceApp` in the user's Clerk public metadata to the origin of the app from which the user first onboarded. In production this will be `https://www.thenational.academy` we can use this to attribute sign-ups to OWA.
1. Go to https://deploy-preview-2713--oak-web-application.netlify.thenational.academy/onboarding
2. Login if necessary
3. Onboard as a teacher picking a school or entering one manually
4. Find your account in Clerk and verify that your public metadata contains `{ owa: { isTeacher: true } }`
5. Repeat 1. but onboard as a non-teacher
6. Reload your account in Clerk and verify that your public …
=> LESQ-1007: Add user onboarding details to clerk

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumOverview/curriculumOverview.gql, src/node-lib/curriculum-api-2023/queries/curriculumUnits/curriculumUnits.gql, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.gql, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.query.ts, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.schema.ts
Update the curriculum MVs which filter out cycle 2 programmes from curriculum visualiser until ready for launch.
Fixes `CUR-788`
Test that there are no functional changes to the visualiser. Also @rightsaidjames are you able to find out if we can publish a programme on staging double check it all works correctly prior to production publish?
FYI: I can setup, a test env for staging locally and proxy it over to you.
=> Update MVs which filter out cycle 2 programmes

scripts/build/write_env_file/index.js, src/__tests__/__helpers__/mockUser.ts, src/components/TeacherComponents/OnboardingForm/OnboardingForm.test.tsx, src/components/TeacherComponents/OnboardingForm/OnboardingForm.tsx, src/components/TeacherComponents/OnboardingForm/onboardingActions.test.ts, src/components/TeacherComponents/OnboardingForm/onboardingActions.ts, src/components/TeacherViews/Onboarding/Onboarding.view.tsx, src/components/TeacherViews/Onboarding/RoleSelection/RoleSelection.view.tsx, src/components/TeacherViews/Onboarding/SchoolSelection/SchoolSelection.view.tsx, src/node-lib/getServerConfig.ts, src/pages/api/hubspot/subscription/index.test.ts, src/pages/api/hubspot/subscription/index.ts
- Add an api route to get a user's subscription status
- Make the hubspot sign up checkbox conditional on subscription status
1. Go to https://deploy-preview-2756--oak-web-application.netlify.thenational.academy/onboarding **while logged in**
2. You should not see the sign up checkbox
3. Go to school selection
4. You should see an unchecked checkbox on the page (if you haven't already set up a subscription)
5. Go to the contact for your email in hubspot ([example](https://app-eu1.hubspot.com/contacts/24947711/record/0-1/33730277100)) and on the left under 'communication subscriptions` update the School Support subscription to subscribed 
6. Go back to the school selection page and refresh
7. You should not see the checkbox
How it used to look (d
elete if n/a): …
=> Feat/lesq 1054/hubspot checkbox conditional [LESQ-1054]

.github/workflows/code_checks.yml, .github/workflows/create_semantic_release.yml, .github/workflows/post_deployment_actions.yml, package-lock.json, package.json
Chromuim (via puppeteer) was previously being downloaded on each CI run causing a massive spike in CI times.
This PR stores chromium in the `.npm` directory so it gets cached with the setup-node action, this should speed up the following workflows by around 4-5mins each
- `.github/workflows/code_checks.yml`
- `.github/workflows/create_semantic_release.yml`
- `.github/workflows/post_deployment_actions.yml`
Previous `npm ci` took `5m 45s`
After `npm ci` takes `52s` (with cache)
Fixes `FEC-81`
=> CI performance fixes

src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructCanonicalLessonDownloads.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructLessonDownloads.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/lessonListing/lessonListing.query.ts, src/node-lib/curriculum-api-2023/queries/lessonOverview/lessonOverview.query.ts, src/node-lib/curriculum-api-2023/queries/lessonShare/lessonShare.query.ts
Music year: 2018
- update lessonListing, lessonOverview, and lessonDownload queries to use optionality title for the unit title when present
- add test for this
Fixes #
Null unitvariant title being used on optionality units
1. Go to https://deploy-preview-2765--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-aqa/units/modern-text-first-study-152/lessons
3. You should see the optionality title 'Animal Farm: the pigs and power' as the heading and in breadcrumbs
4. Continue the journey to lesson overview and downloads/share and it should continue to use the optionality title in breadcrumbs
5. Clicking on the breadcrumbs should work
6. Canonical lesson page breadcrumbs should also be using optionality unit title …
=> fix: use optionality title for unit when available [LESQ-1063]

src/app/(registration)/formAppearanceStyles.ts, src/app/(registration)/sign-in/[[...sign-in]]/page.tsx, src/app/(registration)/sign-up/[[...sign-up]]/page.tsx, src/components/AppComponents/AppHeader/AppHeader.test.tsx, src/components/AppComponents/AppHeader/AppHeader.tsx, src/components/AppComponents/AppHeaderBurgerMenuSections/AppHeaderBurgerMenuSections.test.tsx, src/components/AppComponents/AppHeaderBurgerMenuSections/AppHeaderBurgerMenuSections.tsx
- Replaces sign out in hamburger with clerk signout in app header
- Updates clerk style to match OWA (as much as possible considering limitations) 
https://www.figma.com/design/fxWHjjNzvbbc0J38pM3Kti/Log-in?node-id=2343-5313&node-type=SECTION&m=dev
[[Ticket checklist (non-tester)](https://www.notion.so/Ticket-checklist-non-tester-5317535736fe47fb984a3591a1bd7616?pvs=21)](https://www.notion.so/Ticket-checklist-non-tester-5317535736fe47fb984a3591a1bd7616?pvs=21)
Fixes #
1. Go to https://deploy-preview-2757--oak-web-application.netlify.thenational.academy
Go to lesson download and sign in, you should see avatar in app header, test criteria above.
=> LESQ 1042 & LESQ-1038 - clerk sign out button and form styles

src/components/TeacherComponents/UnitList/UnitList.tsx, src/components/TeacherComponents/UnitsLearningThemeFilters/UnitsLearningThemeFilters.test.tsx, src/components/TeacherComponents/UnitsLearningThemeFilters/UnitsLearningThemeFilters.tsx
Music year: 2011
- Adds skip button to threads on unit page
Fixes #
1. Go to https://deploy-preview-2769--oak-web-application.netlify.thenational.academy
Got to unit and specialist unit page - tab through page, you should see a skip to units button that will skip thread filters
=> Feat skip button on unit page  - LESQ-1048

src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/index.ts, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.gql, src/node-lib/curriculum-api-2023/queries/subjectPhaseOptions/subjectPhaseOptions.schema.ts, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts
The text "Key stage 1 and 2" and  "Key stage 3 and 4" will now be generated from the key stages available.  
Although we haven't got any it also now supports single key stages, such as "Key stage 1" or "Key stage 3"
Fixes `CUR-857`
Test for regressions in the above UI. There should be no functional changes until we enable cycle 2.
=> Key stage text derived from list of available key stages

src/components/PupilComponents/PupilUnitsSection/PupilUnitsSection.tsx
Pupil area is not showing optionality units when there are only two units to display (showing more than two remains unaffected)
Eg.https://www.thenational.academy/pupils/programmes/english-secondary-year-10-edexcel/units
Fixes #
This was because the backend was changed to stop serving null unitvariants alongside their optionality counterparts. I removed the condition which filtered for this situation and allowed arrays of two unitvariants to be rendered.
1. Go to https://deploy-preview-2782--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-year-10-edexcel/units
Confirm that you can see the same optionality units as in the teacher journey
https://www.thenational.academy/teachers/programmes/english-secondary-ks4-edexcel/units
=> fix: render optionality units when there are 2 of them

src/context/FeatureFlaggedClerk/FeatureFlaggedClerk.tsx
Music year: 1978
the production Clerk environment is misconfigured and both the sign-in and sign-up routes point to labs.thenational.academy. It makes sense to have these paths under version control so i'm setting them in code instead of doing it through the Clerk UI to avoid causing any issues with the AI project. Clerk themselves say you should do this and it keeps OWA decoupled from other projects.
🚨 **This will only have an impact in production where the environment is currently misconfigured in Clerk. That is also the only environment in which we can properly test that login sessions are shared between labs and OWA.** 
👇🏻 Production these are quite clearly wrong for both labs and OWA — in labs the environment variables are set to override these values so there is currently no issue …
=> fix(LESQ-1066): set the sign-in and sign-up routes on ClerkProvider

src/middleware.ts
it causes page latency and we don't need it everywhere right now. Going forward if we need to access the user session on all pages we'll have to tackle this.
Music year: 2013
Fixes #
1. Go to https://deploy-preview-2788--oak-web-application.netlify.thenational.academy
{screenshots}
{screenshots}
=> chore: disable Clerk middleware for everything but API routes

src/components/TeacherComponents/ManualEntrySchoolDetails/ManualEntrySchoolDetails.tsx, src/components/TeacherComponents/OnboardingForm/OnboardingForm.schema.ts, src/components/TeacherComponents/OnboardingForm/OnboardingForm.tsx, src/components/TeacherViews/Onboarding/RoleSelection/RoleSelection.test.tsx, src/components/TeacherViews/Onboarding/RoleSelection/RoleSelection.view.tsx, src/components/TeacherViews/Onboarding/SchoolSelection/SchoolSelection.test.tsx, src/components/TeacherViews/Onboarding/SchoolSelection/SchoolSelection.view.tsx
Music year: 1971
Fixes #
1. Removes the minimum length requirement on the manually entered school name and address
2. Sets the manual school name, school address and school picker inputs as "required"
3. Fixes a regression in the role selection form caused by the above changes (this page should be retested 🙇🏻 )
1. Go to https://deploy-preview-2798--oak-web-application.netlify.thenational.academy/onboarding
5. Select "Yes" when asked if you "Work in a school"
6. You should see a required field for the school picker
7. Click "Enter manually"
8. You should see required fields for "School name" and "School address"
9. You should be able to a enter a non-whitespace only string into both and proceed
How it used to look
=> LESQ-1073: Remove restriction on manual school entry

src/components/TeacherComponents/LessonItemContainerLink/LessonItemContainerLink.tsx
Music year: 1963
- Each download button on the download page should navigate un-onboarded users / non-logged in users to onboarding page
Fixes #LESQ-1076
1. Go to https://deploy-preview-2809--oak-web-application.netlify.thenational.academy
2. Navigate to any lesson page, all download buttons should navigate you to the onboarding journey when not signed in
https://github.com/user-attachments/assets/7cb88833-4950-4c36-84b9-1eb675f042b9
=> LESQ-1076: Individual download buttons require onboarding

next-env.d.ts, src/__tests__/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].test.tsx, src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.test.tsx, src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx, src/components/CurriculumComponents/OakComponentsKitchen/Alert/Alert.stories.tsx, src/components/CurriculumComponents/OakComponentsKitchen/Alert/Alert.test.tsx, src/components/CurriculumComponents/OakComponentsKitchen/Alert/__snapshots__/Alert.test.tsx.snap, src/components/CurriculumComponents/OakComponentsKitchen/Alert/index.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx, src/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].tsx, src/utils/curriculum/constants.ts, src/utils/curriculum/features.test.ts, src/utils/curriculum/features.ts, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts
Added `<Alert/>` component and initial swimming functionality for cycle 2 curriculum all behind a flag.
Because we haven't got a published primary PE with "all-years", I've added a constant `SWIMMING_HACK`, which when enabled turns some PE secondary into "swimming units".
`<Alert/>`  in the curriculum kitchen
Swimming "all years" hacked into PE secondary when `SWIMMING_HACK` and `ENABLE_CYCLE_2` is enabled
Completes `CUR-843` & `CUR-841`
Cycle 1 regressions
1. Go to https://deploy-preview-2813--oak-web-application.netlify.thenational.academy
2. Check for regressions in the curriculum visualiser
Cycle 2 testing
1. Enable `SWIMMING_HACK` and `ENABLE_CYCLE_2`
2. Check that blue info box appears and is correct
3. Check that filtering works, year is at the top of the visualiser and titles are …
=> Added `<Alert/>` component and initial swimming functionality for cycle 2 curriculum

src/components/CurriculumComponents/OakComponentsKitchen/Alert/__snapshots__/Alert.test.tsx.snap, src/components/CurriculumComponents/OakComponentsKitchen/Alert/index.tsx
Music year: 2016
- Change border radius of `oak-inline-banner` inside `<Alert />` component to `border-radius-m2` so that it comes out as 8px and is consistent with [the design](https://www.figma.com/design/3cz9fb0ObFDLv1c212OtJv/Final-designs---Curriculum-squad?node-id=5233-97372&m=dev).
Fixes #CUR-841
Locally:
- Enable `SWIMMING_HACK` and `ENABLE_CYCLE_2`
- Check that blue info box has the correct border radius.
Storybook:
- Go to https://deploy-preview-2818--owa-storybook.netlify.thenational.academy/?path=/story/components-curriculumcomponents-oakcomponentskitchen-alert--alert
- Check border radius of alert components.
=> fix: tweak border radius of oak-inline banner

src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/OverviewTab/OverviewTab.test.tsx, src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx, src/utils/curriculum/constants.ts, src/utils/curriculum/features.test.ts, src/utils/curriculum/features.ts
Added new curriculum explainer styling sticky contents and new partners footer in overview tab
- Added new partner styling
- Curriculum explainer typography styles
- Sticky contents pane
- Color changes to header
- `CUR-892`
- `CUR-895` (only UI part)
- `CUR-893`
- Check for regressions in cycle 1
- Test tickets linked above with `ENABLE_CYCLE_2` enabled
https://github.com/user-attachments/assets/8d8b981b-8c94-4298-a1da-e08ba3f24753
=> Added new curriculum explainer styling in overview tab

sonar-project.properties, src/app/(registration)/layout.tsx, src/app/layout.tsx, src/app/styles-registry.tsx
Music year: 1988
rendering two sign-up/sign-in forms was causing the email confirmation
to be sent twice. I believe this was intended to make it easier to
present an alternative mobile view of the sign-up UI.
it appears to ultimately be an implementation bug in Clerk, because this
only happens with the confirmation link flow and not with the confirmation
code flow. Also if you refresh the page it will send another link which
is not great.
1. Go to https://deploy-preview-2834--oak-web-application.netlify.thenational.academy/sign-up
2. Sign up with an email address
3. You should see the "Verify your email" screen
4. Check your email
5. You should have received one confirmation email
🚨 **I had to make some tweaks to the way the responsive layout was implemented to fix this. Definitely worth …
=> LESQ-1096: fix confirmation email sent twice

src/components/TeacherComponents/OnboardingForm/OnboardingForm.test.tsx, src/components/TeacherComponents/OnboardingForm/OnboardingForm.tsx, src/components/TeacherComponents/OnboardingForm/onboardingActions.test.ts, src/components/TeacherComponents/OnboardingForm/onboardingActions.ts, src/components/TeacherViews/Onboarding/HowCanOakSupport/HowCanOakSupport.view.tsx
Music year: 1977
- Disables the onboarding form (by setting the buttons to disabled) while the user is being onboarded to Clerk and Hubspot
1. Go to https://deploy-preview-2840--oak-web-application.netlify.thenational.academy/onboarding
2. Onboard as usual
3. On the last step the "Continue" and "Skip" buttons should switch to a disabled state while submission is taking place
=> LESQ-1097: Prevent multiple submissions of onboarding form

src/__tests__/__helpers__/mockUser.ts, src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].test.tsx, src/__tests__/pages/teachers/specialist/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].test.tsx, src/components/TeacherComponents/LessonOverviewHeaderDownloadAllButton/LessonOverviewHeaderDownloadAllButton.tsx
Music year: 1988
- Changes download button on lesson overview page based on if a use is signed in and onboarded or not
- Updates download test to have logged in user
Fixes #LESQ-984
1. Go to https://deploy-preview-2845--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-higher-edexcel/units/atomic-structure-and-the-periodic-table/lessons/atomic-structure-negligible-electron-mass#slide-deck 
(Or any lesson page)
2. You should see when feature flag is enabled, download all button say sign in to download all resources
3. After sign in, button says Download all resources
=> LESQ-984: download button on lesson overview page is dynamic

package-lock.json, package.json, src/app/(registration)/auth-layout.tsx, src/app/(registration)/sign-in/[[...sign-in]]/page.tsx, src/app/(registration)/sign-up/[[...sign-up]]/page.tsx, src/app/layout.tsx, src/components/CurriculumComponents/CurriculumDownloadTab/CurriculumDownloadTab.test.tsx
Music year: 1971
Figma: https://www.figma.com/design/fxWHjjNzvbbc0J38pM3Kti/Log-in?node-id=3330-8406&m=dev
Design: 
🎨  I diverged from the design in a few places:
* The copy colour is #222 or `text-primary` — _i think the use of #000 in Figma was a bug_
* ~~The "No pupils" banner has a border — _this is consistent with the design kit and storybook components_~~
* The "No pupils" banner uses the "info" icon from the design kit and storybook — _looks like the one in the design is from an obsolete design file?_
⚠️ We have limited control over the login box itself so this PR is only intended to update the heading and subheading copy of that component, everything else is out of scope
1. Go to https://deploy-preview-2851--oak-web-application.netlify.thenational.academy/sign-up
2. You should see …
=> LESQ-1088: Updated sign up page copy

package-lock.json, package.json
Music year: 1960
- Bump oak components to include new subject icon `subject-cooking-nutrition`
- This icon does not exist in cloudinary yet (should be added this week) so will appear broken until then: 
https://deploy-preview-2870--oak-web-application.netlify.thenational.academy/teachers/search?term=macbeth
=> chore: bump oak components

src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Changes to lot picker text to "Explore our curricula for 2024/2025." for cycle 2 release.
Fixes `CUR-947`
- Check text unchanged at https://deploy-preview-2872--oak-web-application.netlify.thenational.academy
- Check when cycle 2 enabled locally text changes to "Explore our curricula for 2024/2025."
=> Changes lot picker text for cycle 2 release

src/__tests__/pages/about-us/board.test.tsx, src/__tests__/pages/onboarding/index.test.tsx, src/__tests__/pages/onboarding/role-selection.test.tsx, src/__tests__/pages/onboarding/school-selection.test.tsx, src/__tests__/pages/teachers/search.test.tsx, src/app/(registration)/auth-layout.tsx, src/app/(registration)/sign-in/[[...sign-in]]/page.tsx, src/app/(registration)/sign-up/[[...sign-up]]/page.tsx, src/components/AppComponents/AppHeader/AppHeader.test.tsx, src/components/TeacherComponents/LessonItemContainerLink/LessonItemContainerLink.tsx, src/components/TeacherComponents/LessonOverviewHeaderDownloadAllButton/LessonOverviewHeaderDownloadAllButton.tsx, src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormState.test.tsx, src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormState.tsx, src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormSubmit.ts, src/components/TeacherViews/LessonDownloads.view.test.tsx, src/components/TeacherViews/LessonDownloads.view.tsx, src/components/TeacherViews/Onboarding/ONboarding.test.tsx, src/hocs/withFeatureFlag.test.tsx, src/hocs/withFeatureFlag.tsx, src/pages/onboarding/how-can-oak-support-you.tsx, src/pages/onboarding/index.tsx, src/pages/onboarding/role-selection.tsx, src/pages/onboarding/school-selection.tsx
This swaps out the original `use-auth-owa` feature flag for the new multi-variant flag required for our Posthog experiment
Development version of our experiment is here https://eu.posthog.com/project/124/experiments/21583
⚠️  We can merge this once we're happy with the experiment setup on production and all our events are in place.
Music year: [1992](https://www.youtube.com/watch?v=GLvohMXgcBo)
1. In an incognito session / after clearing cookies
2. Go to https://deploy-preview-2844--oak-web-application.netlify.thenational.academy/teachers/programmes/citizenship-secondary-ks3-l/units/citizenship-whats-it-all-about-e038/lessons/what-is-citizenship-c4t38d
2. Click on "Download resources"
3. The odds are 🎲 :
* 50% that you will be in the "with-login" group and asked to sign-in before …
=> LESQ-1084: point the lesson downloads at the experiment feature flag

src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx
Small fix to increase size of list items in curriculum explainers
Fixes `CUR-962`
Enable cycle 2
1. Go to https://deploy-preview-2899--oak-web-application.netlify.thenational.academy
2. Navigate to new curriculum explainers
3. Check for correct list styling
=> Fix list item styling in curriculum explainers

src/components/TeacherComponents/LessonOverviewHeader/LessonOverviewHeader.test.tsx, src/components/TeacherComponents/LessonOverviewHeader/LessonOverviewHeader.tsx, src/components/TeacherComponents/LessonOverviewHeaderDesktop/LessonOverviewHeaderDesktop.tsx, src/components/TeacherComponents/LessonOverviewHeaderMobile/LessonOverviewHeaderMobile.tsx, src/components/TeacherViews/LessonOverview/LessonOverview.view.tsx
Music year: 2010
- Adds isEYFS boolean to conditionally render share button on non EYFS pages
- KS1 - KS4 lesson pages still have share option
Fixes #LESQ-1116
1. Go to https://deploy-preview-2894--oak-web-application.netlify.thenational.academy
=> LESQ-1116: conditionally render share on eyfs pages

src/components/CurriculumComponents/CurriculumUnitDetailsAccordion/CurriculumUnitDetailsAccordion.tsx
Added `isFocusVisible` to `isFocused` condition so only applies for keyboard users
Fixes `CUR-980`
1. Go to https://deploy-preview-2900--oak-web-application.netlify.thenational.academy
2. Navigate to the curriculum visualiser modal
3. Click the accordions **should not** show focus state indicators
3. Using keyboard to select the accordions **should** show focus state indicators
=> Focus state fixes on curriculum modal accordion

src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Changed `:focus` -> `:focus-visible` for focus state in lot picker
Fixes `CUR-976`
1. Go to https://deploy-preview-2904--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. Check the focus state of lot picker when using mouse/keyboard
=> `:focus` -> `:focus-visible` for focus state in lot picker

src/components/TeacherComponents/helpers/downloadAndShareHelpers/fetchHubspotContactDetails.test.ts, src/components/TeacherComponents/helpers/downloadAndShareHelpers/fetchHubspotContactDetails.ts
Fixes #
Users not being able to download when signing up with an email that was not already a Hubspot contact.
1. Go to https://deploy-preview-2906--oak-web-application.netlify.thenational.academy
=> fix: missing Hubpost contacts throwing errors on download page

percy.snapshot.list.js, src/__tests__/__helpers__/mockUser.ts, src/components/TeacherComponents/ResourcePageLayout/ResourcePageLayout.test.tsx, src/components/TeacherComponents/ResourcePageLayout/ResourcePageLayout.tsx, src/components/TeacherComponents/TermsAgreementForm/TermsAgreementForm.test.tsx, src/components/TeacherComponents/TermsAgreementForm/TermsAgreementForm.tsx, src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormState.tsx, src/components/TeacherComponents/hooks/useOnboardingStatus.test.ts, src/components/TeacherComponents/hooks/useOnboardingStatus.ts, src/components/TeacherViews/LessonDownloads.view.tsx, src/components/TeacherViews/LessonShare/LessonShare.view.tsx
Music year: 1969
Fixes 
* Flicker of the "Your details" section appearing when logged in
* This was caused by the initial delay between the page rendering and Clerk loading.
* Annoyingly this sort of loading experience is unavoidable with client side personalisation.
1. With the [teacher-download-auth](https://eu.posthog.com/project/124/feature_flags/35482) feature flag set to "with-login" and while logged in
2. Go to https://deploy-preview-2902--oak-web-application.netlify.thenational.academy/teachers/programmes/computing-secondary-ks3-l/units/impact-of-technology-collaborating-online-respectfully-35d0/lessons/account-security-68rkee/downloads?preselected=all
3. Reload the page
4. You should see a slight delay (and potentially a loading spinner) before the download options appear
5. …
=> fix(LESQ-1115): remove the flicker of the "your details" section

src/utils/getValidSubjectIconName.ts
Music year: 1987
- don't report errors for canonical pages with null subjects
- this happens when a lesson is in multiple subjects, eg `To explore fronted adverbials` is in `english` and `english-grammar`
- we display a fallback icon 'books'
- it's not helpful to receive these errors as they tell us nothing new and clog up the errors channel
1. Go to https://deploy-preview-2910--oak-web-application.netlify.thenational.academy/teachers/lessons/to-explore-fronted-adverbials-71h64t
3. You should see no `Invalid icon name provided to OakIcon` error in the console
4. You should see the 'books' icon in place of a subject icon
=> fix: don't report errors for canonical pages with null subjects [LESQ-1121]

src/browser-lib/hubspot/forms/getHubspotFormPayload.test.ts, src/browser-lib/hubspot/forms/getHubspotFormPayloads.ts, src/components/TeacherComponents/OnboardingForm/onboardingActions/collectOnboardingTrackingProps.ts, src/components/TeacherComponents/helpers/downloadAndShareHelpers/getFormattedDetailsForTracking.tsx
Music year: 2010
Fixes
* Northern Irish URN (IRN) being truncated to 3 numbers when submitted to Hubspot
1. Go to https://deploy-preview-2920--owa-storybook.netlify.app/onboarding
2. Follow the teacher onboarding journey
3. Select a Northern Irish school from the picker
4. Complete onboarding
5. Check the Hubspot form request/contact in Hubspot
6. The URN should be in the format `XXX-XXXX`
=> fix(LESQ-1138): send the correct URN for NI schools to hubspot

src/browser-lib/hubspot/forms/getHubspotFormPayloads.ts, src/components/SharedComponents/FieldError/FieldError.tsx, src/components/TeacherComponents/LessonOverviewHeaderDownloadAllButton/LessonOverviewHeaderDownloadAllButton.tsx, src/components/TeacherComponents/OnboardingForm/OnboardingForm.schema.test.ts, src/components/TeacherComponents/OnboardingForm/OnboardingForm.schema.ts, src/components/TeacherComponents/OnboardingForm/OnboardingForm.tsx, src/components/TeacherViews/Onboarding/HowCanOakSupport/HowCanOakSupport.test.tsx, src/components/TeacherViews/Onboarding/HowCanOakSupport/HowCanOakSupport.view.tsx, src/components/TeacherViews/Onboarding/SchoolSelection/SchoolSelection.test.tsx
Fixes
* Download button asking users to Sign in when they have signed in but have not onboarded
* Validation when clicking "Continue" or "Skip" on the "How can Oak support you" step of onboarding
1. Go to https://deploy-preview-2917--oak-web-application.netlify.thenational.academy/onboarding
2. Click on take the teacher journey through onboarding
3. On the "How can Oak support you" step
4. Don't select any options
5. Click "Continue"
6. You should see a validation error
7. Select some options
8. Click "Skip"
9. The form should submit
10. `how_can_oak_support_you_` should be omitted from the form sent to Hubspot
1. Sign in as a user who has not onboarded in OWA (`owa.isOnboarded` is not `true` in Clerk)
2. Go to …
=> LESQ-1117: onboarding login fixes

src/components/PupilViews/PupilQuiz/PupilQuiz.view.tsx
Music year: 1959
add aria-described by to "check" button tooltip
Fixes #
1. Go to https://deploy-preview-2957--oak-web-application.netlify.thenational.academy
2. Click on pupil quiz; tab to and select "check" with a screen reader
3. You should hear the toolti text read out when it pops up
{screenshots}
{screenshots}
=> feat(submit): make checkout tooltip accessible

src/node-lib/sanity-graphql/generated/sdk.ts, src/node-lib/sanity-graphql/queries/curriculumOverview.gql, src/pages/api/curriculum-downloads/index.ts, src/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].tsx
Music year: 2017
- Changed GQL query to search by title instead of slug (no slug available in sanity)
- Changed query to look for equality instead of matching
PE and RE had switched explainers in prod due to fuzzy matching during querying. Hadn't had the issue before as most subjects are single words and not phrases
1. Go to https://deploy-preview-2966--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Click on Physical education primary/secondary
3. You should see the correct explainer
4. Same for RE
=> [CUR-1031] fix: update sanity query for equality of subject title

src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx
Add full stop after each item of content guidance (unless it already has a full stop which is sometimes the case then only add a space to it).
Fixes [PUPIL-1067](https://www.notion.so/oaknationalacademy/Content-guidance-rendering-lesson-overview-page-10026cc4e1b18028a154da30451ca249)
1. Navigate to a lesson with content guidance
2. Content guidance block of text with should have full stop after each line of content guidance.
Check this lessons:
- https://deploy-preview-2974--oak-web-application.netlify.app/pupils/programmes/drama-primary-year-3-l/units/stories-shared-across-the-world-2d56/lessons/dragons-c8v3cc/overview (content guidance item already has a full stop coming from database)
- https://deploy-preview-2974--oak-web-application.netlify.thenational.academy/pupils/programmes/englis …
=> fix: add full stop after each item of content guidance

src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersMobile.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/helpers.ts
Fix for selected year in highlight threads mobile (curric visualiser)
Fixes `CUR-1033`
1. Go to https://deploy-preview-2967--oak-web-application.netlify.thenational.academy
2. Navigate to mobile filters, check counts are correct
=> Fix for selected year in highlight threads mobile (curric visualiser)

src/components/PupilComponents/QuizResultInner/QuizResultInner.tsx, src/components/PupilComponents/QuizResultQuestionStem/QuizResultQuestionStem.stories.tsx, src/components/PupilComponents/QuizResultQuestionStem/QuizResultQuestionStem.test.tsx, src/components/PupilComponents/QuizResultQuestionStem/QuizResultQuestionStem.tsx, src/components/PupilComponents/QuizResults/QuizResults.tsx, src/components/PupilViews/PupilResults/PupilResults.view.tsx
Fix text in quiz results so it is not marked incorrectly as another question (remove numbering, right/wrong icon and '
Question hint used - false' text).
Fixed in:
- lesson review quiz results
- printable results
Fixes [#PUPIL-1039](https://www.notion.so/oaknationalacademy/Lesson-Review-quiz-results-explanatory-text-marked-as-incorrect-10b26cc4e1b1802c84d2cb820389734b)
1. Go to https://deploy-preview-2971--oak-web-application.netlify.thenational.academy/pupils/lessons/talk-about-school-life-part-13-6hj34t/overview
2. Complete the quiz
3. You should see explanatory text not having question related styling, numbering of the questions should not include explanatory text in it (it did before)
screenshot attached to the issue
=> fix: remove numbering from hint text in quiz results

src/components/PupilComponents/QuizCorrectAnswers/QuizCorrectAnswers.test.tsx, src/components/PupilComponents/QuizCorrectAnswers/QuizCorrectAnswers.tsx, src/components/TeacherComponents/QuizQuestionsListItem/QuizQuestionsListItem.tsx
Remove text feedback for image MCQs 
Fixes [PUPIL-411](https://www.notion.so/oaknationalacademy/No-useful-text-feedback-for-image-MCQs-b5d420c0b8cc4ebb9df09b2e83a774ea)
1. Go to https://deploy-preview-2979--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-8/units/graphical-representations-of-data/lessons/constructing-bar-charts-by-utilising-technology/starter-quiz
2. Go to question 5
3. You should see 'Almost correct' feedback for one correct answer or 'Incorrect feedback' for no correct answers but the text listing correct answers (ie. Correct answers: xxxx) should not be visible
=> fix: remove text feedback for image mcqs

src/browser-lib/mathjax/MathJaxProvider.tsx, src/browser-lib/mathjax/MathJaxWrap.tsx, src/components/PupilComponents/QuizMCQMultiAnswer/QuizMCQMultiAnswer.tsx, src/components/PupilComponents/QuizResultMCQ/QuizResultMCQ.tsx
Fix unicode Celcius error
Fixes [PUPIL-807](https://www.notion.so/oaknationalacademy/Mathjax-unicode-error-when-displaying-Celsius-07376ff72ce64cdcb5fde46df86eb5b2)
1. Go to https://deploy-preview-2986--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-7/units/comparing-and-ordering-fractions-and-decimals-positive-and-negative/lessons/ordering-negative-integers/exit-quiz
3. Go to question 2 of the exit quiz
4. Celcius symbol should be displayed correctly
=> PUPIL-807 unicode celcius error

src/components/SharedComponents/VideoPlayer/VideoPlayer.tsx
Added 0.5x and 0.7x speed to MuxPlayer (ticket mentioned only 0.5x but it is VERY slow)
Fixes [PUPIL-852](https://www.notion.so/oaknationalacademy/Offer-MUX-video-speed-1x-579808e7d7dc4432ba5cf8ec77f27dc0)
1. Go to any page in the app with video in it
2. Video player should now offer 0.5x and 0.7x playback speeds
=> feat: offer lower speed in MuxPlayer

src/pages-helpers/curriculum/docx/builder/5_subjectExplainer.ts, src/pages-helpers/curriculum/docx/builder/__snapshots__/5_subjectExplainer.test.ts.snap
Changes paragraph content pulled in from sanity to have the "Arial" (rather than "Aptos") typeface.
Fixes `CUR-1029`
1. Go to https://deploy-preview-2990--oak-web-application.netlify.thenational.academy
2. Navigate to curriculum visualiser and download a document
3. Check the explainer content if rendering with Arial
=> Explainer font incorrectly using Aptos

src/pages-helpers/curriculum/docx/builder/2_tableOfContents.ts, src/pages-helpers/curriculum/docx/builder/5_subjectExplainer.ts, src/pages-helpers/curriculum/docx/builder/__snapshots__/2_tableOfContents.test.ts.snap, src/pages-helpers/curriculum/docx/builder/__snapshots__/5_subjectExplainer.test.ts.snap
Rename 'overview' to 'explainer' in curriculum downloads (docx)
Fixes `CUR-1052`
1. Go to https://deploy-preview-2995--oak-web-application.netlify.thenational.academy
2. Go to curriculum downloads and download a document
3. You should see 'explainer' rather than 'overview' as both the title and contents entry, for the explainers
=> Rename 'overview' to 'explainer' in curriculum downloads (docx)

src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.test.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx
Don’t show ‘All exam boards (KS4)’ when there is no KS4 in sequence
Fixes `CUR-1049`
1. Go to https://deploy-preview-2993--oak-web-application.netlify.thenational.academy
2. Go to the curriculum visualiser 
3. Secondary phases without KS4 shouldn't contain "All exam boards (KS4)' text
=> Don’t show ‘All exam boards (KS4)’ when there is no KS4 in sequence

src/pages-helpers/curriculum/docx/builder/1_frontCover.test.ts, src/pages-helpers/curriculum/docx/builder/1_frontCover.ts, src/pages-helpers/curriculum/docx/builder/helper.test.ts, src/pages-helpers/curriculum/docx/builder/helper.ts
Fix to use new subjects icon URLs for curriculum downloads (docx)
Fixes `CUR-1110`
1. Go to https://deploy-preview-3010--oak-web-application.netlify.thenational.academy
2. Navigate to the curriculum visualiser
2. Download a document for each subject and check the subject icon appears correctly
=> Fix to use new icon URLs for curriculum downloads

src/components/TeacherComponents/DownloadConfirmation/DownloadConfirmation.tsx, src/components/TeacherComponents/HeaderListing/HeaderListing.tsx, src/components/TeacherComponents/LessonOverviewHeader/LessonOverviewHeader.tsx, src/components/TeacherComponents/LessonOverviewHeaderDesktop/LessonOverviewHeaderDesktop.tsx, src/components/TeacherComponents/LessonOverviewHeaderMobile/LessonOverviewHeaderMobile.tsx, src/components/TeacherComponents/TeacherShareButton/TeacherShareButton.test.tsx, src/components/TeacherComponents/TeacherShareButton/TeacherShareButton.tsx, src/components/TeacherViews/LessonOverview/LessonOverview.view.tsx, src/pages-helpers/teacher/share-experiments/createShareId.ts, src/pages-helpers/teacher/share-experiments/getUpdatedUrl.ts, src/pages-helpers/teacher/share-experiments/useShareExperiment.ts, src/pages-helpers/teacher/share-experiments/useShareExperiments.test.ts, src/pages/teachers/lessons/[lessonSlug].tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx
**When** I press a share button,
**I want to copy the url to the clipboard**
**So that I can share the url with another user**.
See [[Share tracking plan](https://www.notion.so/Share-tracking-plan-13f26cc4e1b180379bf6c664fd120a77?pvs=21)](https://www.notion.so/Share-tracking-plan-13f26cc4e1b180379bf6c664fd120a77?pvs=21) 
- Send share-id and page-variant to posthog when sent
1. Go to https://deploy-preview-3016--oak-web-application.netlify.thenational.academy
2. Click on https://deploy-preview-3016--oak-web-application.netlify.thenational.academy/teachers/lessons/transverse-waves
3. You should see the share button appear
4. click on the button
5. it should fire an activation event
6. it should say copied to clipboard and the text on the clipboard should be a link 
7. paste the link in …
=> Feat/pupil 1100/add share buttons

src/config/localStorageSchemas.ts, src/pages-helpers/teacher/share-experiments/createShareId.test.ts, src/pages-helpers/teacher/share-experiments/createShareId.ts, src/pages-helpers/teacher/share-experiments/getUpdatedUrl.test.ts, src/pages-helpers/teacher/share-experiments/getUpdatedUrl.ts, src/pages-helpers/teacher/share-experiments/useShareExperiment.ts, src/pages-helpers/teacher/share-experiments/useShareExperiments.test.ts, src/utils/localstorage.ts
Switching from cookies to local storage to avoid hard limits and performance overheads
Modify 
src/pages-helpers/teacher/share-experiments/createShareId.ts
to use local storage instead of cookies
update all tests relying on cookie mocks
How to test
Go to https://deploy-preview-3018--owa-storybook.netlify.app/ and accept cookies and open the console
Go to  https://deploy-preview-3018--owa-storybook.netlify.app/teachers/lessons/atomic-structure-very-small-electron-mass
See that TeacherShareInitiated is sent
Copy the url into a different browser window (eg. a different google instance or safari)
See that both TeacherShareIniated and TeacherShareConverted are sent (accept cookies)
See that the url in the second browser is modified to a different id
Repeat the experiment with same urls and see …
=> Fix/pupil 1119/share cookies to local storage

src/components/CurriculumComponents/CurriculumVisualiserLayout/CurriculumVisualiserLayout.tsx
Fixes the width of the curriculum sidebar
Fixes `CUR-1143`
1. Go to https://deploy-preview-3060--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. Navigate to the curric sequences 
3. Check width of the sidebar stays consistent
=> Make curric filter sidebar fixed width

src/pages/teachers/curriculum/index.tsx
Music year: 1989
- Update metadata title and description as per https://www.notion.so/oaknationalacademy/Meta-Descriptions-clean-up-9dc8d8b3bb664a56b66222d640cdf549?pvs=4
1. Go to https://deploy-preview-3063--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. The page title should be: `Free curriculum plans aligned with National Curriculum  | Oak National Academy`
3. The metadata description should be: `Discover our free curriculum plans across subjects from KS1 to KS4, all high-quality, fully-sequenced and aligned with the national curriculum.`
=> [CUR-885] Update curriculum homepage metadata

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].test.tsx, src/components/TeacherComponents/DownloadConfirmation/DownloadConfirmation.tsx, src/pages-helpers/teacher/share-experiments/useShareExperiment.ts, src/pages-helpers/teacher/share-experiments/useShareExperiments.test.ts, src/pages/teachers/lessons/[lessonSlug].tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].tsx
**When I view a lesson**
I want a button to share it with a colleague
So that I can advocate for oak
- remove flag fetching code from useShareExperiment
- remove the flag condition from useShareExperiment
- remove flag condition for displaying share buttons
- remove the url updates
**OR** 
- Add a canonical link to the headers of the effected pages
- remove flag fetching code from useShareExperiment
- remove the flag condition from useShareExperiment
- remove flag condition for displaying share buttons
1. Go to 
https://deploy-preview-3066--oak-web-application.netlify.thenational.academy/teachers/lessons/transverse-waves
https://deploy-preview-3066--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-foundation-aqa/units/measuring-waves/lesson …
=> feat: remove feature flag restriction from share buttons and tracking

src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Fixes invalid causing close button to be visually clipped (hidden) in the UI 
Fixes `CUR-1144`
1. Go to https://deploy-preview-3067--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Check subject phase picker breakpoints for visual errors (see  `CUR-1144` for particular issue addressed)
=> Incorrect breakpoint in curric picker

src/pages-helpers/curriculum/docx/builder/5_subjectExplainer.ts, src/pages-helpers/curriculum/docx/builder/__snapshots__/5_subjectExplainer.test.ts.snap
Fixes for docx validation errors and also visual issues with level 6 headings.
Fixes `CUR-1153`
1. Go to https://deploy-preview-3070--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. From the picker "English secondary (AQA)"
3. Download docment
4. Level 6 heading should be correctly spaced.
Before
After
=> Invalid value for `w:beforeAutospacing` in docx

src/pages-helpers/curriculum/docx/builder/1_frontCover.ts, src/pages-helpers/curriculum/docx/builder/helper.test.ts, src/pages-helpers/curriculum/docx/builder/helper.ts
Added `subjectFromUnits` method to pull title from data rather than generating from the slug
Fixes `CUR-797`
1. Go to https://deploy-preview-3068--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. Generate a docx with and without child subjects
3. Check for regressions in the cover page where the child subject is displayed.
=> Added `subjectFromUnits` method to pull title from data

package-lock.json, package.json, src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug].test.tsx, src/components/CurriculumComponents/OakComponentsKitchen/Alert/__snapshots__/Alert.test.tsx.snap
- Updated `oak-components` version to see versioned icons
Fixes [PUPIL-1154](https://www.notion.so/oaknationalacademy/Use-versioned-versions-of-icons-16026cc4e1b180078e36d2bdede46e42)
1. Go to https://deploy-preview-3084--oak-web-application.netlify.thenational.academy
2. Scan through pages and check that icons and backgrounds in lesson and unit views render without changes
=> PUPIL-1154 Update oak-components version to see versioned icons

src/components/PupilViews/PupilProgrammeListing/PupilProgrammeListing.view.tsx
PE. is released with a single pathway GCSE at KS4. The pupil programme listing operated on the assumption of always being multiple or no pathways
Fixes #
- adjust the condition to accept just a single factor for any programme factors
1. Go to https://deploy-preview-3101--oak-web-application.netlify.thenational.academy/pupils/programmes/physical-education-secondary-year-10/options
2. You should be prompted to choose a pathway and then an examboard
3. you should be able to successfully access a unit listing page
4. please check for any regressions around programme factors in other subjects - eg. combined science, maths, english
=> hotfix: allow singular programme factors in ui

src/components/CurriculumComponents/Banners/__snapshots__/Banners.test.tsx.snap, src/components/CurriculumComponents/CurriculumDownloadView/index.tsx, src/components/CurriculumComponents/CurriculumDownloads/CurriculumDownloads.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersDesktop.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersMobile.tsx, src/components/CurriculumComponents/HomePageBanner/HomePageBanner.tsx, src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx, src/components/CurriculumComponents/UnitModal/UnitModal.tsx, src/components/CurriculumComponents/UnitsTabSidebar/UnitsTabSidebar.tsx
Easy updates for `<Box/>` to `<OakBox/>` in `./src/components/CurriculumComponents/`
Regression test of curriculum pages
Most of the updates are **no-ops** except for small changes to the padding in the curriculum header.  
=> Simple updates for `<Box/>` to <OakBox/>` in curriculum components

src/pages/blog/[blogSlug].tsx, src/pages/develop-your-curriculum.tsx, src/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].tsx, src/pages/teachers/curriculum/index.tsx, src/pages/teachers/curriculum/previous-downloads.tsx, src/pages/webinars/[webinarSlug].tsx
No-op updates for `<Box/>` to `<OakBox>` in `./src/pages` 
Regression test
- `/blog/[slug]`
- `/develop-your-curriculum` (~looks like this only exists locally and has a redirect on production, see <https://www.thenational.academy/develop-your-curriculum>~ created a ticket in curric squad to remove this page)
- `/teachers/curriculum/[subjectPhaseSlug]/[tab]`
- `/teachers/curriculum/previous-downloads`
- `/webinars/[webinarSlug]`
=> Easy to update `<Box/>` to `<OakBox>` in `./src/pages` 

src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersMobile.tsx, src/components/CurriculumComponents/OakComponentsKitchen/AcceptTerms/index.tsx, src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx, src/components/CurriculumComponents/SuccessMessage/index.tsx, src/components/CurriculumComponents/UnitsTabSidebar/UnitsTabSidebar.tsx, src/styles/utils/dropShadow.ts
Update curriculum components to use `<OakBox/>` rather than `<Box/>`
See screenshot below for changes
Increased size either side of bullet in "highlight a thread" also the "Units that make up" get pushed down a little `40px` to `48px` (before/after)
Overview pages pushed down slightly in `/teachers/curriculum/art-primary/overview`  (before/after)
Success message padding slightly changes (before/after)
Very minor pixel change to the "year 1", "year 2", "year 3" header over in
=> More awkward to update `<Box/>` to `<OakBox/>` in curriculum components

package-lock.json, package.json, src/pages-helpers/curriculum/docx/builder/10_threadsDetail.ts, src/pages-helpers/curriculum/docx/builder/11_backCover.ts, src/pages-helpers/curriculum/docx/builder/4_threadsExplainer.ts, src/pages-helpers/curriculum/docx/builder/5_subjectExplainer.ts, src/pages-helpers/curriculum/docx/builder/8_units/8_units.ts, src/pages-helpers/curriculum/docx/builder/8_units/unit_detail.ts
Revert `@prettier/plugin-xml` to fix linting of embedded XML via `safeXml` statements
Fixes `CUR-1177`
This shouldn't have changed anything , however some code was touched in docx, so worth testing there
1. Go to https://deploy-preview-3139--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. Download a few documents and check they validate correctly via https://marketplace.visualstudio.com/items?itemName=mikeebowen.ooxml-validator-vscode
=> Revert `@prettier/plugin-xml` to fix linting of embedded XML

src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.tsx
Change the colour of threads tag in curriculum unit modal from `grey` to `lavender`
Fixes `CUR-1200`
1. Go to https://deploy-preview-3144--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Go to the visualiser and select a unit 
3. Check threads in the unit modal are the correct colour (as per designs)
=> Change colour of threads tag in curriculum unit modal

src/components/TeacherComponents/UnitDownloadButton/UnitDownloadButton.test.tsx, src/components/TeacherComponents/UnitDownloadButton/UnitDownloadButton.tsx
Music year: 1979
- removes the feature flag `teacher-unit-downloads`
- promote the download button to appear for all users
- promote the copy from option-a
1. Go to https://deploy-preview-3148--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-higher/units/algebraic-manipulation/lessons
3. You should see a unit download button
4. When signed out: it should say 'Download unit'
5. Clicking should take you through sign in/up and redirect back to the lesson listing page
6. When signed in: it should say Download (.zip ~size)
7. Clicking it should initiate download for the unit zip file
depending on which cohort for the feature flag, you may see no download button
you should always see the …
=> feat: promote unit downloads [LESQ-1199]

src/pages-helpers/teacher/subject-listing-page/getCombinedSubjects.tsx
Display pathways in alphabetical order so it's always consistent, regardless which order comes form the backend
Fixes [CTC-145](https://www.notion.so/oaknationalacademy/Pathways-Bug-Computing-Pathway-Cards-Not-in-Order-18b26cc4e1b1802b904be2a7cc517a98)
1. Go to https://deploy-preview-3164--oak-web-application.netlify.thenational.academy
2. Go to KS 4 subject listing page
3. Check if the pathways are displayed in the same order for all subjects with pathways
=> CTC-145 Display pathways in alphabetical order

src/components/CurriculumComponents/UnitModal/UnitModal.test.tsx, src/components/CurriculumComponents/UnitModal/UnitModal.tsx
Music year: 1951
- Added optionality title to unit modal
- Added test which tests for presence of optionality title the case of optional unit
Fixes #[1201](https://www.notion.so/oaknationalacademy/Add-optionality-title-to-unit-modal-18326cc4e1b18098a800fa8648f64ed8?pvs=4)
1. Go to https://deploy-preview-3169--oak-web-application.netlify.thenational.academy
2. Visit a subject with optional units such as English (Secondary, AQA)
3. Find a unit  with multiple options and click it
4. Select one of the options
5. In the unit detail check to see that optionality title is present
- [] Does this PR update a package with a breaking change
=> feat: add optionality title to unit modal

package-lock.json, package.json, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFilters.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersDesktop.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersMobile.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/helpers.ts, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx, src/components/TeacherComponents/LessonOverviewMediaClips/LessonOverviewClipWithThumbnail.tsx, src/utils/curriculum/getNumberOfSelectedUnits.ts
Music year: 1976
- Uses the new OakRadioAsButton and OakRadioGroup components to implement radio button semantics for a group of buttons
- Remove FieldsetLegend component and use OakHeading in its place
Fixes #[1172](https://www.notion.so/oaknationalacademy/Restyle-year-groups-in-new-curriculum-filtering-to-match-new-designs-17526cc4e1b18026a9bdc4567043b3fd?pvs=4)
=> Add new year group filter design

src/components/TeacherComponents/DesktopUnitFilters/DesktopUnitFilters.stories.tsx, src/components/TeacherComponents/DesktopUnitFilters/DesktopUnitFilters.tsx, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.schema.ts, src/pages/teachers/programmes/[programmeSlug]/units.tsx
Music year: 2022
- Remove conditional rendering of header row on mobile where the filter button lives
- Refactor unit listing page layout
Fixes https://www.notion.so/oaknationalacademy/Filter-button-disappears-on-mobile-13e26cc4e1b180a19183dcec5e00278c?pvs=4
1. Go to https://deploy-preview-3175--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-aqa/units?category=literature&learning-theme=developing-fiction-writing
2. Open the filter menu on mobile / tablet view and apply filters until you arrive at 0 results 
3. You should see the filter button and a heading, either `Units (0)` or tabs for tiers
4. You should be able to go in an adjust the filters
5. Desktop view should be unchanged
6. Navigating by keyboard on desktop should work the same with …
=> Fix/lesq 1172/unit filter button mobile [LESQ-1172]

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersDesktop.tsx, src/components/CurriculumComponents/CurriculumVisualiserFilters/helpers.ts, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
Fixes thread highlighting counts in new filter UI in the curriculum visualiser. 
Fixes `CUR-1183`
2. Test thread counts are correct for curriculum filter state
=> Thread highlighting in new filters for curriculum

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/helpers/index.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructLessonDownloads.test.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/constructLessonDownloads.ts, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.gql, src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.query.ts
Music year: 2015
- change the downloads query to get all lessons for unit and programme
- this is how it used to work before MVs were refactored so it's already set up to find the current lesson and (up to) the next three in sequence 
Fixes #
[Next lessons missing on downloads confirmation page](https://www.notion.so/oaknationalacademy/The-downloads-confirmation-page-next-lessons-in-sequence-has-disappeared-16126cc4e1b18029ab45d68e13578af5?pvs=4)
1. Go to https://deploy-preview-3176--oak-web-application.netlify.thenational.academy/teachers/programmes/chemistry-secondary-ks4-foundation-aqa/units/atomic-structure-and-the-periodic-table/lessons/atomic-structure-very-small-electron-mass/downloads?preselected=all
2. Click on download
3. You should see next lessons in the sequence on the …
=> fix: next lessons on download confirmation [LESQ-1228]

src/components/TeacherComponents/UnitList/UnitList.tsx
Music year: 1986
- use subjectTitle for unit list header instead of subjectSlug
Fixes #
Slugs showing for multi-word subjects
1. Go to https://deploy-preview-3180--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-higher-ocr/units
3. You should see the units header has no hyphen, and is in sentence case `Combined science units`
4. The same should be true for /teachers/programmes/physical-education-secondary-ks4-gcse-aqa/units `Physical education units`
5. Other subjects should be unaffected
=> fix: use subject title instead of slug for header [LESQ-1269]

package-lock.json, package.json, src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersDesktop.tsx, src/utils/getValidSubjectCategoryIconById.ts, src/utils/getValidSubjectIconName.ts
Music year: 1966
- Add HR elements between each filter section
- @rightsaidjames Note that the custom HR component has been removed from the codebase in our attempt to standardise components and try to use components from the component library where possible. As such instead of the `Hr` component being used I had to use `OakHandDrawnHr`. Due to this the divider has a slightly different style and could only take specific margin-top and bottom spacing values – which therefore meant that it diverges very slightly in look from the Figma designs. I talked with @HelenHarlow about this and she was fine with the changes.
Note that there seems to be a slight bug with the filter at the moment, where subject categories and exam subjects aren't displayed at the same time when all is selected (they're …
=> Restyle subject category filters

package-lock.json, package.json, src/pages-helpers/curriculum/docx/__snapshots__/docx.test.ts.snap, src/pages-helpers/curriculum/docx/docx.test.ts
Improved docx test performance from around **~21s** down to **~1s**. I did this by replacing [json-diff](https://www.npmjs.com/package/json-diff) with [microdiff](https://github.com/AsyncBanana/microdiff)
Before
```
PASS  src/pages-helpers/curriculum/docx/docx.test.ts (19.656 s)
docx
✓ cmToEmu
✓ emuToCm
✓ lineHeight
✓ pointToDxa
✓ cmToTwip
✓ wrapInLinkTo
✓ wrapInLinkToBookmark
✓ wrapInBookmarkPoint
✓ getFooterFilenameFromContent
✓ degreeToOoxmlDegree
checkWithinElement
✓ return true if check passes at least once (5 ms)
✓ return false if check always fails (1 ms)
mapOverElements
✓ should not mutate if no changes
✓ should mutate changes made (1 ms)
generateEmptyDocx
✓ test (23 ms)
insertImages
✓ test (3382 ms)
insertLinks
✓ test (3344 ms)
insertNumbering
✓ test (6209 ms)
appendBodyElements …
```
=> Improve docx test performance

.github/workflows/code_checks.yml
This should hopefully speed up CI a little
We're just moving these checks off into their own job and running checks(lint, check types) and tests(test,sonar) in parallel. This should save us ~1min on the test run 🤞
=> Parallelize CI a little more

src/components/CurriculumComponents/CurriculumVisualiserFilters/CurriculumVisualiserFiltersDesktop.tsx, src/pages-helpers/curriculum/docx/tab-helpers.ts, src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts, src/utils/curriculum/keystage.test.ts, src/utils/curriculum/keystage.ts, src/utils/curriculum/types.ts
Adds ks3/ks4 suffixes where required in new curriculum filter sidebar.  
> [!NOTE]
> Builds on PR #3193
Fixes `CUR-1191`
2. Test new ks3/ks4 suffixes work as intended.
=> Subject specific grouping labels (ks3/ks4)

src/utils/curriculum/features.ts, src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts
Fixed subject specific filter option ordering, for the new curriculum filtering UI
Fixes `CUR-1182`
1. Go to `/teachers/curriculum`
2. Check filter ordering is correct as per `CUR-1182`
=> Subject specific ordering for new curric filter

src/components/SharedComponents/VideoPlayer/getDuration.test.ts, src/components/SharedComponents/VideoPlayer/getDuration.ts
Don't round video duration to zero - round to two coma spaces instead
Fixes [CTC-142](https://www.notion.so/oaknationalacademy/Media-Page-Bug-Clips-less-than-a-second-do-not-play-18a26cc4e1b18093900ae93894a689ee)
1. Go to https://deploy-preview-3207--oak-web-application.netlify.thenational.academy/teachers/programmes/spanish-secondary-ks4-edexcel/units/media-and-technology-actores-y-peliculas/lessons/dos-actores-famosos-ar-3rd-person-singular-and-plural-preterite/media
2. The videos under 1 second should play
=> CTC-142 Don't round video duration to zero

package-lock.json, package.json, src/components/TeacherComponents/TeacherNotesModal/TeacherNotesModal.tsx
Final tweaks to teacher notes
latest design
https://www.figma.com/design/OEMJMj2akckSSxkbumdJAD/%F0%9F%A7%AA-Lesson-Delivery-Squad-Experiments?node-id=4591-49961&m=dev
revised title:
”Add a teacher note to the page and share the link with your colleague.”
- ensure that you have the teacher notes feature flag enabled using the posthog toolbar
- goto a lesson eg . https://deploy-preview-3213--oak-web-application.netlify.app/teachers/lessons/transverse-waves
- there should now be a warning which links to the T&Cs 
- the title should now be changed
=> Feat/pupil 1185/deploy teacher notes

src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts
Added `buildPageTitle` method with updated title rules for curriculum visualisers `<h1/>` tag.
Fixes `CUR-1204`
1. Go to https://deploy-preview-3214--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Check new title rules for `<h1/>`
=> Added `buildPageTitle` with update title rules for curric visualiser

src/__tests__/__helpers__/renderWithProviders.tsx, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.test.tsx, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
On from #3217 I've fixed the performance of some slow tests
It turns out that two things were causing slow downs, firstly whenever an error gets logged it needs to calculate a stacktrace. Fixing this seems to speed up by ~30-50ms
Secondly reducing the amount of providers included in tests with the following new function was a minor small bump.
```ts
const render = renderWithProvidersByName(["oakTheme", "theme"]);
```
Results are about 200ms saved on this test file alone (adds up quickly)
Just added a missing key to the SubjectPhasePicker
1. Go to https://deploy-preview-3219--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Check phase picker works as intended
=> Speed up tests by adding missing key and minimising providers

src/utils/curriculum/getNumberOfSelectedUnits.test.ts, src/utils/curriculum/getNumberOfSelectedUnits.ts
Fixes "year count" in new curriculum filtering branch.
Fixes `CUR-1169`
2. Check hidden aria "units shown" text is correct when filters change
=> Fixes year count in new curriculum filtering

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.tsx
Fixes for various data issues in the new filtering branch.
I turns out when I told @assadk88 to ah yeah just remove that code in https://github.com/oaknational/Oak-Web-Application/commit/be20ecfcf35da30582bbf5b1ecd7403808936dd3#diff-f5088875e98c3f1cda69461182f7cb387c881b0fe15b374868d107ef82132948L75-L172 yeah we kind of needed that code.
Fixes `CUR-1291`
1. Go to {owa_deployment_url}/teachers/curriculum/science-secondary-aqa/units
2. Check data is correct
3. Check for regressions
=> Fixes for new curriculum filtering data issues

src/components/CurriculumComponents/CurricVisualiserMobileHeader/index.tsx
Removes the number of filters from mobile filter as shown in the below
Fixes `CUR-1169`
2. Go to the visualiser
3. Apply a filter in the mobile viewport
4. Check `(1)` is no longer preset
=> Remove filter number from mobile filter

src/fixtures/curriculum/filters/index.test.ts, src/fixtures/curriculum/filters/index.ts, src/fixtures/curriculum/yearData/index.test.ts, src/fixtures/curriculum/yearData/index.ts, src/utils/curriculum/filtering.test.ts
Added missing tests for `shouldDisplayFilter` in new curriculum filtering branch.
Also adds new fixture helpers `createYearData` and `createFilter`
No QA required just dev review only tests effected
=> Added missing tests for `shouldDisplayFilter` new curric filtering

src/components/CurriculumComponents/CurricVisualiserFiltersMobile/index.tsx, src/components/CurriculumComponents/OakComponentsKitchen/OakModalNew/__snapshots__/index.test.tsx.snap, src/components/CurriculumComponents/OakComponentsKitchen/OakModalNew/index.test.tsx, src/components/CurriculumComponents/OakComponentsKitchen/OakModalNew/index.tsx, src/hooks/usePrevious.ts
100% test coverage of new `<OakModalNew/>`
FYI: Will add tests for `usePrevious` in another PR as it's not strictly related
```
.../CurriculumComponents/OakComponentsKitchen/OakModalNew      |     100 |      100 |     100 |     100 | 
index.tsx                                                     |     100 |      100 |     100 |     100 | 
```
No QA required just dev review (only effects tests)
=> Added missing tests for `<OakModalNew/>` in curric filtering branch

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersChildSubjects.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.fixtures.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersThreads.tsx, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts, src/utils/curriculum/keystage.test.ts, src/utils/curriculum/keystage.ts
More code coverage for curric filtering
```
CurricFiltersChildSubjects.fixtures.tsx                                                       |     100 |      100 |     100 |     100 |                                                                          
CurricFiltersChildSubjects.tsx                                                                |     100 |      100 |     100 |     100 |                                                                          
CurricFiltersSubjectCategories.fixtures.tsx                                                   |     100 |      100 |     100 |     100 |                                                                          
CurricFiltersSubjectCategories.tsx                                                            |     100 |      100 | …
```
=> Curric filters more test coverage

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.test.tsx, src/__tests__/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/share.test.tsx, src/pages/teachers/lessons/[lessonSlug]/downloads.tsx, src/pages/teachers/lessons/[lessonSlug]/share.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/share.tsx
Add no index to download and share pages
Fixes [PUPIL-1262](https://www.notion.so/oaknationalacademy/OWA-add-noindex-to-all-downloads-share-pages-1b326cc4e1b18069a566dda2fac210d0)
1. Go to https://deploy-preview-3279--oak-web-application.netlify.thenational.academy
2. Check that download and share pages have `<meta name="robots" content="noindex,follow">` in the head
{screenshots}
{screenshots}
=> feat: add no index to download and share pages

src/utils/curriculum/getNumberOfSelectedUnits.test.ts, src/utils/curriculum/getNumberOfSelectedUnits.ts, src/utils/curriculum/isVisibleUnit.test.ts
Fixes for the unit count in hidden aria DOM node in the curriculum filters
Also small refactor to use `createFilter` helper
Fixes `CUR-1169`
2. Check the accessible highlighted/unit count is correct when different combinations of filtering options are applied
=> Fixes incorrect unit count in hidden aria DOM node

package-lock.json, package.json, src/utils/getValidSubjectCategoryIconById.ts
- Added RE subject category icons
Fixes #[1246](https://www.notion.so/oaknationalacademy/Add-missing-icons-to-oak-components-filtering-19d26cc4e1b1803692c2d8d2cf33fb06)
1. Naviate to RE Primary to https://deploy-preview-3283--oak-web-application.netlify.thenational.academy/teachers/curriculum/religious-education-primary/units
2. You should see the recently added subject category icons for Theology, Philosophy and Social Science
=> Add new RE subject category icons

src/components/CurriculumComponents/Banners/__snapshots__/Banners.test.tsx.snap, src/components/SharedComponents/Button/ButtonAsLink/ButtonAsLink.tsx, src/components/SharedComponents/Card/SummaryCard.tsx, src/components/SharedComponents/Circle/Circle.tsx, src/components/SharedComponents/SocialButtons/SocialButtons.tsx
Migrate away from `defaultProps` in the components
In a few component we previously used something like the following
```tsx
Circle.defaultProps = {
$alignItems: "center",
$justifyContent: "center",
$borderRadius: "50%",
};
```
We've changed that into
```tsx
const Circle: FC<CircleProps> = (props) => {
props = {
$alignItems: "center",
$justifyContent: "center",
$borderRadius: "50%",
...props,
};
// ...
}
```
Dev QA the following components are effected
- `ButtonAsLink`
- `SummaryCard`
- `SocialButtons`
- `Circle`
=> Migrate away from `defaultProps`

src/components/TeacherComponents/SearchResultsItem/SearchResultsItem.tsx
Fixes `styled-components` issue from report.
The issue is that styled components should only be defined at the top level 
Check that search renders correctly (pathname `/teachers/search?term=english`) and the tests pass
=> Extract out styled components from inside other components

src/context/Toast/useToastContext.test.ts
Mocks out `console.error` to prevent additional logging in CI.
Just dev review required.
=> Mock out error logging in expected error

src/components/PupilComponents/LessonEngineProvider/LessonEngineProvider.test.tsx
I believe this should always be calling
```diff
- result.current.completeActivity("intro")
+ result.current.completeActivity(section)
```
@benprotheroe can you confirm the logic in the test
=> Typo in test when calling `.completeActivity(...)`

src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/subjectListing/constructSubjectsFromUnitData.test.ts, src/node-lib/curriculum-api-2023/queries/subjectListing/constructSubjectsFromUnitData.ts, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.query.ts, src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.schema.ts
Music year: 1991
[Ticket here](https://www.notion.so/DB-changes-for-finance-to-be-displayed-as-non-curriculum-subject-1a026cc4e1b180d689a4cafb7e84a17e?pvs=8&n=github_linkback)
This PR adds the GraphQL and associated changes required to access subject features within the teachers and pupils unit listing views (**Note**: no visual changes).
1. Go to https://deploy-preview-3297--oak-web-application.netlify.thenational.academy
2. The site should operate normally
N/A
=> [PUPIL-1224] Adds the pf_subject features data to the FE

package-lock.json, package.json, src/__tests__/pages/pupils/programmes/[programmesSlug]/units.test.tsx, src/components/PupilViews/PupilUnitListing/PupilUnitListing.view.tsx, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.query.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.schema.ts, src/pages/pupils/programmes/[programmeSlug]/units.tsx
Music year: 2022
[Ticket here](https://www.notion.so/Overrides-for-cross-reference-of-finance-from-both-unit-listing-pages-1a026cc4e1b1803a8e01f002f16d910f?pvs=8&n=github_linkback)
This PR adds the schema and associated changes required to access related subjects from within the teachers and pupils unit listing views (**Note**: no visual changes).
1. Go to https://deploy-preview-3296--oak-web-application.netlify.thenational.academy
2. The site should operate normally
N/A
=> [PUPIL-1225] Adds the related subjects data to the FE from the overrides table

src/utils/curriculum/constants.ts, src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts, src/utils/curriculum/flags.test.ts
Initial branch of storing the curriculum filter in the URLs querystring
**Note**: This doesn't "build time" / "server side", render which is inline with other squads, for example you'll note that https://www.thenational.academy/teachers/programmes/art-primary-ks1/units?year=year-2&learning-theme=draw gets a flash of "initial state" prior to JavaScript kicking in.
Fixes `CUR-1294`
2. Check that filtering modifies the querystring in the correct way
3. Check that refreshing the browser, or opening the URL in a different browser restores the correct state
=> Store curric filter in the URLs querystring

src/components/TeacherComponents/UnitDownloadButton/UnitDownloadButton.tsx
Music year: 1962
- Fixes unit download button being taller than share button
Fixes LESQ-1265
1. Go to https://deploy-preview-3317--oak-web-application.netlify.thenational.academy
2. Go to lesson listing page (example: [https://deploy-preview-3317--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks3/units/lord-of-the-flies/lessons?sid-93727c=jdjn9KdJmp&sm=0&src=3](https://deploy-preview-3317--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks3/units/lord-of-the-flies/lessons?sid-93727c=jdjn9KdJmp&sm=0&src=3))
3. You should see unit download button with the same height as share button
=> fix: unit download button height

src/components/TeacherComponents/LessonOverviewMediaClips/LessonOverviewMediaClips.tsx, src/components/TeacherComponents/helpers/lessonHelpers/lesson.helpers.test.ts, src/components/TeacherComponents/helpers/lessonHelpers/lesson.helpers.ts, src/components/TeacherViews/LessonMedia/LessonMedia.view.tsx
-  Order media clips according to order in CAT
- Go to the correct clip when clicking on a learning cycle on the lesson overview page
Testing link:
https://deploy-preview-3325--oak-web-application.netlify.thenational.academy/teachers/lessons/what-is-it-naming-belongings-with-un-and-une
Fixes [PUPIL-1242](https://www.notion.so/oaknationalacademy/Media-clip-bugs-Lesson-media-page-some-clips-are-not-in-the-correct-order-19a26cc4e1b18050a2f8d2aa374fa067)
Also fixes [PUPIL-1252](https://www.notion.so/oaknationalacademy/Clicking-on-a-learning-cycle-on-the-lesson-page-always-displays-the-first-video-clip-18a26cc4e1b1808f98fed647d9b1ec76)
=> PUPIL-1242: order media clips according to order in CAT

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.test.tsx, src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersSubjectCategories.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersDesktop/index.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersDesktop/index.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersMobile/index.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersModal/index.stories.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersModal/index.test.tsx, src/components/CurriculumComponents/CurricVisualiserFiltersModal/index.tsx, src/components/CurriculumComponents/CurricVisualiserMobileHeader/index.stories.tsx, src/components/CurriculumComponents/CurricVisualiserMobileHeader/index.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx, src/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].tsx, src/utils/getValidSubjectCategoryIconById.test.ts, src/utils/getValidSubjectCategoryIconById.ts
Adds correct "all" icons for Science/RE in new filtering
Fixes `CUR-1333`
1. Go to {owa_deployment_url}/teachers/curriculum/
2. Check subject category filters science/english are correct as per `CUR-1333`
=> Added new "all" icons for Science/RE subjects in curriculum filtering

src/components/PupilComponents/RelatedSubjectsBanner/banners/FinancialEducationBanner.test.tsx, src/components/PupilComponents/RelatedSubjectsBanner/banners/FinancialEducationBanner.tsx
Music year: 1994
use data to set phase from finance banners on related subjects
Fixes #
1. Go to https://deploy-preview-3331--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-primary-year-1/units
2. Click on finace lesson below
3. You should be linked to primary units
{screenshots}
{screenshots}
=> Feat/pupil 1275/primary banner bug

src/components/SharedComponents/VideoPlayer/VideoPlayer.tsx, src/components/TeacherViews/LessonMedia/LessonMedia.view.tsx
Disable auto captions on PE practical media clips
[PUPIL-1253](https://www.notion.so/oaknationalacademy/Disable-captions-as-default-on-PE-practical-media-clips-1a626cc4e1b180129e79e51531f10ba8)
1. Go to https://deploy-preview-3329--oak-web-application.netlify.thenational.academy/teachers/lessons/passing-and-receiving-skills/media
2. Validate that captions are turned off by default for pe practical lesson
3. Validate captions are turn off by default for other lessons
=> PUPIL-1253 Disable captions on PE practical media clips

src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.test.tsx, src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.tsx, src/components/CurriculumComponents/UnitModal/UnitModal.tsx, src/node-lib/curriculum-api-2023/generated/sdk.ts, src/node-lib/curriculum-api-2023/queries/curriculumSequence/curriculumSequence.gql, src/node-lib/curriculum-api-2023/queries/curriculumSequence/curriculumSequence.schema.ts, src/pages-helpers/curriculum/docx/builder/8_units/unit_detail.ts, src/utils/curriculum/fixtures/curriculumunits-english-primary.fixture.ts, src/utils/curriculum/fixtures/curriculumunits-english-secondary.fixture.ts, src/utils/curriculum/fixtures/curriculumunits-science-secondary.fixture.ts
This PR changes from using `cycle` to determine wether to show unit-description/WTWN to using the parent programmes `features.unit_description`
Fixes `CUR-1351` & `CUR-1355`
1. Go to https://deploy-preview-3332--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. Check that units that previously used prior/future units still display those in the unit modals
3. Check that units that previously used unit-description/WTWN still display those in the unit modals
=> Use `features` of parent programme to determine whether to show unit-description/WTWN

src/utils/curriculum/formatting.ts
Music year: 1957
Fixes `CUR-1329`
{screenshots}
{screenshots}
=> Subheadings not displaying correctly for years without subcategories

src/components/GenericPagesComponents/CurriculumTab/CurriculumTab.tsx, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap
- Updated design to system to include new colour filter tokens and squiggle icon
- Added squiggle icon behind the teacher illustration
- Updated snapshots
Fixes `CUR-1163`
1. Go to https://deploy-preview-3340--oak-web-application.netlify.thenational.academy/curriculum
2. You should see that the illustration of the teacher writing on the whiteboard now has a squiggly line behind it
=> Background squiggle in curriculum lander

src/components/GenericPagesComponents/CurriculumTab/CurriculumTab.tsx, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap
Fixes text selection issue on curric lander.
1. Go to https://deploy-preview-3341--oak-web-application.netlify.thenational.academy/curriculum
2. Check text selection and picker works as expected.
=> `pointer-events: none` to fix text selection issue

src/components/CurriculumComponents/CurricVisualiserFiltersMobile/index.tsx, src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts
Music year: 2010
- Fix mobile filtering closing bug
Fixes #[1371](https://www.notion.so/oaknationalacademy/Mobile-filtering-closing-after-each-selection-1ca26cc4e1b180beaf37fedd33cf2c44?pvs=4)
1. Go to {owa_deployment_url}/teachers/curriculum/english-secondary-edexcel
2. Switch to responsive mobile view in Chrome
3. Click the mobile filter
4. Select options within the filter
5. The filter should only close when you click apply
{screenshots}
{screenshots}
=> Fix mobile filtering closing bug

.github/workflows/post_deployment_actions.yml, pa11yci.config.js, src/__tests__/pages/teachers/search.test.tsx, src/pages/teachers/search.tsx
Music year: 1953
- Changes SEO metadata to noindex on search results pages
Fixes #
1. Go to https://deploy-preview-3347--oak-web-application.netlify.thenational.academy
2. Search using a keyword
3. Check the dev tools elements and you should see `<meta name="robots" content="noindex,follow">` in the head on the search results page
{screenshots}
{screenshots}
=> fix: set search results pages to noindex

src/components/GenericPagesComponents/PostPortableText/PostPortableText.tsx, src/pages/blog/[blogSlug].tsx
Adds missing heading styles to the blogs.
hotfix
1. Go to https://deploy-preview-3348--oak-web-application.netlify.thenational.academy/blog/your-top-5-questions-about-aila-our-ai-lesson-assistant-answered
2. Check for any regressions on blogs
=> Added heading styles to blogs

src/components/CurriculumComponents/CurricVisualiserFilters/CurricFiltersYears.tsx, src/components/CurriculumComponents/CurriculumVisualiser/index.tsx, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts, src/utils/curriculum/pathways.test.ts, src/utils/curriculum/pathways.ts
Added subheading for core/gsce to years in curric visualiser.
Note: This is just the missing tests, the work was completed in the main branch as a part of the initial spike.
Fixes `CUR-1322`
2. Check non-core pathways have Core/GCSE sub-heading
=> Added subheading for core/gsce to years in curric visualiser

src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx
Fixes bottom heading margin `<CurriculumHeader/> with medium width viewport
hotfix
1. Go to https://deploy-preview-3355--oak-web-application.netlify.thenational.academy/teachers/curriculum/computing-secondary-core/units
2. Verify spacing is correct with a medium width viewport
Before
After
How it used to look (de
=> Fix bottom heading margin `<CurriculumHeader/>` with medium width viewport

src/pages/api/curriculum-downloads/index.ts
We currently have a caching issue with Netlify caching the first response form the downloads.
hotfix
1. Go to https://deploy-preview-3357--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Regression test curric downloads
=> Try to add `Netlify-Vary` to 307 redirect fix netlify cache issue

src/__tests__/pages/teachers/curriculum/[subjectPhaseSlug]/[tab].test.tsx, src/components/CurriculumComponents/CurriculumDownloadTab/CurriculumDownloadTab.test.tsx, src/components/CurriculumComponents/CurriculumDownloadView/CurriculumDownloadView.test.tsx, src/components/CurriculumComponents/CurriculumDownloadView/index.tsx, src/utils/curriculum/constants.ts
Disable curriculum downloads in the UI while we wait for a fix from netlify
hotfix
1. Go to https://deploy-preview-3361--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Check downloads shows the following message, both when logged in an logged out.
=> Disable curriculum downloads while waiting on a fix from netlify

src/components/CurriculumComponents/CurriculumVisualiser/index.tsx, src/pages-helpers/curriculum/docx/builder/8_units/8_units.ts, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts
Music year: 2008
- Moved the subject override from year group title to subheading
- Removed getSuffixFromFeatures function
@HelenHarlow is it okay if there's a comma between the subject title and GCSE in the subheading? (Refer to screenshot below)
Fixes #[1320](https://www.notion.so/oaknationalacademy/Change-computer-science-exception-for-new-style-1b326cc4e1b180509c91d2b8f47b3e90?pvs=4)
1. Go to https://deploy-preview-3360--oak-web-application.netlify.thenational.academy/teachers/curriculum/computing-secondary-aqa/units
2. Navigate to Year 10 & 11
3. Refer to the below screenshot for what you should see
=> Add Computer Science to year group subheading

src/utils/curriculum/constants.ts
Re-enable curriculum downloads after netlify fix
hotfix
1. Go to https://deploy-preview-3363--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Test curric downloads work as expected
=> Re-enable curriculum downloads after netlify fix

src/components/CurriculumComponents/UnitModal/UnitModal.tsx, src/pages-helpers/curriculum/docx/builder/8_units/unit_detail.ts, src/utils/curriculum/constants.ts, src/utils/curriculum/features.test.ts, src/utils/curriculum/features.ts
Add config to allow WTWN to be enabled via flag
1. Go to https://deploy-preview-3365--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Check all cycle 1 subjects use prior/future units rather than WTWN and unit-description.
=> Add config to allow WTWN to be enabled via flag

src/components/CurriculumComponents/UnitModal/UnitModal.tsx, src/pages-helpers/curriculum/docx/builder/8_units/unit_detail.ts, src/pages-helpers/curriculum/docx/builder/helper.ts, src/pages-helpers/curriculum/docx/tab-helpers.ts, src/utils/curriculum/formatting.test.ts, src/utils/curriculum/formatting.ts, src/utils/curriculum/sorting.test.ts, src/utils/curriculum/sorting.ts
Datatype has changed for all-years swimming, this PR makes the changes required to fix that
Fixes `CUR-1384`
1. Go to https://deploy-preview-3367--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Go to physical education -> primary
3. Check filtering and "all years" works as expected
=> Datatype has changed for all-years swimming

package-lock.json, package.json, src/components/PupilComponents/QuizQuestionStem/QuizQuestionStem.tsx
- Updated oak components to use latest OakCodeRenderer with Code colour tooltip
- Made QuizQuestionStem text span full available width
When code blocks were being rendered in code in quizzes the width of the code block would match the width of the question text and not span all available space.
1. Go to [quiz in preview deploy](https://deploy-preview-3368--oak-web-application.netlify.thenational.academy/pupils/programmes/computing-secondary-year-9/units/python-programming-with-sequences-of-data/lessons/creating-lists-in-python/exit-quiz)
2. Example of the code block quiz is question 5 here: [`/pupils/programmes/computing-secondary-year-9/units/python-programming-with-sequences-of-data/lessons/creating-lists-in-python/exit-quiz`](https://deploy-preview-3368--oak-web-application.netlify.then …
=> chore: made the QuizQuestionStem titles full width to ensure code blocks always go full width

package-lock.json, package.json, src/components/PupilViews/PupilLessonListing/PupilLessonListing.view.tsx, src/components/PupilViews/PupilLessonOverview/PupilLessonOverview.view.tsx, src/components/SharedComponents/ExpiringBanner/ExpiringBanner.test.tsx, src/components/SharedComponents/ExpiringBanner/ExpiringBanner.tsx, src/components/TeacherViews/LessonOverview/LessonOverview.view.tsx, src/pages/teachers/beta/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx, src/pages/teachers/programmes/[programmeSlug]/units/[unitSlug]/lessons.tsx
Music year: 1953
- Updated oak component version to utilise new OakInlineBanners
- Updated Expiring Lesson Banners new large variant and warning type
- Updated existing inline banners so that they are no longer dismissable
[Link to designs](https://www.figma.com/design/dGO9erL0b0kpYxmv6Jku4f/Lessons-takedown-banners?node-id=2177-4655&p=f&m=dev)
1. Go to https://deploy-preview-3372--oak-web-application.netlify.thenational.academy/teachers/programmes/geography-primary-ks2-l/units/mountains-volcanoes-and-earthquakes-e02a/lessons/what-is-the-earth-made-of-6hk3ec
2. You should see the updated alert banner in a warning style (same as designs)
1. Go to https://deploy-preview-3372--oak-web-application.netlify.thenational.academy/teachers/programmes/geography-primary-ks2-l/units/mountains-volcanoes …
=> PUPIL-1280 refactor: updated expiring banner for teacher and pupil lesson overview and listing pages

release.config.js
This reverts commit daecbfcc813423217999e52e1de656c970b70340, reversing changes made to 611806094c65ba9fbc5155a502ac7c2ac781451c.
Music year: 1971
- Reverts the semantic release config change as the release notes configuration doesn't work.
=> ci: revert semantic release config change

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.test.tsx, src/components/CurriculumComponents/CurriculumVisualiser/fixtures.ts, src/utils/curriculum/by-pathway.ts
- Remove empty year from the visualiser for core/gcs
- Amended tests and test fixtures to reflect new filtering
Fixes #
1. Go to https://deploy-preview-3375--oak-web-application.netlify.thenational.academy/teachers/curriculum/computing-secondary-aqa/units?years=10&pathways=core
2. Click on Year 10 (Core)
3. You should see a non-empty year populated with units
=> Remove empty year from the visualiser for core/gcse

src/components/CurriculumComponents/CurriculumUnitDetails/CurriculumUnitDetails.tsx, src/components/CurriculumComponents/CurriculumUnitDetailsAccordion/CurriculumUnitDetailsAccordion.tsx
Add the following
- Add headings to unit modal accordions — `CUR-1387`
- Mark up unit modal threads as unordered list — `CUR-1389`
Fixes `CUR-1387` and `CUR-1389`
`CUR-1387`
1. Go to https://deploy-preview-3380--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Accordian modal titles should be marked up as `<h3/>`
`CUR-1389`
2. Check threads in the unit modals are marked up as a list
`CUR-1387`
`CUR-1389`
=> A11y fixes

src/components/CurriculumComponents/CurriculumHeaderTabNav/index.tsx
Adding missing `<ul/>`/`<li/>` to curriculum heading nav
Fixes `CUR-1391`
1. Go to https://deploy-preview-3379--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Nav should be marked up with `<ul>`/`<li>`
=> A11y fix adding `<ul/>`/`<li/>` to curriculum heading nav

src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx, src/utils/curriculum/filtering.test.ts, src/utils/curriculum/filtering.ts
Fix unit count in curric-visualiser and refactored `getNumberOfSelectedUnits(...)`, which was previously removed accidentally.
Fixes `CUR-1394`
2. Check unit count is correct and no longer displays zero
=> Fix unit count in curric-visualiser

src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx
Accessibility fix added `aria-expanded` to `<SubjectPhasePicker/>`
Fixes `CUR-1386`
1. Go to https://deploy-preview-3389--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. When the lot picker "pickers" are open the buttons clicked should have `aria-expanded` attribute set to `true`
=> Added `aria-expanded` to `<SubjectPhasePicker/>`

src/pages-helpers/curriculum/docx/builder/2_tableOfContents.ts, src/pages-helpers/curriculum/docx/builder/__snapshots__/2_tableOfContents.test.ts.snap
Music year: 1981
Fixes #
1. Go to {owa_deployment_url}/teachers/curriculum/english-secondary-edexcel/downloads
2. Click on dowload and inspect the generated .docx file
- [] Considered impact on accessibility
=> fix: add logic to ensure GCSE is correctly appended to a year in TOC

src/components/AppComponents/ErrorBoundary/ErrorBoundary.tsx
Only create error boundary once not every render
This prevents aggressive rei-rendering of the entire tree, and is the recommended usage, see <https://docs.bugsnag.com/platforms/javascript/react/capturing-render-errors/>
**Note**: Although this is true for lots of parts of the application, the testing steps below if for my particular usecase.
hotfix
Test the app locally (with `npm run dev`) as it doesn't appear to be an issue in production.
1. Go to http://localhost:3000/teachers/curriculum/english-primary/overview
2. Select the `<h1/>` ("KS1 & KS2 English curriculum") in dev tools
3. Navigate to the explainer
4. The same DOM node should remain present, if the selection gets reset it means that the DOM node was recycled.
Also verify on the `main` branch that the above does indeed fail.
=> Only create error boundary once not every render

src/components/AppComponents/ErrorBoundary/ErrorBoundary.tsx
Reverts oaknational/Oak-Web-Application#3407
Reverted as it's causing warnings 🤦
```
console.error
Bugsnag.getPlugin() was called before Bugsnag.start()
```
=> Revert "Only create error boundary once not every render"

src/components/AppComponents/ErrorBoundary/ErrorBoundary.tsx
Only create error boundary once not every render
This prevents aggressive rei-rendering of the entire tree, and is the recommended usage, see <https://docs.bugsnag.com/platforms/javascript/react/capturing-render-errors/>
**Note**: Although this is true for lots of parts of the application, the testing steps below if for my particular usecase.
**Also note:** Previous attempt reverted in https://github.com/oaknational/Oak-Web-Application/pull/3408
hotfix
Test the app locally (with `npm run dev`) as it doesn't appear to be an issue in production.
1. Go to http://localhost:3000/teachers/curriculum/english-primary/overview
2. Select the `<h1/>` ("KS1 & KS2 English curriculum") in dev tools
3. Navigate to the explainer
4. The same DOM node should remain present, if the selection gets reset it …
=> Only create error boundary once not every time

percy.config.js, src/components/SharedComponents/VideoPlayer/VideoPlayer.tsx
In the percy tests we end up in a state where sometimes videos are loaded and sometimes they aren't. Rather than adding hacks in to disable videos in the code, I've instead just added a `data-percy-hide="contents"` to allow the disabling anything we like in the percy tests
> Why not stop the video from loading entirely
Because we use the preview URL to do the testing against, we'd need a conditional in the querystring (or something like that) to disable loading entirely. This seems like a much simpler and robust solution.  Also `data-percy-hide="contents"` is very easy to identify during development.
Fixes `FEC-82`
To test OWA
1. Go to https://deploy-preview-3402--oak-web-application.netlify.thenational.academy
2. Check videos still work as expects and still looks correct
To test percy: …
=> Added `data-percy-hide` attribute to prevent race condition in video content

src/__tests__/pages/teachers/lessons/[lessonSlug].test.tsx, src/components/TeacherComponents/TeacherShareNotesButton/TeacherShareNotesButton.test.tsx, src/components/TeacherComponents/TeacherShareNotesButton/TeacherShareNotesButton.tsx, src/pages-helpers/teacher/share-experiments/useTeacherNotes.ts, src/pages-helpers/teacher/useLesson/useLesson.tsx
- Removed feature flag check for teacher notes
- Hide teacher notes button when cookies have not been accepted/rejected
- Disabled teacher notes button shows if cookies are rejected
- Enabled teacher notes button shows if cookies are accepted
Fixes [https://www.notion.so/oaknationalacademy/Loading-performance-of-teacher-notes-button-lesson-overview-19f26cc4e1b180a29adee94d71511581?pvs=4](https://www.notion.so/oaknationalacademy/Loading-performance-of-teacher-notes-button-lesson-overview-19f26cc4e1b180a29adee94d71511581?pvs=4)
1. Go to https://deploy-preview-3401--oak-web-application.netlify.thenational.academy/teachers/programmes/music-secondary-ks3/units/keyboard-fundamentals/lessons/playing-a-melody-in-the-c-position-on-the-keyboard
2. Open in an incognito …
=> fix: removed feature flag check for teacher notes and use cookie conent for hide/enabled/disabled

src/node-lib/educator-api/helpers/saveUnits/useSaveUnits.tsx
Music year: 2005
- refactor useSaveUnits to use arrays instead of sets
- hoping this stops the bug we're seeing `e.difference is not a function` and doesn't raise another issue with it instead
1. Go to https://deploy-preview-3414--oak-web-application.netlify.thenational.academy
2. Go to a unit listing page
3. There should be no errors
4. try again while signed in / out
5. saving and unsaving should still work with the feature flag
=> fix: use arrays instead of sets to see if that resolves the bug

README.md
This PR updates the installation instructions for the repo, previously you needed to ask a colleage for env vars, but now they are stored on 1Password
Outdated installation instructions
1. check the readme file
=> docs: update readme with instructions for getting env vars

src/components/CurriculumComponents/CurriculumVisualiser/CurriculumVisualiser.test.tsx, src/components/CurriculumComponents/CurriculumVisualiser/fixtures.ts, src/components/CurriculumComponents/CurriculumVisualiser/index.tsx, src/utils/curriculum/by-pathway.ts
Fixes regression introduced in https://github.com/oaknational/Oak-Web-Application/commit/3abe6747e87fed940a82f6fb89c2605719f70591
2. Regression test filtering in visualiser
3. Test "continue at" logic in the visualiser works as expected
=> Fix regression when trying to remove empty year in the visualiser

package-lock.json, src/components/PupilComponents/QuizQuestionStem/QuizQuestionStem.stories.tsx, src/components/PupilComponents/QuizQuestionStem/QuizQuestionStem.tsx, src/components/PupilComponents/QuizResultQuestionStem/QuizResultQuestionStem.stories.tsx, src/components/PupilComponents/QuizResultQuestionStem/QuizResultQuestionStem.tsx, src/components/PupilComponents/QuizResults/QuizResults.stories.tsx, src/components/PupilViews/PupilResults/PupilResults.stories.tsx
Music year: 2015
Resolved prop type inference in stories by:
- Making Storybook 'Story' type aliases specific to component props.
- Using 'satisfies' operator for typing the `meta` object.
Fixes #
{screenshots}
{screenshots}
=> Storybook type fixes

src/pages-helpers/curriculum/docx/builder/8_units/unit_detail.ts
Re-enable column breaks now issues have been fixed in office365
Fixes `CUR-863`
1. Go to https://deploy-preview-3423--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Select various sequences from the picker
3. Check that "Lessons in unit" is in the second column
=> Re-enable column breaks in unit detail pages (curric downloads)

src/components/PupilComponents/pupilUtils/getWorksheetInfo.ts
Add lessonSlug to the metadata when the getWorksheetInfo error is thrown. Should allow us to narrow down where this error is occurring and we can look for any patterns across the lessons.
See [this getWorksheetInfo issue](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/67e2c8c07f772e4ec395b7e0?filters[error.status]=open&filters[event.since]=30d) on bug snag.
=> FEC-115 feat: added extra metadata to getWorksheetInfo error coming up in bugsnag

src/components/CurriculumComponents/CurriculumDownloadTab/index.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
Fix margins across curric tabs to fix white gap at top of explainer in tablet breakpoint.
Fixes `CUR-1475`
1. Go to https://deploy-preview-3440--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Select a sequence from the picker, and
- Regression test all the tabs layout correctly at all breakpoints
- Test that the white-gap at the top of the explainer tab is no longer present in tablet layout.
=> Fix white gap at top of curric explainer in tablet breakpoint

src/components/CurriculumComponents/OakComponentsKitchen/OakModalNew/Content.tsx, src/components/CurriculumComponents/OakComponentsKitchen/OakModalNew/__snapshots__/index.test.tsx.snap
Fixes bottom half of mobile close button isn't clickable
hotfix
1. Go to https://deploy-preview-3449--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Test closing of curriculum modals
=> fix: overflow causes bottom of close button to not be clickable

next.config.ts, src/components/AppComponents/ErrorBoundary/ErrorBoundary.test.tsx, src/components/AppComponents/ErrorBoundary/ErrorBoundary.tsx, src/components/CurriculumComponents/CurriculumDownloadView/CurriculumResourcesSelector.tsx
Re-enable bugsnag / sentry behind env-variable
Fixes https://www.notion.so/oaknationalacademy/Disable-sentry-in-vercel-PR-1fa26cc4e1b18089bc5efdddb1be3300
Dev code review, test that errors are getting through to bugsnag
=> Re-enable bugsnag / sentry behind env-variable

infrastructure/web/monitoring.tf
Music year: 1966
Updated terraform monitoring to additionally send OWA error logs to datadog log drain for Vercel source. 
[Notion Ticket Here](https://www.notion.so/oaknationalacademy/Datadog-monitoring-20626cc4e1b180eca362e59942a9164b?source=copy_link)
After a terraform deployment, we should see a new monitor on datadog for the vercel errors. [Datadog Montiors](https://app.datadoghq.eu/monitors/manage)
=> feat: added logs for vercel to datadog as part of terraform config

src/__tests__/pages/teachers/programmes/[programmeSlug]/units/unitListing.test.tsx, src/node-lib/curriculum-api-2023/__mocks__/index.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.query.test.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.query.ts, src/node-lib/curriculum-api-2023/queries/unitListing/unitListing.schema.ts, src/pages/teachers/programmes/[programmeSlug]/units.tsx
Music year: 2021
- Add `hasCycle2Content` flag to unitListing query when any units have the cohort `2024-2025` (it seems this cohort is not fully populated in the data but I think it is widespread enough for this use case)
- Conditionally render a banner on unit listing pages with cycle 2 content
- Banner links to curriculum download page
_Note_: the icon on the card is smaller than the figma designs for this ticket and can't be updated without updating oak components
1. Go to https://deploy-preview-3469--oak-web-application.netlify.thenational.academy
2. Go to a unit listing page for a cycle 2 subject, eg. Design and technology
3. You should see the curriculum downloads banner
4. It should link to the curriculum download page
5. Go to a cycle 1 subject and you should not see the banner …
=> Feat/lesq 1447/curriculum download banner [LESQ-1447]

src/components/TeacherComponents/NoSearchResults/SignPostToAila.tsx, src/components/TeacherComponents/PromoBannerWithVideo/index.tsx
Music year: 1991
- Changed button text from 'Get started' to 'Create a lesson with AI' for better context
- Added automatic external link detection using existing isExternalHref utility
- Applied target='_blank' and proper aria-label for external Aila links only
- Maintained existing behavior for internal links in PromoBannerWithVideo component
Fixes AI-840
1. Go to https://deploy-preview-3484--oak-web-application.netlify.thenational.academy
2. Search for a lesson that returns no results
3. Look for the Aila signposting banner with video
4. Verify the button text reads 'Create a lesson with AI'
5. Verify the link opens in a new tab
6. Test with screen reader to confirm proper aria-label
- Button text: 'Get started'
- No explicit new tab indication for screen readers …
=> fix: improve Aila signposting link accessibility for screen readers

src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap, src/context/OakToast/OakToastProvider.test.tsx, src/context/OakToast/OakToastProvider.tsx
This PR fixes an issue where toasts intermittently appeared behind the header. I think this was due to a race condition where the IntersectionObserver evaluated header visibility before DOM was fully rendered. It wasn't just happening in the unit listing page, but on other pages also.
- Added 100ms timeout before observing header element (this feels a bit brittle. from reading around I think [a mutation observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) might be better. I tried to use one but I couldn't get it to work)
- Drive-by fix : Set intersection threshold to 0.5 (header must be 50% visible)
- Drive-by refactor: added a named variable for header visibility to make the code read a bit more clearly
Old behaviour: header is barely visible, toasts are offset …
=> Fix toasts rendering behind the header

jest.setup.js, src/components/TeacherComponents/LessonList/LessonList.test.tsx, src/components/TeacherComponents/LessonList/LessonList.tsx
Added SignPostToAila component positioned between pagination and SEO helper to guide users to AI lesson creation when they can't find what they need.
- Added SignPostToAila component to LessonList component
- Component displays at bottom of lesson listings with video preview and call-to-action
- Passes contextual parameters (subject, key stage) to Aila for better user experience
- Fixed pagination threshold from 5 to 20 lessons to match actual pagination behavior
- Implemented responsive spacing that works with and without pagination present
- Resolved React ref warnings in VideoPlayer component with updated Mux mock
- Updated LessonList test to handle multiple h2 headings
Fixes #AI-81290
1. Go to lesson listing page (e.g., any unit's lessons page)
2. Scroll to bottom of lesson list
3. …
=> feat: add Aila signposting to lesson list

src/components/TeacherViews/LessonMedia/LessonMedia.view.tsx, src/node-lib/curriculum-api-2023/queries/lessonBetaMediaClips/lessonBetaMediaClips.query.ts, src/node-lib/curriculum-api-2023/queries/lessonMediaClips/lessonMediaClips.schema.ts
Music year: 1991
- update query for beta media clips page to convert `undefined` lesson release date values to `null`
- update schema to make lesson release date nullable
- update tracking query lesson release date value when null
- This enables testing copyright restriction work against lessons with media clips with login_required and georestrction applied
Fixes #
500 errors on unpublished lesson media clip pages
1. For a lesson with georestriction go to https://deploy-preview-3491--oak-web-application.netlify.thenational.academy/teachers/beta/lessons/learning-about-the-poet-joseph-coelho/media
3. You should see a media clips page
4. For a lesson with only login required go to https://deploy-preview-3491--oak-web-application.netlify.thenational.academy/teachers/beta/lessons/exploring-conn …
=> feat: enable unpublished media clips page

src/__tests__/pages/api/educator/getSavedContentLists/index.test.tsx, src/components/TeacherViews/MyLibrary/MyLibrary.tsx, src/fixtures/teachers/myLibrary/collectionData.ts, src/node-lib/educator-api/generated/sdk.ts, src/node-lib/educator-api/helpers/saveUnits/useMyLibrary.test.tsx, src/node-lib/educator-api/helpers/saveUnits/useMyLibrary.tsx, src/node-lib/educator-api/queries/getUserListContent/getUserListContent.gql, src/node-lib/educator-api/queries/getUserListContent/getUserListContent.types.ts, src/pages/api/educator/getSavedContentLists/index.ts
Music year: 2004
This PR covers [LESQ-1432](https://www.notion.so/oaknationalacademy/Citizenship-Core-and-GCSE-do-not-have-distinct-label-in-My-library-20326cc4e1b1802abc66c353209128ed?source=copy_link) as well.
- Add `pathway` to my library query and use in programme headers and sidenav subheadings
- Refactor how programme cards are generated to create separate cards for subject categories within a programme (when they don't match the subject)
- Update anchor links to work with multiples of the same programme
1. Go to https://deploy-preview-3492--oak-web-application.netlify.thenational.academy
2. Save a KS4 citizenship unit in each pathway, core and gcse
3. Go to my library
4. You should see separate programme cards for each pathway, with the pathway in the title of the card, linking to …
=> Feat/lesq 1440/my library categories [LESQ-1440]

src/components/CurriculumComponents/CurricUnitCard/CurricUnitCard.tsx, src/components/CurriculumComponents/CurricUnitCard/__snapshots__/CurricUnitCard.test.tsx.snap, src/components/CurriculumComponents/CurricVisualiser/CurricVisualiser.tsx, src/components/CurriculumComponents/CurricVisualiserUnitList/CurricVisualiserUnitList.test.tsx, src/components/CurriculumComponents/CurricVisualiserUnitList/__snapshots__/CurricVisualiserUnitList.test.tsx.snap, src/components/CurriculumComponents/CurricVisualiserUnitList/index.tsx, src/utils/curriculum/analytics.ts
Clicking unit cards in the visualiser now calls `unitOverviewAccessed` again (regression)
Fixes `CUR-1541`
1. Go to https://deploy-preview-3523--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Select a subject/phase from the picker
3. When clicking on the unit cards the `unitOverviewAccessed` analytics call should trigger with the correct details
=> Added back in `unitOverviewAccessed` analytics tracking

src/pages/teachers/lessons/[lessonSlug]/media.tsx
Music year: 2006
- update seo title on canonical media page
Fixes #
Incorrect title on page
1. Go to https://deploy-preview-3528--oak-web-application.netlify.thenational.academy/teachers/lessons/passing-and-receiving-in-games/media
2. You should see `Lesson Media` in the tab title not `Lesson Share`
=> fix: update seo title on canonical media page [LESQ-1401]

infrastructure/project/builds.tf, infrastructure/project/main.tf
- Put Storybook live on vercel
- Temporarily adds `git_branch` and `ignore_command`
Whilst trying to put storybook live on vercel, we encountered a `Deployment not found` error probably because of `feat/eng-1145-vercel-migration` branch. Temporarily linking the branch directly to the domain fixed it.
[ENG-1254](https://www.notion.so/oaknationalacademy/Put-Storybook-live-on-Vercel-21826cc4e1b180ff97d7c8bb68a92a5e)
=> [ENG-1254]: Temporarily adds git_branch and ignore command

src/components/AppComponents/AppHeader/AppHeader.tsx, src/components/AppComponents/AppHeaderUnderline/AppHeaderUnderline.tsx, src/components/SharedComponents/OwaLink/OwaLink.tsx
Music year: 1997
- adjust width of logo in app header on mobile to 24px
- move to a flex layout with even spacing for all items in the app header on mobile 
- update `OwaLink` on logo to `OakLink`
- update positions of app header underline and active link underline to fit new header height
Fixes #
Buttons too close together on small mobiles
1. Go to https://deploy-preview-3526--oak-web-application.netlify.thenational.academy
2. Look at the app header in mobile view, it should match the design on the ticket
3. the tablet & desktop width header should be unchanged
=> Fix: small mobile header layout [LESQ-1429]

src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormSubmit.test.ts, src/components/TeacherComponents/hooks/downloadAndShareHooks/useResourceFormSubmit.ts
When downloading a lesson the `shouldAuthenticate` is now set based on the `teachers-copyright-restrictions` feature flag. Tests have been updated accordingly.
A two-parter with [This PR](https://github.com/oaknational/curriculum-downloads-api/pull/243)
[Fixes #1399](LESQ-1399)
{screenshots}
{screenshots}
=> Update shouldAuthenticate header behaviour

next.config.ts
- attempt to fix failing sso-callback request when signing in via the sign up page in clerk by adding owa.thenational.academy as allowed origin for server actions
- seeing the following errors in server logs when a sign in fails:
We saw a similar error on deploy preview domains when updating to next 15 and adding to allowed origins was the solution. It's not clear to me why the forwarded host header would now have value `owa.thenational.academy` to begin with in this case though, it's possible this isn't related to the issue with the clerk request failing
We won't be able to test properly until it's deployed, but we shuld ensure sign up is still working as expected
1. Go to https://deploy-preview-3548--oak-web-application.netlify.thenational.academy
2. Click …
=> fix: clerk sign in via sign up

infrastructure/project/builds.tf
-  Since the Load Balancer has been removed for www.thenational.academy, we need to add `www.thenational.academy` as a custom domain on the Vercel project
[ENG-1274](https://www.notion.so/oaknationalacademy/Remove-the-load-balancer-from-www-23926cc4e1b180d7b773f2feab506dea)
1. check that `www.tn.a` has been created and attached to the vercel project
=> [ENG-1274] Attach www.tn.a domain directly to project 

src/pages-helpers/curriculum/xlsx/index.ts
Add in unit optionality to NC downloads
Fixes `CUR-1505`
1. Go to https://oak-web-application-website-3ob63i4uh.vercel-preview.thenational.academy/teachers/curriculum
2. Navigate to NC downloads
3. Verify unit optionality is correct as-per ticket
4. Verify no regressions in NC spreadsheet
=> Add in unit optionality to NC downloads

package-lock.json, package.json
- Update oak-components to latest version to include fixes for `OakUnitHeadings`, `OakUnitListItem`, and `OakUnitOptionalityListItem`
Fixes LESQ-1465
1. Go to [https://oak-web-application-website-git-fix-lesq-1465unit-listin-e3668a.vercel-preview.thenational.academy](https://oak-web-application-website-git-fix-lesq-1465unit-listin-e3668a.vercel-preview.thenational.academy)
2. Go to a unit listing page with optionality units [https://oak-web-application-website-git-fix-lesq-1465unit-listin-e3668a.vercel-preview.thenational.academy/teachers/programmes/english-secondary-ks4-aqa/units](https://oak-web-application-website-git-fix-lesq-1465unit-listin-e3668a.vercel-preview.thenational.academy/teachers/programmes/english-secondary-ks4-aqa/units)
3. You should see the …
=> fix: unit list accessibility issues

infrastructure/project/builds.tf, infrastructure/project/locals.tf, infrastructure/project/variables.tf
-  Remove ignore build and git branch since migration to vercel is complete, `feat/eng-1145-vercel-migration` has been merged into main
- Refactor sensitive env vars to individual variables for easier management. Currently, we need to know all the values of sensitive env var object when we add/update a var because TFC hides sensitive values. This ticket breaks down the monolithic senstive env vars object into individual variables, making it easier to update single sensitive values without knowing all others
[ENG-1244](https://www.notion.so/oaknationalacademy/7a067876b8d94be0b4100d6c831d5a1a?v=450b96370cb34a7dacd6994b6a8540c4&p=21826cc4e1b1804897f6ea2237d0fab0&pm=c)
1.Terraform plan should show no changes
=> [ENG 1244] Refactor sensitive env vars

src/components/CurriculumComponents/CurriculumDownloadTab/CurriculumDownloadTab.test.tsx, src/components/CurriculumComponents/CurriculumDownloadTab/index.tsx, src/components/CurriculumComponents/CurriculumDownloadView/CurriculumDownloadView.stories.tsx, src/components/CurriculumComponents/CurriculumDownloadView/CurriculumDownloadView.test.tsx, src/components/CurriculumComponents/CurriculumDownloadView/CurriculumResourcesSelector.tsx, src/components/CurriculumComponents/CurriculumDownloadView/SignedInFlow.tsx, src/components/CurriculumComponents/CurriculumDownloadView/SignedOutFlow.tsx, src/components/CurriculumComponents/CurriculumDownloadView/index.tsx, src/components/TeacherComponents/CurriculumDownloadBanner/useCurriculumDownloads.tsx
Allow download of multiple files from curric downloads
Fixes `CUR-618`
1. Go to https://oak-web-application-website-c1tt0rap4.vercel-preview.thenational.academy/teachers/curriculum/english-primary/downloads
2. Select files
3. Click download
This PR downloads multiple files rather than a `.zip`. I think this is supported by all browsers, but we'd need to double check during QA. Also check with @HelenHarlow on her return this is desired behaviour
=> Allow download of multiple files from curric downloads

src/pages-helpers/curriculum/xlsx/helper.test.ts, src/pages-helpers/curriculum/xlsx/helper.ts
NC alignment document fixes for swimming all-years unit ordering
Fixes `ADOPT-1550`
1. Go to https://oak-web-application-website-git-fix-adopt-1550-swimming-f0405d.vercel-preview.thenational.academy/teachers/curriculum
2. Go to the physical-education primacy sequence and verify unit numbering is now correct
3. Verify the unit numbering in other sequences is still correct
Functioning correctly in physical-education primary all-years
Functioning correctly for subject category grouped units
Functioning correctly for regular non-grouped units
=> NC document fix swimming all-years unit ordering

infrastructure/project/.terraform.lock.hcl, infrastructure/project/builds.tf, infrastructure/project/main.tf
- This update replaces Cloudflare Access Apps with Vercel's native deployment protection for hosted applications. Authentication is now handled entirely by Vercel using `project_visibility` variable to toggle between `private/public` modes with the exception of `owa.thenational.academy` because its a custom domain and setting it to public means all custom domains will be publicly available
[ENG-1316](https://www.notion.so/oaknationalacademy/Remove-Cloudlfare-Access-Apps-config-25d26cc4e1b18041a117fd9d6e002797)
=> [ENG-1316] Updates module version

src/components/TeacherComponents/LessonMediaAttributions/LessonMediaAttributions.test.tsx, src/components/TeacherComponents/LessonMediaAttributions/LessonMediaAttributions.tsx, src/components/TeacherComponents/LessonOverviewHeaderShareAllButton/LessonOverViewHeaderShareAllButton.test.tsx, src/components/TeacherComponents/LessonOverviewHeaderShareAllButton/LessonOverviewHeaderShareAllButton.tsx
Music year: 2022
- remove remaining `teachers-copyright` feature flag in codebase
Fixes #
Share with pupils button visible when cookies not accepted on lessons with copyrighted content
1. Go to https://oak-web-application-website-b9ebvkuw4.vercel.thenational.academy/teachers/programmes/english-primary-ks2/units/the-jabberwocky-narrative-writing/lessons/understanding-the-plot-of-jabberwocky 
2. Sign out if signed in, and refuse cookies
3. You should not see the share with pupils button
4. This also removes feature flagging from copyright attributions on the media page, I don't think we have any of these to test against
=> Fix/share with pupils button feature flag [LESQ-1600]

src/app/(beta)/timetabling/name/page.test.tsx, src/app/(beta)/timetabling/name/page.tsx, src/app/(beta)/timetabling/new/page.test.tsx, src/app/(beta)/timetabling/new/page.tsx, src/app/(beta)/timetabling/units/page.test.tsx, src/app/(beta)/timetabling/units/page.tsx, src/utils/featureFlags.test.ts, src/utils/featureFlags.ts
`useFeatureFlag()` now just returns value and does type assertion on returned value
Safe usage is now
```ts
const flagBooleanValue = await useFeatureFlag("some-flag", "boolean");
const flagStringValue = await useFeatureFlag("some-flag", "string");
```
n/a
Test https://oak-web-application-website-fr0s92pqx.vercel.thenational.academy/timetabling/new is only shown when feature flag is enabled.
=> `useFeatureFlag()` now just returns value and does type assertion on returned value

src/browser-lib/fixtures/curriculumPhaseOptions.ts, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.test.tsx, src/components/CurriculumComponents/CurriculumHeader/CurriculumHeader.tsx, src/components/CurriculumComponents/UnitsTab/UnitsTab.test.tsx, src/components/GenericPagesComponents/CurriculumTab/CurriculumTab.test.tsx, src/components/GenericPagesComponents/CurriculumTab/__snapshots__/CurriculumTab.test.tsx.snap, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.test.tsx, src/components/SharedComponents/SubjectPhasePicker/SubjectPhasePicker.tsx, src/pages-helpers/curriculum/docx/tab-helpers.ts, src/pages/curriculum/index.tsx, src/pages/teachers/curriculum/index.tsx
When changing the selection in the in the lot-picker the tab no longer changes. 
Fixes `ADOPT-1568`
1. Go to https://oak-web-application-website-7u1duza8q.vercel.thenational.academy/teachers/curriculum/
2. Make a selection in the lot picker
3. Change tabs to something other than "units"
4. Change the lot picker and press "view"
5. The tab should stay consistent
=> Preserve tab with changing selection in the lot picker

src/__tests__/pages/api/search/intent.test.ts, src/errors/OakError.ts, src/pages/api/search/intent.ts, src/pages/api/search/schemas.ts
Music year: 1967
- This is the base for our other tasks around search intent
- Returns dummy content
- Type "maths" for an exact match
- Type anything else for an AI-style match
Fixes #AI-1597
```bash
curl "https://oak-web-application-website-git-feat-search-intent-scaffold.vercel.thenational.academy/api/search/intent?searchTerm=maths"
curl "https://oak-web-application-website-git-feat-search-intent-scaffold.vercel.thenational.academy/api/search/intent?searchTerm=some+valid+search+term"
```
=> feat: add empty endpoint scaffold for search intent [AI-1597]

src/components/AppComponents/LayoutSiteFooter/LayoutSiteFooter.tsx
Hide cyber essentials logo from percy as it's flakey and causes lots of false percy errors.
hotfix
Check that the logo no longer appears in percy
=> Hide cyber essentials logo from percy
